### ISSUE TITLE
Unable to Precompile Assets on Latest Revision

### ISSUE THREAD

**Issue by blakewatters** [activescaffold/active_scaffold#141]
I recently tried to update from 9d41fa9c3ef941f78e828b6c548b693537b09fe5 to ab2dae8cc7da5957720bf911d0a66785056fc70e (latest HEAD as of this writing). I had to step back to the previously bound revision because rake assets:precompile was bombing out with: 

rake aborted!
File to import not found or unreadable: active_scaffold_layout.

My application.css contains: *= require active_scaffold

**Comment by bretweinraub** [comment]
At least for me I had to move sass-rails out of the :assets group a la:

 https://github.com/alphagov/publisher/commit/1b893fed99fc77ffcfea40837b53bb0b45c00ec6

**Comment by blmundie** [comment]
+1

**Comment by chrishawk** [comment]
I'm running into the same issue - "File to import not found or unreadable: active_scaffold_layout." sass-rails is not in an asset group, config.assets.initialize_on_precompile enabled or disabled doesn't have an effect. I noticed that active_scaffold_layout is a .css file. Should it be an scss at this point?

**Comment by scambra** [comment]
I don't think css it's an issue. I have working it for several apps.

:assets group is not used anymore for rails 4

@chrishawk can you reproduce it with a new blank app?
