### ISSUE TITLE
Mark action doesn't work in nested scaffolds

### ISSUE THREAD

**Issue by Envek** [activescaffold/active_scaffold#189]
Mark action has no effect in nested scaffolds.

On checkbox click POST request sending and returning with code 200. No messages pop-ups. (But they exists in answer).

If run a method, the `marked_records` set will be empty, `each_marked_record` enumerator yields nothing.

But if execute in debugger something like `Stub.all.map{|s| s.as_marked}` it will return meaningful `[true, false, false, false, false]`

Additionaly, if analyse returned messages (those, that doesn't display), it seems, that mark action in nested scaffold tries to mark ALL elements (i.e. doesn't account relationship to belongs_to record)

I've tested it on Ruby REE and 1.9.3 against latest published Active Scaffold (3.2.15) and on 1.9.3 against current master on Ubuntu Linux 12.04 32-bit.
### How to reproduce

``` shell
rvm use 1.9.3
rails new as_mark
cd as_mark
echo "gem 'active_scaffold'" >> Gemfile
echo "gem 'therubyracer', :group => :development" >> Gemfile
echo "gem 'debugger', :group => :development" >> Gemfile
bundle update
rails g active_scaffold stuff name:string
rails g active_scaffold stub name:string value:integer
rake db:migrate
```

Don't forget to include AS into assets manifest files.

Make models look like this:

``` ruby
class Stuff < ActiveRecord::Base
  has_many :stubs
  attr_accessible :name
end

class Stub < ActiveRecord::Base
  belongs_to :stuff
  attr_accessible :name, :value
end
```

Set up controllers like this:

``` ruby
class StuffsController < ApplicationController
  active_scaffold :stuff do |conf|
    conf.nested.add_link :stubs
  end
end

class StubsController < ApplicationController
  active_scaffold :stub do |conf|
    conf.actions.add :mark
    conf.action_links.add :sum, :type => :collection, :position => nil
  end

  def sum
    @sum = each_marked_record.map(&:value).compact.sum
    debugger
    respond_to_action :sum
  end

protected

  def sum_respond_to_js
    render :partial => "sum"
  end

end
```

Template (`app/views/stubs/_sum.html.erb`):

``` ruby
<p><%= @sum %></p>
```

And don't forget for routes:

``` ruby
resources :stuffs do as_routes end

resources :stubs do
  as_routes
  collection do
    get :sum
  end
end
```

Now run an application, go to the /stuffs and create a couple of stuffs and associated stubs. Try to select and deselect them and run the `sum` action and look in the debugger.

**Comment by vtt** [comment]
I think that this problem is caused by the column name "value".  The mark action uses this parameter to indicate marked/non-marked.  But the parameter is being used to filter out the records due to having the same column name "value"
