### ISSUE TITLE
jQuery(document).on('ajax:complete', 'a.as_paginate' doesn't seem to be getting called

### ISSUE THREAD

**Issue by ghost** [activescaffold/active_scaffold#257]
We are trying to run some custom code after pagination is complete. I was not able to get anything to run in either my code or in active_scaffold.js for jQuery(document).on('ajax:complete', 'a.as_paginate', function(event){
  console.log('complete');
  return true;
});

I noticed that app/views/active_scaffold_overrides/_refresh_list.js.erb is being rendered and thought that maybe it was stopping the 'ajax:complete' event from firing. I noticed that you are firing as:element_udpate on replace_html and I am able to detect that event.

I'm not sure what the desired behavior should be, but feel like you would want all the ajax events to fire that should.

using:
 ruby-1.9.3
 rails-3.2.13
 active_scaffold (3.3.0.rc3)

**Comment by vinhne** [comment]
fafafsd

**Comment by vinhne** [comment]
adfsdfdsf
