### ISSUE TITLE
Inline Constraints Not working - Executing Wrong Query

### ISSUE THREAD

**Issue by srini-salem** [activescaffold/active_scaffold#305]
Active Scaffold Config in Controller

   active_scaffold :app_floor_history do |config|
    config.columns =[:project_id, :floor_developer_id, :app_from_floor_id, :app_to_floor_id, :start_date, :end_date, :tools, :execution_info, :status]
    config.list.columns =[:project_id, :app_from_floor_id, :app_to_floor_id, :start_date, :end_date, :floor_developer_id, :tools, :execution_info, :status]
    config.list.columns.exclude :created_at, :updated_at
    config.create.columns.exclude :created_at, :updated_at
    config.update.columns.exclude :created_at, :updated_at 
    config.actions.exclude :delete, :show, :update, :create
    config.columns[:app_from_floor_id].label = "From Floor"
    config.columns[:app_to_floor_id].label = "New Floor"
  end

In views i specified

<%= render :active_scaffold=>"app_floor_histories", :constraints=>{:project_id=> 1, :app_to_floor_id=> 2}, :label=>"Analysis Phase" %>

But it executing the wrong query

  ←[1m←[35m (0.0ms)←[0m  SELECT COUNT(DISTINCT "app_floor_histories"."id") FROM
"app_floor_histories" WHERE "app_floor_histories"."id" = 1 AND (project_id = 1 a
nd app_to_floor_id = 2)

Bug:

As part of my constraint :project_id=> 1, :app_to_floor_id=> 2, it is taking additional constraint "app_floor_histories"."id" = 1.

Any resolution for this?

I am using Rails 3.2.13 and Active_scaffold 3.3.3

Thanks in Advance

**Comment by scambra** [comment]
closing, not enough info to reproduce it
