### ISSUE TITLE
Active Scaffold 3.3.3 - not working edit,show,search etc links.

### ISSUE THREAD

**Issue by pbharadiya** [activescaffold/active_scaffold#374]
Hi,
I am having hard time to figure out why my active scaffold pages not working properly.
I am not getting any AJAX error when I check in firebug console but content is not replacing in front UI.
Info :
active_scaffold -> 3.3.3
rails -> 3.2.12

Any help is highly appreciable.

Thanks!

**Comment by scambra** [comment]
closing it, not enough information

**Comment by pbharadiya** [comment]
Sorry for being late. It solved the issue by properly setting order of active_scaffold.js

**Comment by x1wins** [comment]
@pbharadiya hello
I have same issue too
how solved this problem?

**Comment by pbharadiya** [comment]
@x1wins I could solve issue by properly setting order of active_scaffold.js
e.g in my manifest file, I have below chunk of lines.
<pre><code>//= require prototype
//= require prototype_ujs
//= require active_scaffold</code></pre>

That means, you should have your prototype or jQuery above active_scaffold
