### ISSUE TITLE
datepicker 

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#377]
Hi, 
I managed to get sortable and the papaerclip upload working nicely. The last thing I need to do is get the the datepicker going. I looked at the other issues surrounding this and made sure that i did have jQuery.ui.datapicker loading and that the active scaffold form ui was indeed being set to datepicker.  All that is being rendered it a text box.  Below is my code for activescaffold config:

    config.columns[:date].form_ui = :datepicker  
    config.columns[:date].options = {options: [[changeYear: true]]}
    
in the javascript console of firefox:

jQuery.ui
jQuery.datepicker

returns:
jQuery.ui jQuery.datepicker
Datepicker { _keyEvent=false, _disabledInputs=[0], _datepickerShowing=false, more...}

I know this has to be something really simple. just not sure what to do here.

Thanks so much for keeping the fire going on this!
--mark

**Comment by scambra** [comment]
You don't need to set form_ui, is set automatically for date columns if you have jquery-ui-rails gem. Anyway I will fix wiki

**Comment by markmcdonald51** [comment]
scambra,

Thanks for the reply. I am messing with the rails engines to see if I can figure out *why* this aint loading the bridges/date_picker/ext and helper correctly into the rails engine... going to investigate soon.

**Comment by markmcdonald51** [comment]
this would also explain why it isn't inputting into the database as excpected as well...

**Comment by markmcdonald51** [comment]
Curious, does anyone have this jQuery datepicker working without intervention? I just wanted to see if the was something I was doing wrong so i just created a new project, added in the necessary gems, eg. activescaffold, jquery and jquery-ui and created a simple active_scaffold controller using the generator with a date column and nothing worked by default.

**Comment by markmcdonald51** [comment]
Not sure exactly what i did to get this working. Now i just cant get the years to go back to a certain date unless i enter it into the text box. Anyway, thanks for your help. I am trying to get this going on rails 4.2 and getting 'super: no superclass method `parent_prefixes'  as the errors....but that is for another issue. Thanks for your help!

**Comment by scambra** [comment]
I have used datepicker in several projects with no issue.

About superclass error in 4.2, is fixed on master

**Comment by markmcdonald51** [comment]
thanks for the response and it all works fine for me now. Cheers!
