### ISSUE TITLE
Ruby 2.2.0 vs 2.1.3  using Rails 4.1.0

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#383]
Hi,

I just noticed something interesting where active scaffold seems to break if you are using the latest ruby 2.2.0 and Rails 4.1.0. Not sure if this is a Rails thing but if I take the Ruby version back to 2.1.3 everything works fine and dandy. I pasted in the error. Lemme know if you need any other info. Going to use Ruby 2.1.3 for this project. Just wanted to report this possible issue. Thanks! --Mark

 Rendered /home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_scaffold-3.4.11/app/views/active_scaffold_overrides/row.js.erb (127.9ms)
Completed 500 Internal Server Error in 249ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
     9: <tr class="record <%= tr_class %>" id="<%= row_id %>" data-refresh="<%= data_refresh %>">
    10:   <% columns.each do |column| %>
    11:     <% authorized = record.authorized_for?(:crud_type => :read, :column => column.name) -%>
    12:     <% column_value = authorized ? get_column_value(record, column) : active_scaffold_config.list.empty_field_text -%>
    13: 
    14:     <%= content_tag :td, column_attributes(column, record).merge(:class => column_class(column, column_value, record)) do %>
    15:       <%= authorized ? render_list_column(column_value, column, record) : column_value %>
  activerecord (4.1.0) lib/active_record/associations/has_many_association.rb:79:in `cached_counter_attribute_name'
  activerecord (4.1.0) lib/active_record/associations/has_many_association.rb:75:in `has_cached_counter?'
  activerecord (4.1.0) lib/active_record/associations/has_many_through_association.rb:20:in `size'
  activerecord (4.1.0) lib/active_record/associations/collection_proxy.rb:729:in `size'
  active_scaffold (3.4.11) lib/active_scaffold/helpers/list_column_helpers.rb:127:in `format_column_value'
  active_scaffold (3.4.11) lib/active_scaffold/helpers/list_column_helpers.rb:9:in `get_column_value'
  active_scaffold (3.4.11) app/views/active_scaffold_overrides/_list_record.html.erb:12:in `block in __home_mark__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold________app_views_active_scaffold_overrides__list_record_html_erb___36885514894858429_70126923264940'
  active_scaffold (3.4.11) app/views/active_scaffold_overrides/_list_record.html.erb:10:in `each'
  active_scaffold (3.4.11) app/views/active_scaffold_overrides/_list_record.html.erb:10:in `__home_mark__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold________app_views_active_scaffold_overrides__list_record_html_erb___36885514894858429_70126923264940'
  actionview (4.1.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.0) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:143:in `render'
  actionview (4.1.0) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  actionview (4.1.0) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/partial_renderer.rb:278:in `render'
  actionview (4.1.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.1.0) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  active_scaffold (3.4.11) lib/active_scaffold/extensions/action_view_rendering.rb:117:in `render_with_active_scaffold'
  active_scaffold (3.4.11) app/views/active_scaffold_overrides/row.js.erb:1:in `__home_mark__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold________app_views_active_scaffold_overrides_row_js_erb__4135322158882132338_70127025173900'
  actionview (4.1.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.0) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:143:in `render'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.0) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.0) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.0) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  active_scaffold (3.4.11) lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render_with_active_scaffold'
  active_scaffold (3.4.11) lib/active_scaffold/actions/list.rb:62:in `row_respond_to_js'
  active_scaffold (3.4.11) lib/active_scaffold/actions/core.rb:269:in `block (3 levels) in respond_to_action'
  actionpack (4.1.0) lib/action_controller/metal/mime_responds.rb:258:in `call'
  actionpack (4.1.0) lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
  active_scaffold (3.4.11) lib/active_scaffold/actions/core.rb:265:in `respond_to_action'
  active_scaffold (3.4.11) lib/active_scaffold/actions/list.rb:20:in `row'
  active_scaffold (3.4.11) lib/active_scaffold/actions/list.rb:10:in `index'
  actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.0) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/rescue.rb:29:in `process_action

**Comment by scambra** [comment]
It's rails bug, fixed on 4.1.3
