### ISSUE TITLE
Request Failed 

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#384]
Hi again!

I am trying to use this with a pretty large site that has what we can now call 'legacy' gems (Rails 4.0.1). It seems to work...well sort of except the actions like update/edit/cancel result in a pink 'Request Failed' at the top. No code or anything like that and nothing in the javascript console. I am using the latest version of Active Scaffold (active_scaffold-3.4.16)  and Jquery (jQuery JavaScript Library v1.11.1), with 'ruby 2.1.3p242'. 

The updates/inserts work fine, it is just seems that Request Failed is coming up instead of closing the form and adding ack the row. Hopefully this is something I can figure out because I dont think the mapping modules they are using can be upgraded (at the moment).

Any help would be totally appreciated.

Thanks in advance.
Mark

**Comment by markmcdonald51** [comment]
also, when I try to view a record inline I get: Use of getPreventDefault() is deprecated. Use defaultPrevented instead.

Uggg, i hope this is a simple js or rails problem that maybe i could fix by upgrades? 

Thanks in advance.

**Comment by scambra** [comment]
ActiveScaffold doesn't use getPreventDefault, maybe jquery_ujs uses it, I don't know.

Can you post response you for create/update request? Copy it from network tab on web inspector

**Comment by scambra** [comment]
closing it, not enough information
