### ISSUE TITLE
Cannot override required = false

### ISSUE THREAD

**Issue by vtt** [activescaffold/active_scaffold#388]
I have a table with fields that cannot be null thus AS automatically makes the columns to have 'required => true'.

This cannot be overrided by forcing config.columns[:field].required = false; as it still show required as true.

(there is a before_save callback that validate/fills the value to be non-null)

**Comment by scambra** [comment]
Are you sure of that? There is no line in AS which sets required based on null not allowed, it's set based on presence or inclusion validation. You can check in rails console with YourController.active_scaffold_config.columns[:field].required

I don't know if other gem or rails can set required based on null not allowed

**Comment by vtt** [comment]
You are quite correct; the model has presence validation (missed that in the wiki).

**Comment by scambra** [comment]
ok, anyway you should be able to remove required

**Comment by scambra** [comment]
I have added some tests about overriding required in a column with validations and it works. Is it failing yet? Can you post your controller?

**Comment by vtt** [comment]
This was an oversight on my part.  I had another function that configure the AS at the bottom of the controller that sets ".required = true" when the column is not nullable.  This broke my manual override.

Thanks for the help and sorry for the trouble.

**Comment by scambra** [comment]
I'm glad to hear it's working
