### ISSUE TITLE
date_picker and localization

### ISSUE THREAD

**Issue by vtt** [activescaffold/active_scaffold#389]
My current project on rails 4.1.9 + AS 3.4.8 running on Ruby 2.2 seems to be working fine; however, I can't seem to localize the date_picker; no matter what the I18n.locale is set, the date_picker dialog always shows in English.

I look in the date_picker_bridge.js, and it contains lots of locales; but it doesn't seem to activate.

What am I missing?

**Comment by scambra** [comment]
Is it working with other ruby? I don't know if can be related. Also, what is jquery ui version and jquery-ui-rails gem version?

**Comment by vtt** [comment]
Problem is the same running on ruby-1.9.3-p429.  In my gem file, it is using:
jquery-rails 3.1.2
jquery-ui-rails 5.0.3

Under jquery-ui-rails 5.0.3, it is using:
jQuery UI Core 1.11.2
jQuery UI Datepicker 1.11.2

**Comment by vtt** [comment]
I tested with a brand new simple Rails 4.1.9 application (rails new demo)

- added the AS gem, 'jquery-rails', 'jquery-ui-rails' to Gemfile and bundle install
- added the :locale scope in config/routes.rb, added :before_filter in application_controller.rb to set I18n.locale
- generate AS model user (rails g active_scaffold User name:string birthday:date) and rake db:migrate
- added AS to assets

Run the rails app (rails s), and visit (http://localhost:3000/fr/users)
- the localization of AS is in French (ie: the labels etc)
- clicking on "Create new user", the create box is localized in French correctly
- clicking on the Birthday input field, the date picker shows up but in English only (NOT localized)

Something is definitely broken.

**Comment by jsurrett** [comment]
I was able to get the date picker to localize placing the following in my application.html.erb file.

    <script>
    $(function() {
      <% if I18n.locale =="en" %>
        $.datepicker.setDefaults( $.datepicker.regional[ "" ] );
      <% else %>
        $.datepicker.setDefaults( $.datepicker.regional[ "<%= I18n.locale %>" ] );
      <% end %>
    });

    </script>

**Comment by scambra** [comment]
Code from @jsurrett is added by ActiveScaffold (a similar code), but it works for a localized web, without dynamic locale selection. I think @vtt needs to change the locale in every request. So a code like this is needed:

```js
<script>
$(function() {
 $.datepicker.setDefaults( $.datepicker.regional[window.locale] );
 $.timepicker.setDefaults( $.timepicker.regional[window.locale] );
});
</script>
```

And a script should be added to layout to set window.locale with <%= I18n.locale %>

**Comment by scambra** [comment]
Closing, it must be done on application level
