### ISSUE TITLE
has anyone tried to integrate AS with https://github.com/tors/jquery-fileupload-rails

### ISSUE THREAD

**Issue by jasonfb** [activescaffold/active_scaffold#394]
I am building an app for Heroku and we are hitting the timeout limit on uploads. I was wondering if there was anyone who had tried an ActiveScaffold integration with jquery-fileupload-rails

other versions exist online, but this is the approach that seems common:
https://github.com/tors/jquery-fileupload-rails

I was hoping an integration could automatically pick up paperclip images and correctly output the Javascript & form to have them transferred via the Direct upload method (explained here https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails)

**Comment by scambra** [comment]
This kind of questions should be asked on google group, not issues
