### ISSUE TITLE
RJS TypeError 

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#409]
up on validations failure in the model. I am getting RJS error. it say TypeError cannot read the property 'top'.

could you help me out, to resolve this

**Comment by scambra** [comment]
can you post response from server? You can get it from network tab on inspector

**Comment by kranthi3896** [comment]
try {
var action_link;
action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
action_link.update_flash_messages('');
  ActiveScaffold.replace('as_exchanges-create--form','<form id=\"as_exchanges-create-2-form\" class=\"as_form create\" data-loading=\"true\" action=\"/exchanges?utf8=%E2%9C%93\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"><input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" />\n  <h4>Create Exchange<\/h4>\n\n  <div id=\"as_exchanges-create--messages\" class=\"messages-container\">\n    \n\n  <div id=\"errorExplanation\" class=\"errorExplanation\"><h2>1 error prohibited this exchange from being saved.<\/h2><p>There were problems with the following fields:<\/p><ul><li>Exchange code has already been taken<\/li><\/ul><\/div>\n\n  <\/div>\n\n  <ol class=\"form\"  >\n  <li class=\"form-element required number \">......
.....
...data of table ...
..........

<img style=\"visibility:hidden;\" id=\"as_exchanges-create-2-loading-indicator\" alt=\"loading indicator\" class=\"loading-indicator\" src=\"/assets/active_scaffold/indicator.gif\" />\n    \n  <\/p>\n\n<\/form>\n\n\n');
  ActiveScaffold.scroll_to('as_exchanges-create--form', true);
} catch (e) { alert('RJS error:\n\n' + e.toString());}

**Comment by scambra** [comment]
Ok, try to run every line of response on inspector console, starting with:
action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
let me know first line giving an error

**Comment by kranthi3896** [comment]
action_link.update_flash_messages('');
VM336:2 Uncaught TypeError: Cannot read property 'update_flash_messages' of null

**Comment by kranthi3896** [comment]
So, here is the thing..

I have two tables... one is working fine and other is not working .

the thing id one action_link is returning null for link "as_exchanges-create--form"

and the other is returning a class object.

I can understand that accessing a function on a null object throws error. how to set this. please help me out.

the below is the console for the commands..

action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
null
action_link.update_flash_messages('');
VM336:2 Uncaught TypeError: Cannot read property 'update_flash_messages' of null


action_link = ActiveScaffold.find_action_link('as_level2_product_mappings-create--form');
Class {tag: jQuery.fn.init[1], url: "/level2_product_mappings/new?adapter=_list_inline_adapter", method: "get", target: jQuery.fn.init[1], loading_indicator: jQuery.fn.init[1]…}
action_link.update_flash_messages('');
undefined

action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
null

**Comment by scambra** [comment]
It seems different error than original one (cannot read the property 'top')
is exchanges create form closed?

**Comment by kranthi3896** [comment]
no .. it was not closed

**Comment by scambra** [comment]
what's id for that form?

**Comment by kranthi3896** [comment]
<tr class="inline-adapter" id="as_exchanges-nested--row">
  <td class="inline-adapter-cell">
    <div class="new-view exchanges-view view">
      <a class="inline-adapter-close as_cancel" title="Close" data-remote="true" href="">Close</a>      <form id="as_exchanges-create--form" class="as_form create" data-loading="true" action="/exchanges" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="&#x2713;" />
  <h4>Create Exchange</h4>

  <div id="as_exchanges-create--messages" class="messages-container">
    
the above is the response after i click create new.

and i fill some values which will fail the validations and hit create.. the responce is 

try {
var action_link;
action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
action_link.update_flash_messages('');
  ActiveScaffold.replace('as_exchanges-create--form','<form id=\"as_exchanges-create-1-form\" class=\"as_form create\" data-loading=\"true\" action=\"/exchanges?utf8=%E2%9C%93\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"><input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" />\n  <h4>Create Exchange<\/h4>\n\n  <div id=\"as_exchanges-create--messages\" class=\"messages-container\">\n    \n\n  <div id=\"errorExplanation\" class=\"errorExplanation\"><h2>1 error prohibited this exchange from being saved.<\/h2><p>There were problems with the following fields:<\/p><ul><li>Exchange code has already been taken<\/li><\/ul><\/div>\n\n  <\/div>\n\n  <ol class=\"form\"  >\n  <li class=\"form-element required number \">\n    <dl><dt><label for=\"record_exchange_code_\">Code<\/label><\/dt><dd><div class=\"field_with_errors\"><input min=\"1\" name=\"record[exchange_code]\" class=\"exchange_code-input numeric-input text-input\" id=\"record_exchange_code_\" required=\"required\"

**Comment by scambra** [comment]
does this line work after click create new?
action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');

**Comment by kranthi3896** [comment]
sorry ....... 

the form id when I click create button is

form id="as_exchanges-create--form" class="as_form create"

and I fill some values which fail validations . it returns with response 

action_link.update_flash_messages('');
  ActiveScaffold.replace('as_exchanges-create--form','

form id=\"as_exchanges-create-1-form\" class=\"as_form create\"

note: If there is no fail at validations , record has been created and create form is closed and  every thing is fine. there is RJS error if there is only fail in validations and the create form is not created . and if I hit update/create button for second time  then it alerts as RJS error: TYPE error TypeError: Cannot read property 'update_flash_messages' of null

**Comment by kranthi3896** [comment]
yes , just now I have tested i have clicked the create new button I got response .....action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');.....

I went to console and pasted the this line

action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
Class {tag: jQuery.fn.init[1], url: "/exchanges/new?adapter=_list_inline_adapter", method: "get", target: jQuery.fn.init[1], loading_indicator: jQuery.fn.init[1]…}

the above is the output
it is returning the class object

**Comment by scambra** [comment]
I'm not sure I understand you. Did you get that error when you send form with validation errors? Or when you send form with validation erorrs and then form again (send form twice)?

**Comment by kranthi3896** [comment]
here is the thing..

1. I sent the form with the validations errors. I will get the notifications above the create form and RJS error alert saying property 'top' is required.

still the form is not closed .. so chagned the data and sent the form which has validations errors . this time the notifications are not changed and RJS error allert saying the "Cannot read property 'update_flash_messages' of null"

still the form was not closed . again changed the data and now i dont have any validations errors. so this time notifications are not changes and there is no RJS error . created the record , but the form is not closed.

the final response is .
try {
var action_link;
action_link = ActiveScaffold.find_action_link('as_exchanges-create--form');
action_link.update_flash_messages('');
    ActiveScaffold.create_record_row(action_link ? action_link.scaffold() : 'as_exchanges-active-scaffold', '<tr class=\"record  \" id=\"as_exchanges-list-3-row\" data-refresh=\"3\">\n\n    <td class=\"exchange_code-column sorted numeric  \">\n      3\n<\/td>\n    <td class=\"name-column  \">\n      afs\n<\/td>\n    <td class=\"iso-column  empty \">\n      <a class=\"disabled  iso\">-<\/a>\n<\/td>\n    <td class=\"constant-column  empty \">\n      -\n<\/td>\n    <td class=\"product-column  empty \">\n      <a class=\"disabled  product\">-<\/a>\n<\/td>\n    <td class=\"provider-column  empty \">\n      <a class=\"disabled  provider\">-<\/a>\n<\/td>\n    <td class=\"timezone_spec-column  empty \">\n      <a class=\"disabled  timezone_spec\">-<\/a>\n<\/td>\n    <td class=\"delay-column  empty \">\n      <a class=\"disabled  delay\">-<\/a>\n<\/td>\n    <td class=\"premarket_open-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"market_open-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"break_start-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"break_stop-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"market_close-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"postmarket_close-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"issue_type-column  empty \">\n      <a class=\"disabled  issue_type\">-<\/a>\n<\/td>\n    <td class=\"site-column  empty \">\n      <a class=\"disabled  site\">-<\/a>\n<\/td>\n    <td class=\"ticker_plant-column  empty \">\n      <a class=\"disabled  ticker_plant\">-<\/a>\n<\/td>\n    <td class=\"threshold-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"offhour_threshold-column numeric  empty \">\n      -\n<\/td>\n    <td class=\"holiday_key-column  empty \">\n      <a class=\"disabled  holiday_key\">-<\/a>\n<\/td>\n    <td class=\"feed_handler-column  empty \">\n      <a class=\"disabled  feed_handler\">-<\/a>\n<\/td>    \n  <td class=\"actions\"><table>\n    <tr>\n      <td class=\"indicator-container\">\n        <img style=\"visibility:hidden;\" id=\"as_exchanges-record-3-loading-indicator\" alt=\"loading indicator\" class=\"loading-indicator\" src=\"/assets/active_scaffold/indicator.gif\" />\n      <\/td>\n      <td><a class=\"edit as_action\" data-position=\"replace\" data-action=\"edit\" id=\"as_exchanges-edit-3-link\" data-remote=\"true\" href=\"/exchanges/3/edit?utf8=%E2%9C%93\">Edit<\/a><\/td><td><a class=\"destroy as_action\" data-confirm=\"Are you sure you want to delete afs?\" data-action=\"destroy\" id=\"as_exchanges-destroy-3-link\" data-remote=\"true\" rel=\"nofollow\" data-method=\"delete\" href=\"/exchanges/3?destroy_action=true&amp;utf8=%E2%9C%93\">Delete<\/a><\/td><td><a class=\"show as_action\" data-position=\"replace\" data-action=\"show\" id=\"as_exchanges-show-3-link\" data-remote=\"true\" href=\"/exchanges/3?utf8=%E2%9C%93\">Show<\/a><\/td>\n    <\/tr>\n  <\/table><\/td>\n<\/tr>\n', {"insert_at":"top"});
    

      action_link.close();
} catch (e) { alert('RJS error:\n\n' + e.toString());}


but still I can see the create form. it is not closed . but record has been updated

**Comment by scambra** [comment]
Checking server response again I found it:
 ActiveScaffold.replace('as_exchanges-create--form','<form id=\"as_exchanges-create-2-form\" 

It's replacing as_exchanges-create--form with a new form with id as_exchanges-create-2-form, instead of same id attribute.

So it seems like record is created. What's the validation error you get? Can you post model and associations in subforms (if any)?

**Comment by kranthi3896** [comment]
model 

class Exchange < ActiveRecord::Base
  self.primary_key = :exchange_code

  validates :exchange_code, uniqueness: true, presence: true ,numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 15000 }
 # validates :constant, uniqueness: true, format: { with: /\A[0-9A-Z_]+\Z/ }
  validates :name, presence: true
  validates :delay_time, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :market_open, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :market_close, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :data_type_id, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :threshold, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :premarket_open, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :postmarket_close, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :break_start, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :break_stop, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  validates :offhour_threshold, numericality: { only_integer: true, greater_than: -1}, allow_blank: true
  # People don't like the way this works so I'm turning it off
  #validates_presence_of :iso, :message => "must be set.  If the exchange doesn't have an ISO yet, use one of the repeating 4 digit ISOs like AAAA, BBBB, etc..."

  belongs_to :product, :foreign_key => "product_code"
  belongs_to :iso, :foreign_key => "iso_code"
  belongs_to :provider, :foreign_key => "provider_code"
  belongs_to :site, :foreign_key => "live"
  belongs_to :delay, :foreign_key => "delay_time"
  belongs_to :issue_type, :foreign_key => "data_type_id"
  belongs_to :timezone_spec
  belongs_to :ticker_plant
  belongs_to :holiday_key, foreign_key: :holidays_key
  belongs_to :feed_handler

  def timezone
    if(self.timezone_spec_id.nil?)
      nil
    else
      "#{timezone_spec.name}"
    end
  end

  def to_s
    "#{name}"
  end
 
  def to_label
    "#{name}"
  end
end



controller

class ExchangesController < ApplicationController

  active_scaffold :exchange do |config|
    config.columns = [:exchange_code, :name, :iso, :constant, :product, 
        :provider, :timezone_spec, :delay, :premarket_open, :market_open, :break_start, :break_stop, :market_close, :postmarket_close, 
        :issue_type, :site, :ticker_plant, :threshold, :offhour_threshold, :holiday_key, :feed_handler]

    ['timezone_spec', 'issue_type', 'delay', 'product','iso', 'provider', 'site', 'ticker_plant','holiday_key','feed_handler'].each do |assoc|
      config.columns[assoc].collapsed = true
      config.columns[assoc].form_ui = :select

      config.columns[assoc].sort = true
    end
   
    ['premarket_open','market_open','break_start','break_stop','market_close','postmarket_close'].each do |assoc|
    config.columns[assoc].options={:i18n_options => {delimiter: ""}} 
  end
    config.columns[:timezone_spec].label = "Timezone"
    config.columns[:market_open].label = "Open"
    config.columns[:market_close].label = "Close"
    config.columns[:exchange_code].label = "Code"
    config.columns[:data_type_id].label = "Type"

    config.columns[:delay_time].description = "Delayed feed time in minutes"
    config.columns[:market_open].description = "Market open time (HHMM)"
    config.columns[:market_close].description = "Market close time (HHMM)"
    config.columns[:exchange_code].description = 
        "For telekurs feeds, use the bourse code"
    config.columns[:constant].description = "MDSExchanges.h constant name.  " +
        "Use only capital letters, underscores and numbers"
    config.columns[:site].description = "What environments this exchange " +
        "is live in.  Marco databases above this threshold will not report " +
        "this exchange"
    #config.columns[:iso].description = "This is required.  Use a test ISO " + 
    #    "like AAAA, BBBB, CCCC, etc. if you don't have an ISO code yet."
  end

end

**Comment by kranthi3896** [comment]
ActiveScaffold.set_defaults do |config|
    config.security.default_permission = true
    config.ignore_columns.add [:created_at, :updated_at, :lock_version]

    config.actions.exclude :search
   config.actions.add :field_search

    config.list.per_page = 30
    config.theme = :default

    config.dhtml_history = false

    config.action_links.add 'export_csv', :label => 'Export to Excel', :page => true
  end

**Comment by kranthi3896** [comment]
ActiveScaffold::DataStructures::Column.actions_for_association_links = [:show, :list]

these are acivescaffold defaults

**Comment by kranthi3896** [comment]
ActiveScaffold.scroll_to('as_exchanges-create--form',true);

the above line throws the exception

**Comment by scambra** [comment]
post server log of first create request, I don't understand why it's replacing form with as_exchanges-create-2-form

**Comment by kranthi3896** [comment]
href=\"/exchanges\">Cancel<\/a>\n <img style=\"visibility:hidden;\" id=\"as_exchanges-create-1-loading-indicator\" alt=\"loading indicator\" class=\"loading-indicator\" src=\"/assets/active_scaffold/indicator.gif\" />\n \n <\/p>\n\n<\/form>\n\n\n');
[]
ActiveScaffold.scroll_to('as_exchanges-create--form', true);
application.js:12320 Uncaught TypeError: Cannot read property 'top' of undefined

**Comment by kranthi3896** [comment]
Started GET "/exchanges/new?adapter=_list_inline_adapter" for 127.0.0.1 at 2015-03-11 06:17:39 -0400
Processing by ExchangesController#new as JS
  Parameters: {"adapter"=>"_list_inline_adapter"}
  User Load (2.1ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = ? LIMIT 1  [["name", "kbandaru"]]
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_form_messages.html.erb (0.3ms)
  Iso Load (5.6ms)  SELECT "isos".* FROM "isos"
  Product Load (4.9ms)  SELECT "products".* FROM "products"
  Provider Load (2.7ms)  SELECT "providers".* FROM "providers"
  TimezoneSpec Load (3.7ms)  SELECT "timezone_specs".* FROM "timezone_specs"
  Delay Load (2.1ms)  SELECT "delays".* FROM "delays"
  IssueType Load (2.1ms)  SELECT "issue_types".* FROM "issue_types"
  Site Load (2.2ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."name" = ? LIMIT 1  [["name", "0"]]
  Site Load (2.3ms)  SELECT "sites".* FROM "sites"
  TickerPlant Load (3.1ms)  SELECT "ticker_plants".* FROM "ticker_plants"
  HolidayKey Load (2.4ms)  SELECT "holiday_keys".* FROM "holiday_keys"
  FeedHandler Load (2.6ms)  SELECT "feed_handlers".* FROM "feed_handlers"
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_form.html.erb (171.9ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_base_form.html.erb (216.3ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_create_form.html.erb (239.1ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_messages.html.erb (0.1ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_list_inline_adapter.html.erb (8.7ms)
Completed 200 OK in 294ms (Views: 28.6ms | ActiveRecord: 36.0ms)


Started POST "/exchanges" for 127.0.0.1 at 2015-03-11 06:17:47 -0400
Processing by ExchangesController#create as JS
  Parameters: {"utf8"=>"✓", "record"=>{"exchange_code"=>"1", "name"=>"sa", "iso"=>"", "constant"=>"", "product"=>"", "provider"=>"", "timezone_spec"=>"", "delay"=>"", "premarket_open"=>"", "market_open"=>"", "break_start"=>"", "break_stop"=>"", "market_close"=>"", "postmarket_close"=>"", "issue_type"=>"", "site"=>"", "ticker_plant"=>"", "threshold"=>"", "offhour_threshold"=>"", "holiday_key"=>"", "feed_handler"=>""}, "commit"=>"Create"}
  User Load (2.2ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = ? LIMIT 1  [["name", "kbandaru"]]
   (0.1ms)  begin transaction
  Exchange Exists (2.3ms)  SELECT  1 AS one FROM "exchanges" WHERE "exchanges"."exchange_code" = 1 LIMIT 1
   (0.7ms)  commit transaction
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_messages.html.erb (0.1ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_form_messages.html.erb (0.7ms)
  Iso Load (5.0ms)  SELECT "isos".* FROM "isos"
  Product Load (4.8ms)  SELECT "products".* FROM "products"
  Provider Load (2.7ms)  SELECT "providers".* FROM "providers"
  TimezoneSpec Load (14.7ms)  SELECT "timezone_specs".* FROM "timezone_specs"
  Delay Load (2.3ms)  SELECT "delays".* FROM "delays"
  IssueType Load (2.6ms)  SELECT "issue_types".* FROM "issue_types"
  Site Load (2.4ms)  SELECT "sites".* FROM "sites"
  TickerPlant Load (3.3ms)  SELECT "ticker_plants".* FROM "ticker_plants"
  HolidayKey Load (2.6ms)  SELECT "holiday_keys".* FROM "holiday_keys"
  FeedHandler Load (2.7ms)  SELECT "feed_handlers".* FROM "feed_handlers"
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_form.html.erb (183.6ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_base_form.html.erb (189.7ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/_create_form.html.erb (192.2ms)
  Rendered /home/user/kbandaru/.rvm/gems/ruby-2.1.4/gems/active_scaffold-3.4.17/app/views/active_scaffold_overrides/on_create.js.erb (206.6ms)
Completed 200 OK in 250ms (Views: 194.2ms | ActiveRecord: 48.4ms)

**Comment by scambra** [comment]
I see issue, you are sending exchange_code in form, which is your primary key too, so it replaces as_exchanges-create--form with as_exchanges-create-<ID>-form, then it tries to scroll to as_exchanges-create--form but it's not found.

**Comment by kranthi3896** [comment]
any help

**Comment by kranthi3896** [comment]
this application was working fine before. now I am upgrading the things and I got this error. 
Is there any thing easy way to get rid of this error.

**Comment by scambra** [comment]
You have this issue because you are setting primary key in form which is not usual in rails.
However you can avoid using :id in create form overriding element_form_id in ApplicationHelper:

```ruby
def element_form_id(options = {})
  options.delete :id if options[:action] == :create
  super options
end

**Comment by kranthi3896** [comment]
thanks very much. I was breaking my head for this.

On Wed, Mar 11, 2015 at 4:35 PM, Sergio Cambra <notifications@github.com>
wrote:

> You have this issue because you are setting primary key in form which is
> not usual in rails.
> However you can avoid using :id in create form overriding element_form_id
> in ApplicationHelper:
>
> def element_form_id(options = {})
>   options.delete :id if options[:action] == :create
>   super optionsend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/activescaffold/active_scaffold/issues/409#issuecomment-78243506>
> .
>



-- 

Thanks,

Kranthi Kumar,
Software Engineer,
Factset Research Systems - India,
Hyderabad.
