### ISSUE TITLE
Save and continue editing

### ISSUE THREAD

**Issue by cassioalmeidas** [activescaffold/active_scaffold#415]
save and continue editing in activescaffold form is possible?

**Comment by scambra** [comment]
it's possible when editing, persistent (https://github.com/activescaffold/active_scaffold/wiki/API%3A-Update#persistent-global-local-24)
For create you can enable action_after_create (https://github.com/activescaffold/active_scaffold/wiki/API%3A-Create#action_after_create-global-local-v23)
