### ISSUE TITLE
Search function when there is a multiple page results.

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#416]
I’m noticing that the search feature/results seems a bit off . , if I get a multi-page result, clicking on next resets the search criteria instead of displaying the next page specific to my search.

**Comment by kranthi3896** [comment]
for your information that is happing only when we are using string as serch and having contains in the type of search ....

**Comment by scambra** [comment]
It's working right here. Please post your controller (only need active_scaffold part), ActiveScaffold.set_defaults block if any, and any initializer with ActiveScaffold settings if any

**Comment by kranthi3896** [comment]
I didnt do much here..
config.security.default_permission = true
    config.ignore_columns.add [:created_at, :updated_at, :lock_version]

    config.actions.exclude :search
   config.actions.add :field_search

    config.list.per_page = 30
    config.theme = :default

    config.dhtml_history = false


config.columns = [:ip,
                      :port,
                      :interface,
                      :name,
                      :feed_group]

    config.columns[:interface].form_ui = :select
    config.columns[:interface].options = {:options => FeedAddress::INTERFACE.map(&:to_sym)}

    ['feed_group'].each do |assoc|
      config.columns[assoc].collapsed = true
      config.columns[assoc].form_ui = :select
    end

**Comment by kranthi3896** [comment]
it is happening only when we do feild search on string and has contains option.

**Comment by scambra** [comment]
I can't reproduce it. By default, search is stored in session, and changing page gets search params from session. Can you debug if session is being reset? What activescaffold version?

**Comment by kranthi3896** [comment]
the thing is that first i am using field search. If I have search on integer field, or dropdown list. or boolean. i am not facing any trouble. 

The only issue where i am getting is that when i am searching on the string fields. when i click on the next page ,

It gets reset to the orginal to second page.

if I use field search on string and as well as the integer . for example i have 300 records (total) on filter on two variables i am getting 100 records. and if i hit the next page   the record number changes to 200 records . that is the data is setting to the filtered data by the integer only ( not both filtered on string and data) .

I think there is an issue with the code for the field search on strings.


I am using activescaffold  active_scaffold (3.4.17)

**Comment by scambra** [comment]
field search on strings it's working here, on many controllers, what's ruby and rails versions?. Also, can you try other options for string filtering, like greater than and begins with?

**Comment by kranthi3896** [comment]
same goes with greater than and the begins with also . i am using rails 4.2 and ruby 2.1.4

**Comment by kranthi3896** [comment]
one thing i can see in the cokkies of chrome. whien i hit for the first time .. the request cookie is say 1. and the responce cookie is 2. now when i am hitting for 2nd page its request cookie is 2 and responce cookie is 1. is this any thing usefull?

**Comment by scambra** [comment]
What I understand from that is controller is changing session to state before searching. Do you have any before_filter or some code changing the session? Can you reproduce it in other controller or a sample app?

**Comment by kranthi3896** [comment]
this is happening in all the controllers.

**Comment by scambra** [comment]
Can you reproduce it in a new clean app?

**Comment by kranthi3896** [comment]
same thing happened.. do we need to make the any changes to sessions in rails initializer?

**Comment by scambra** [comment]
can you post that test app to github, so I can debug. It may be related to rails 4.2 which I only used for some testing

**Comment by kranthi3896** [comment]
I have added the test app at 

kranthi3896/app

when i search on a it works fine. and shows page no 1.

![image](https://cloud.githubusercontent.com/assets/11405911/7836289/c63cdf36-049c-11e5-8af4-77d055580219.png)


when i click on page :2 the data is gone and reset by itself to show all the records .

![image](https://cloud.githubusercontent.com/assets/11405911/7836341/1a3a2d00-049d-11e5-925f-d96161b11d41.png)

**Comment by kranthi3896** [comment]
Thanks Sergio

On Wed, May 27, 2015 at 8:22 PM, Sergio Cambra <notifications@github.com>
wrote:

> Closed #416 <https://github.com/activescaffold/active_scaffold/issues/416>
> via bb6f697
> <https://github.com/activescaffold/active_scaffold/commit/bb6f69723b8412141550dfa97a81e8a9a33e6e32>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/activescaffold/active_scaffold/issues/416#event-314976710>
> .
>



-- 

Thanks,

Kranthi Kumar,
Software Engineer,
Factset Research Systems - India,
Hyderabad.
