### ISSUE TITLE
belongs_to :owner, ->{ where dept : 'xxx' } not showing up in create and search dropdowns

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#418]
the where function is working in the showing table ui. but it is not working on create and search columns for drop down.

**Comment by scambra** [comment]
lambda from associations (or :conditions option in rails 3) never was used in select form ui. You will have to override options_for_association_conditions(association, record). If you can get lambda from association and reuse in that method it would be great to add to ActiveScaffold, although I don't know if it's possible

**Comment by kranthi3896** [comment]
I have overwritten options_for_association_condition.. It is working in the
create form but it is not working in search form ... Can you help me out

**Comment by scambra** [comment]
I don't know why, active_scaffold_search_select calls sorted_association_options_find, 
just like active_scaffold_input_select helper.

Can you check sql when search form is open?

**Comment by kranthi3896** [comment]
it is just calling 

select name * from users order by users.id

i want to include the where clause or some condition filter on it

**Comment by scambra** [comment]
I have checked code and I didn't remember how select worked on field search.

options_for_association_conditions is not used in search, because it removes associated record (when editing has_one or has_many), because options_for_association_conditions doesn't display associated records for has_one and has_many associations by default (it filters by {association.foreign_key => nil})

If you need to add some conditions to both form and search UI it's better to override association_klass_scoped(association, klass, record)

**Comment by kranthi3896** [comment]
how to  write a where condition to get only set of fileds the association_klass_scoped(association, klass, record)?

my before overide is like 

def options_for_association_conditions(association)
    if association.name == :whole
      ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
   elsif association.name == :num
      ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
    elsif association.name == :denom
      ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
    elsif association.name == :fpoint
      ['field_maps.id IN (?)', FieldMap.where(type_name:'FLOAT').ids]
    elsif association.name == :opti
      ['field_maps.id IN (?)', FieldMap.where(type_name:'OPTI_PRICE').ids]
    elsif association.name == :double
      ['field_maps.id IN (?)', FieldMap.where(type_name:'DOUBLE').ids]
    else
      super
    end
  end

**Comment by scambra** [comment]
It would be something like this:

```ruby
def association_klass_scoped(association, klass, record)
    if association.name == :whole
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
   elsif association.name == :num
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
    elsif association.name == :denom
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'INT').ids]
    elsif association.name == :fpoint
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'FLOAT').ids]
    elsif association.name == :opti
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'OPTI_PRICE').ids]
    elsif association.name == :double
      super.where ['field_maps.id IN (?)', FieldMap.where(type_name:'DOUBLE').ids]
    else
      super
    end
  end
```

association_klass_scoped must return an ActiveRecord class or relation, so you can use scopes, includes, joins there too

**Comment by kranthi3896** [comment]
Thanks
