### ISSUE TITLE
>3.4.17 bug with batch destroy 

### ISSUE THREAD

**Issue by jsurrett** [activescaffold/active_scaffold#419]
Since upgrading beyond 3.4.17, batch destroy is giving me the following error:

An ArgumentError occurred in groups#batch_destroy:

  wrong number of arguments (0 for 1)
  

2015-03-31 23:50:48.421 
[fat] ArgumentError (wrong number of arguments (0 for 1)):
  active_scaffold (3.4.19) lib/active_scaffold/actions/mark.rb:75:in `do_destroy'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_destroy.rb:52:in `destroy_record'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_destroy.rb:38:in `block in batch_destroy_marked'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  active_scaffold (3.4.19) lib/active_scaffold/actions/core.rb:143:in `each_marked_record'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_destroy.rb:37:in `batch_destroy_marked'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_base.rb:60:in `process_batch'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_base.rb:12:in `block in batch_action'
  active_scaffold (3.4.19) lib/active_scaffold/actions/core.rb:314:in `process_action_link_action'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_base.rb:11:in `batch_action'
  active_scaffold_batch (3.3.1) lib/active_scaffold/actions/batch_destroy.rb:10:in `batch_destroy'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  exception_notification (4.0.1) lib/exception_notification/rack.rb:28:in `call'
  apartment (1.0.0) lib/apartment/elevators/generic.rb:23:in `call'
  apartment (1.0.0) lib/apartment/reloader.rb:18:in `call'
  bullet (4.14.2) lib/bullet/rack.rb:12:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.0) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.0) lib/puma/server.rb:375:in `process_client'
  puma (2.11.0) lib/puma/server.rb:262:in `block in run'
  puma (2.11.0) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.0) lib/puma/thread_pool.rb:104:in `block in spawn_thread' (pid:7336)

**Comment by jsurrett** [comment]
Here is the part that is causing the error. Not sure if just changing it back causes other side affects or why it was changed.

active_scaffold (3.4.19) lib/active_scaffold/actions/mark.rb:75
    def do_destroy(record)
      super
      @record.as_marked = false if successful?
    end

active_scaffold (3.4.17) lib/active_scaffold/actions/mark.rb:75
    def do_destroy
      super
      @record.as_marked = false if successful?
    end

**Comment by jsurrett** [comment]
It appears that the fix is to change active_scaffold_batch
/lib/active_scaffold/actions/batch_destroy.rb:52
      change do_destroy to do_destroy(record)

**Comment by scambra** [comment]
Fixed on active_scaffold_batch

**Comment by scambra** [comment]
Thanks
