### ISSUE TITLE
Search Ui in active scaffolding

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#420]
Sarch = :fieldsearch

Enter search team
Click Search - Results get displayed
Click cross (on closing serch ui) - list doesn't reset but Search Field is still populated with previous search term .
Refresh page - Search Field is still populated with previous search term and list is displaying according to the search term(bug)

**Comment by scambra** [comment]
that's how it works, close doesn't reset, only close form, there is a reset button on form and a reset button on first row
