### ISSUE TITLE
not getting the data in the .xml format

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#421]
hi,

I have an app , this app contains around 20 controllers . i am getting .xml format of every thing except for one.

did this happen to any one.

the sql operation is below after i hit /nameXXXX.xml

Started GET "/feed_handlers.xml" for 127.0.0.1 at 2015-04-01 02:33:41 -0400
Processing by FeedHandlersController#index as XML
  FeedHandler Load (29.9ms)  SELECT "feed_handlers".* FROM "feed_handlers" WHERE "feed_handlers"."format" = ?  ORDER BY "feed_handlers"."id" ASC  [["format", "xml"]]
Completed 200 OK in 401ms (Views: 0.2ms | ActiveRecord: 29.9ms)

SELECT "feed_handlers".* FROM "feed_handlers" WHERE "feed_handlers"."format" = ?  ORDER BY "feed_handlers"."id" ASC  [["format", "xml"]]

there is no field called format. i dont know from where it is generated.

and i am getting <nil-classes type="array"/> as the xml

can any one hep me out?

**Comment by scambra** [comment]
I don't see any sql error so I guess feed_handlers table has format column (although you said there is no field called format). ActiveScaffold automatically filters by column if column is present on params, however it ignores some params like :controller, :action, :page, :sort, :sort_direction, :id, I think format should be ignored too.

If you want to disable this feature, you can override conditions_from_params in your controller:

```ruby
def conditions_from_params
  {}
end
