### ISSUE TITLE
Embedded scaffolds with Rails 4.2

### ISSUE THREAD

**Issue by jcrate** [activescaffold/active_scaffold#424]
My embedded scaffolds are displayed on a page where the id parameter is used, e.g. 
    /admin/events/89/manage

When using embedded scaffolds on that page like so:

    <%= render(active_scaffold: 'admin/deliveries', constraints: { event: @event.id } ) %>

the ID is picked up in the generated URL:

    /admin/deliveries/89/list?eid=9b151c71e43f80d1d026c79e02457c25&embedded=true

In lib/active_scaffold/actions/list.rb, when processing the index action, if the ID exists for xhr requests, then it processes as a row, which is great when used for redrawing a row after an update but not really what we are looking for when trying to display an embedded scaffold.

    def index
      if params[:id] && !params[:id].is_a?(Array) && request.xhr?
        row
      else
        list
      end
    end

in lib/active_scaffold/action_view_rendering.rb, if I change the url generation to drop the ID parameter, then embedded scaffolds work correctly.

          url = url_for(url_options.merge(id: nil))

I suppose I could have also checked in the list action processing if an embedded scaffold is being processed, but I guess it probably makes more sense to make sure the embedded scaffold url is being properly formed.

**Comment by scambra** [comment]
To make sure the embedded scaffold url is being properly formed, set params: {id: nil} in your embedded scaffold
