### ISSUE TITLE
XSS vulnerability in Update form

### ISSUE THREAD

**Issue by siddarthareddy** [activescaffold/active_scaffold#425]
XSS vulnerability is found when clicked on update form, as its executing javascript stored earlier, in one of the columns.
In lib/active_scaffold/extensions/localize.rb, "as_" function is using html_safe, thus causing problems, when it is used in app/views/active_scaffold_overrides/_update_form.html.erb, while rendering _base_from.html.erb, to the parameter :header.

**Comment by scambra** [comment]
I guess you mean headline partial local, I don't see any :header

For _update_form, headline is set to as_(:update_model, :model => @record.to_label), so the only way to get some javascript is there is:
1. :update_model translation has some &lt;javascript&gt; tag, added by developer, so it should be good (developer will knows why add that tag)
2. @record.to_label returns some &lt;javascript&gt; tag

**Comment by siddarthareddy** [comment]
my apologies, yes headline it is.

**Comment by siddarthareddy** [comment]
yes record.to_label returns executable, javascript to the view, when a user stores JS in it.
