### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#427]
Hi Sergio,

I am having an issue with validations where the 'Please fill out this field' appears on the upper left corner of the screen when a user presses the submit button. Not sure if this has anything to do with the fact that I am using form_ui :chosen and :text_editor as well as date_picker.

The interface works beautifully...it is just the validations are active they mess everything up. Here is what the controller looks like:

class Admin::ReportsController  < Admin::Auth # ApplicationController
 
  active_scaffold :"report" do |config|
    config.columns = [:title,  :summary, :recommended, :source, :categories, 
      :actual_post_date, :drc_companies, :attachments] 
 
    config.list.per_page    = 25 
    config.create.multipart = 'local' 
    config.update.multipart = 'local' 
    
    config.list.sorting = { :actual_post_date => :desc }

    config.columns[:actual_post_date].label   = 'Publication Date' 
    config.columns[:actual_post_date].form_ui = :date_picker
    config.columns[:actual_post_date].options = {options: [[changeYear: true]]}
    
    config.columns[:source].form_ui         = :chosen
    config.columns[:categories].form_ui     = :chosen
    config.columns[:drc_companies].form_ui  = :chosen
    
    config.columns[:summary].form_ui = :text_editor

    #config.columns[:title].length = '60'
    #config.columns[:title].css_class = ' long-title-input'
    
    config.actions.add :export
    config.export.force_quotes = "true"
    config.export.force_quotes = "true"
    
  end
end

and the model:

  validates_presence_of :title, :summary
  #validates :source, presence: true

i am attaching an image
![screenshot from 2015-05-21 14 42 24](https://cloud.githubusercontent.com/assets/39400/7756371/c3579816-ffc8-11e4-9c1a-c7641633230c.png)

Thanks in advance
mark

**Comment by markmcdonald51** [comment]
Sorry that image doesn't show the problem... this one does. Look at the upper left corner.

![screenshot from 2015-05-21 20 51 42](https://cloud.githubusercontent.com/assets/39400/7761977/59d648d2-fffb-11e4-97bf-d52675757837.png)

**Comment by scambra** [comment]
If you use select instead of chosen, does it fix the validation issue?

**Comment by markmcdonald51** [comment]
nevermind... it was because I was using a belongs_to :source and was trying to do a validates_presence_of :source    --instead of :source_id  which now works. Thanks Sergie.
