### ISSUE TITLE
optgroup with :chosen form_ui

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#428]
Hi!

Not sure if this is the best place to post this but I am really trying to figure out how to use the optgroup feature of the 'chosen' form_ui. I need to use it with an acts_as_tree list (for categories) and I cant seem to get it to work. I noticed this piece of code in the chosen class but I am not sure how I can pass any options to it. 
  
if (optgroup = options.delete(:optgroup))

Any help would be super helpful. Thanks so much for the great work on this wonderful module!
Mark

**Comment by scambra** [comment]
Best place for help is google group. Issues on github is pretended for bugs and feature requests
