### ISSUE TITLE
polymorphic issue

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#430]
Hi Sergio,

I have a model that has several polymorphic associations attached that are all the same model (DepositResource). In rails this works just fine and dandy but active scaffold seems to have some trouble with I add it into the add/modify form as it is not recording the deposit type (which is basically handled by rails). When I add it in as a drop down association it adds this field. 

  has_many :proven_reserves, -> { where deposit_type:  DepositResource::PROVEN_RESERVES },
   as: :depoable, dependent: :destroy, class_name: 'DepositResource'

  has_many :probable_reserves, -> { where deposit_type: DepositResource::PROBABLE_RESERVES },
    as: :depoable, dependent: :destroy, class_name: 'DepositResource'

It will also work if I allow the fields to be displayed in the form. Is this something that you have experienced before?

The first image show it with the fields  deposit_type with are being entered in correctly automatically.

The second image show what I would like to do, but AS is not adding deposit_type in. 

The third show when I add the association from which AS works inserts all data correctly. Not sure why or if this is a bug or not but I was wondering if you had see this before. Thanks in advance!
-Mark

![screenshot from 2015-06-02 21 55 58](https://cloud.githubusercontent.com/assets/39400/7951300/ebcaf77a-0973-11e5-899d-66d46bf90616.png)
![screenshot from 2015-06-02 22 00 55](https://cloud.githubusercontent.com/assets/39400/7951302/f00680ac-0973-11e5-91f6-05d82956ee93.png)
![screenshot from 2015-06-02 22 09 47](https://cloud.githubusercontent.com/assets/39400/7951325/1c988cbe-0974-11e5-8c12-9e45506a5b78.png)

**Comment by scambra** [comment]
You could try setting form_ui = :hidden for depoable_type and deposit_type

**Comment by markmcdonald51** [comment]
Hi Sergio,

So the hidden field does fix the horizontal problem but gives rise to another when the form is submitted: it inserts all extra rows not filled in (the ones meant to be used conveniently for adding in another of it's respected assoc). So no I would end up with too many blank rows and more and more as it gets submitted again. I could do a before filter in the cntr but that is pretty awkward. Hmmm...thinking!

![screenshot from 2015-06-03 06 19 34](https://cloud.githubusercontent.com/assets/39400/7957882/9dce7a34-09b8-11e5-98e1-1b95826f9fda.png)

**Comment by scambra** [comment]
I don't know if it's a bug in AS, or it's not possible to get it working without custom code.

You could override in your controller attributes_hash_is_empty?(hash, klass), so it ignores those columns, or even easier, override column_default_value(column_name, klass, column):

```ruby
def attributes_hash_is_empty?(hash, klass)
  if klass == DepositResource
    super(hash.exclude(:depoable_type, :deposit_type), klass)
  else
    super
  end
end
```

**Comment by markmcdonald51** [comment]
Thanks Sergio! That totally worked. So cool. 

  def attributes_hash_is_empty?(hash, klass)
    if klass == DepositResource      
      super(hash.except(:deposit_type), klass)
    else
      super
    end
  end 

That is definitely the way you have to do a mutiple has_many polymorphic attributes. This saves so much time/ code/ headaches and compile cycles..

You make this project great Sergio!
Going to buy you several pints at the cervecería whenever I get to Spain!

Cheers Brother.
Mark

**Comment by scambra** [comment]
It's good to read that
