### ISSUE TITLE
$(".chosen").chosen()

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#431]
Hi All,
When you use :chosen as the form_ui it works wonderfully, only that when you add a new association it will default back to the old form_ui, eg. multi select etc... 

it appears what needs to happen is this needs to be called again:

$(".chosen").chosen();

which then renders it back to the correct form_ui

Is there a way to make this work in the controller or is this something that has to be fixed at the core in the bridge?

Thanks to all!
Mark

**Comment by scambra** [comment]
What do you mean with "add a new association"? Could you post an example?

**Comment by markmcdonald51** [comment]
Hi Sergio,
Sorry, I should have been more clear. It is when you have a has_many assoc and you want to add in another. When one does this it drops down the default style form_ui, which is a select and a multi_select. If I add '$(".chosen").chosen();' into the console it immeadiately changes to the :chosen form_ui..

![screenshot from 2015-06-12 08 26 47](https://cloud.githubusercontent.com/assets/39400/8130016/20be034e-10dd-11e5-8574-339917e539f0.png)

![screenshot from 2015-06-12 08 30 12](https://cloud.githubusercontent.com/assets/39400/8130027/47b70a18-10dd-11e5-9de1-5c37c6d3d5ec.png)
