### ISSUE TITLE
Is there a way to trim the leading and trailing spaces for all the input before storing in the database

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#436]
I want to have all the string data types of my app should not have leading and trailing spaces . I need to have validations which throws error, i dont want to do that too... 

I want leading and the trailing spaces for all string data types to be trimmed , before I save it in to database.

so, is there any easy method to do this for total app?

**Comment by scambra** [comment]
You can add before_validation or before_save callbacks on your models for this.

Also, if you want to do it in controller, you can override in your controller column_value_from_param_value:

```ruby
def column_value_from_param_value(*)
  v = super
  v.strip! if v.is_a? String
  v
end
```

**Comment by kranthi3896** [comment]
thanks a lot
