### ISSUE TITLE
Is there a way to filter the respond json from the url.

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#437]
It is very good that we have 
.json will get the all the records .
.json?somecondition .... will give records that satisfy the conditions

so like '?' does we have any other , so that i can get only certain columns of the database .

if not how can i achieve that . I dont want to use function list_respond_to_js as I want the default foramt . if I overide that I will lose that

**Comment by scambra** [comment]
No way built-in, but you can add a parameter (e.g. columns) and use list_respond_to_js to change columns if a params[:columns] is set, then call super.

**Comment by kranthi3896** [comment]
can you give the example of url ?

for conditions it is ?
so I am thinking how we can pass the params

**Comment by scambra** [comment]
.json?somecondition&columns[]=a&columns[]=b
