### ISSUE TITLE
compatibility with gem composite_primary_keys

### ISSUE THREAD

**Issue by bencarsal** [activescaffold/active_scaffold#442]
With this gem is generated this error:
- ActionView::Template::Error (undefined method `to_sym' for [:field1, :field2, ...]:Array):
And i repair the error just doing this in the file:
lib/active_scaffold/extensions/reverse_associations.rb
line 69, present this sentence:
- next unless assoc.foreign_key.to_sym == foreign_key.to_sym
please replace for this line:
- next unless assoc.foreign_key == foreign_key
And is all. Thanks in advanced

**Comment by scambra** [comment]
It's not so easy. By default foreign_key are strings, but if you set foreign_key in your associations, symbol is used most of time.

For example:
```ruby
class PdfTemplate < ActiveRecord::Base
  has_many :styles, :foreign_key => :template_id
end

class Style < ActiveRecord::Base
  belongs_to :template, :class_name => 'PdfTemplate'
end
```

foreign_key for template association is "template_id", foreign_key for PdfTemplate association is :template_id, so assoc.foreign_key == foreign_key would fail. Maybe convert to string to check would work, or convert only if it's symbol

**Comment by bencarsal** [comment]
And with this in same line 69 of reverse_associations.rb?:
replace this:
           next unless assoc.foreign_key.to_sym == foreign_key.to_sym
with this:
              if assoc.foreign_key.class == Array
                next unless assoc.foreign_key == foreign_key
              else
                next unless assoc.foreign_key.to_sym == foreign_key.to_sym
              end
