### ISSUE TITLE
Input type file for image column

### ISSUE THREAD

**Issue by sebastianvirlan** [activescaffold/active_scaffold#445]
FOr form_ui v1.1 https://github.com/activescaffold/active_scaffold/wiki/API:-Column I cant see the input type file form interface. Can this be implemented?

**Comment by scambra** [comment]
It depends on other gems, like paperclip, dragonfly, carrierwave
You can see there is a :paperclip form_ui, and there is others like :dragonfly although is not documented there. Check [Integration with other plugins](https://github.com/activescaffold/active_scaffold/wiki/Integration)
