### ISSUE TITLE
RJS error:

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#446]
Hi,

Just installed a rails fresh setup and active_scaffold works really well with the exception of an rjs error that pops up as an alert window:

RJS error:

TypeError: element.visible is not a function

I am guessing this function was removed somewhere in he base js code? Thanks in advance.

Mark

**Comment by markmcdonald51** [comment]
my bad.... forgot to do a bundle update;)

**Comment by rosensama** [comment]
I'm getting the same error and bundle update didn't resolve it.   Any time I create a new object in active_scaffold, when it returns from models/new, I get that error and must manually refresh the page to see all results.   

From Gemfile.lock:
```
GIT
  remote: git://github.com/activescaffold/active_scaffold.git
  revision: b04a74f8e6d096c6c93a35198546e7a0b4c9d046
  specs:
    active_scaffold (3.4.29)
      rails (>= 3.2.18, < 5)

GEM
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
```
