### ISSUE TITLE
"Create new" inline with list produces RJS error:  TypeError: element.visible is not a function

### ISSUE THREAD

**Issue by rosensama** [activescaffold/active_scaffold#447]
Reopening closed issue #446.  
```
RJS error:

TypeError: element.visible is not a function
```

I'm getting the same error and bundle update didn't resolve it.   Any time I create a new object inline in the objects list (e.g,. http://localhost:3000/products) by clicking the "Create New" button, I get that error and must manually refresh the page to see all results.   If I create it from the new object view (e.g., http://localhost:3000/products/new) it behaves as expected and there is no error.

From Gemfile.lock:
```
GIT
  remote: git://github.com/activescaffold/active_scaffold.git
  revision: b04a74f8e6d096c6c93a35198546e7a0b4c9d046
  specs:
    active_scaffold (3.4.29)
      rails (>= 3.2.18, < 5)

GEM
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
```

**Comment by scambra** [comment]
I see issue, .visible is added by jquery.visible, which is loaded by recordselect, which most people, including me, use with activescaffold

I will load that file with activescaffold
