### ISSUE TITLE
country form_ui doesn't work on rails 3.2.13 and above

### ISSUE THREAD

**Issue by naaano** [activescaffold/active_scaffold#450]
ActionView::Helpers::InstanceTag got deprecated and removed since 3.2.14
:country form_ui uses this in /lib/active_scaffold/bridges/country_helper/country_helper_bridge.rb

**Comment by scambra** [comment]
ActionView::Helpers::InstanceTag was removed but ActionView::Helpers::Tags::Base added, which is used in newer versions. Maybe you have an outdated version. Anyway, there is a bug, at least with 3.2.22, and probably with 4.x

**Comment by scambra** [comment]
I was wrong, 3.2.22 still uses ActionView::Helpers::InstanceTag, and class is there in 3-2-stable rails branch. But 4th parameter is not an options hash
