### ISSUE TITLE
Not able to select multiple options in rails

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#454]
Hi,
I am trying for multiselect in rails without having any associations.

Here is how my model looks like:

class PackageGroup < ActiveRecord::Base
   GROUPS =["a", "b", "c", "d"]
end

Here is how my controller looks like:

class PackageGroupsController < ApplicationController
  active_scaffold :package_group do |config|
    config.columns = [:package, :groups]

    [:groups].each do |assoc|
      config.columns[assoc].form_ui = :radio
    end
    config.columns[:groups].options = {:multiple => true, :options => PackageGroup::GROUPS}
  end
end

Here I am able to select only one option. I want to select multiple options.
I added ":multiple => true" to get multiselect feature, but it seems to be playing no role and I don't find any difference by adding it.

Please suggest me how to proceed.

**Comment by scambra** [comment]
Try with select instead of radio. I don't think multi select would be possible with radio buttons, certainly not possible with activescaffold.

**Comment by mounika36** [comment]
When I use select, a dropdown is created and we are not able to select multiple options with it.

**Comment by scambra** [comment]
You are right, select will gives you a dropdown, but with multiple, you must be able to select multiple options if you press ctrl key (command on mac) while clicking, or select a range pressing shift while clicking.

However, I have checked and you need to use :html_options => {:mutiple => true}, and I found a bug, where multiple options could be selected but only one would be sent to server.

Also, you could use checkboxes for it, like plural associations do, but no form_ui available, you will have to use helper which calls active_scaffold_checkbox_list(column, select_options, associated_ids, options), such as:

```ruby
def groups_form_column(record, options)
  column = active_scaffold_config.columns[:groups]
  select_options = active_scaffold_enum_options(column, record).collect do |text, value|
    active_scaffold_translated_option(column, text, value)
  end
  active_scaffold_checkbox_list(column, select_options, record.groups, options)
end

**Comment by mounika36** [comment]
Hi scambra - tried the same, but got some error.

ActionView::Template::Error (undefined method `id' for ["Ds", "Ds"]:Array):
    24:     <%= render_column(column, @record, renders_as, scope) %>
    25:   <% end %>
    26:   <% else -%>
    27:   <li class="form-element <%= 'required' if column.required? %> <%= column.form_ui %> <%= column_css_class %>">
    28:     <%= render_column(column, @record, renders_as, scope, !authorized) %>
    29:   </li>
    30:   <% end -%>
  app/helpers/package_groups_helper.rb:7:in `groups_form_column'

and my helper is:

module PackageGroupsHelper
def groups_form_column(record, options)
  column = active_scaffold_config.columns[:groups]
  select_options = active_scaffold_enum_options(column, record).collect do |text, value|
    active_scaffold_translated_option(column, text, value)
  end
  active_scaffold_checkbox_list(column, select_options, record.groups, options)
end
end

Where did I go wrong?

**Comment by scambra** [comment]
what active scaffold version? can you remove backtrace silencers to get a trace which include activescaffold lines?

**Comment by scambra** [comment]
stale, and not a bug, but usage question, so closing
