### ISSUE TITLE
Helper to provide options for a dropdown

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#460]
Hi

I want to create a dropdown in search form for a particular column with the contents of that column as options.
How to define a helper method for it?

Thanks.

**Comment by scambra** [comment]
Better to send support questions to https://groups.google.com/forum/#/activescaffold

Anyway, you can set search_ui = :select, and set options if they are always the same, or override active_scaffold_enum_options if they are dynamic

**Comment by mounika36** [comment]
Done using search override. #{class_name}_#{column_name}_search_column

def  #{class_name}_#{column_name}_search_column(record, column)
    select :record, #{column_name}, options_for_select( #{class_name}.select(#{column_name}).distinct ), {:include_blank => as_('- select -')}, column
  end

Thanks.
