### ISSUE TITLE
list method breaks with active scaffold 3.4.20 to 3.4.31 for some reason

### ISSUE THREAD

**Issue by pbharadiya** [activescaffold/active_scaffold#461]
Hi,

I am unable to use active scaffold list column with active scaffold 3.4.20 to 3.4.31.
Please find below line where error is coming--

```<p id="<%= empty_message_id %>" class="empty-message" <%= ' style="display:none;" '.html_safe unless @page.empty? %>>```

file: **active_scaffold (3.4.31) app/views/active_scaffold_overrides/_list_messages.html.erb:23**

When I use active scaffold 3.3.3, it works fine, but I want to upgrade active scaffold for other stuff.
My configs are as below:
Ruby 1.9.3,
Rails 3.2.18,
Active scaffold 3.4.31

P.S I have noticed one thing. It breaks only for list method. So for example I do /admin/user/list, it breaks, but If I do /admin/user/all and then define all method like below, then it works fine!

<pre><code>def all
  list
end</code></pre>

Let me know if you need more information from my side.

Thanks.
parth.

**Comment by scambra** [comment]
I don't understand, what's the error?

Also, there is no list action, is index now (/admin/user)

**Comment by pbharadiya** [comment]
Sorry for being late here.

Actually the problem is, when I use list, I get the error.
<pre>undefined method `empty?' for nil:NilClass</pre>
at the location that I mentioned above.

this is my config.
<pre>config.actions = [:list, :search, :update, :delete]</pre>

This was working for earlier version of active scaffold(3.3.3)

I also tried using <pre>config.actions = [:index, :search, :update, :delete]</pre> as you told, but then I got error as <code>List is not enabled. Please enable it or remove any references in your configuration (e.g. config.list.columns = [...]).</code>
 I removed these two lines even if I actually want them. <code>list.sorting = {:id => 'DESC'}
      config.list.per_page = 15</code>

Then I got this error <code>undefined method `index' for #<ActiveScaffold::Config::Core:0x007fe9b3b4f1f0></code>

Please let me know where I am doing wrong.

P.S All I want is - to list down all the records with some conditions that I have put in <code>conditions_for_collections</code>

**Comment by scambra** [comment]
When I said there is no list action, I meant no route /list, so action is named :list on active_scaffold (for config.actions), but action method is named index (list is a protected method), and route is only /controller which goes to index action.

**Comment by scambra** [comment]
So you should try /admin/user, no /admin/user/list

**Comment by pbharadiya** [comment]
I see but still when I try /admin/user, it gives me same error.
<pre>undefined method `empty?' for nil:NilClass</pre>
at here.
```<p id="<%= empty_message_id %>" class="empty-message" <%= ' style="display:none;" '.html_safe unless @page.empty? %>>```
file: *active_scaffold (3.4.31) app/views/active_scaffold_overrides/_list_messages.html.erb:23*

And the weird thing is that, with the same configuration, it was working fine for earlier version (3.3.3)

**Comment by scambra** [comment]
Can you post your controller? Maybe you have some code which is overriding some activescaffold method, because @page shouldn't be nil

**Comment by pbharadiya** [comment]
Here is my controller.
<pre>class UserController < AdminController

    active_scaffold :user do |config|
      config.actions = [:list, :search, :update, :delete]
      config.columns = [:name, :email, :phone_number, :role, :kind, :status, :created_on, :last_active_on]
      config.search.columns = [:id, :first_name, :last_name]

      # Override default label name with user defined
      config.columns[:phone_number].label = 'Phone'
      config.columns[:created_on].label = 'Created'
      config.columns[:last_active_on].label = 'Last active'

      # Hide default 'edit' link
      config.update.link = false

      # Inplace Edit
      config.columns[:role].inplace_edit = true
      config.columns[:role].form_ui = :select
      config.columns[:role].options = {:options => [:customer, :worker, :customer_worker]}

      config.columns[:kind].inplace_edit = true
      config.columns[:kind].form_ui = :select
      config.columns[:kind].options = {:options => [:normal, :anonymous, :test, :grader, :admin, :student, :faculty, :staff]}
      config.columns[:status].set_link('update_user_status')


      list.sorting = {:id => 'DESC'}
      config.list.per_page = 15
    end
    
    def conditions_for_collection
       User.merge_conditions(@conditions)
    end
end</pre>

**Comment by scambra** [comment]
That doesn't make sense to me, @conditions would be nil

Also, I don't see anything which prevents AS to set @page

Can you check logs in development and see if there is some select for users table?

**Comment by pbharadiya** [comment]
@conditions won't affect. Even if I remove `conditions_for_collection`, It doesn't work.
And as soon as I change active_scaffold version to 3.3.3, it works perfectly with the same config.

Also I checked log. It gives me only this much information about ```ActionView::Template::Error (undefined method `empty?' for nil:NilClass): NoMethodError - undefined method `empty?' for nil:NilClass:  active_scaffold (3.4.31) app/views/active_scaffold_overrides/_list_messages.html.erb:23```

Is there anything that has changed from v3.3 to v3.4 related to list method? How should I proceed to work this now?

**Comment by pbharadiya** [comment]
There is one more thing to notice here.

When I add e.g 'all' action link to controller and I define it as
<pre>def all
  list
end
</pre>
and visit /admin/user/all, then that works fine!

**Comment by scambra** [comment]
Yes, list action is removed as action method, there is a index action which calls list. I don't remember if something else. Anyway, in log you should see some SQL queries, if you don't see them, something in your application is preventing ActiveScaffold index method, or overriding it.

**Comment by chavanrajsandhya** [comment]
Hi Parth Bharadiya, im sandhya working as a ROR developer, may i know how u solve this issue, i'm also getting same issue here can't able to solve.

**Comment by pbharadiya** [comment]
@chavanrajsandhya Sure. Can you please elaborate what issue you're facing?

**Comment by frisino** [comment]
@pbharadiya did you resolve the issue with @page not being set. I am trying the master branch against Rails 5.1.4 and I am seeing the same behavior that you reported in in this thread. Which is strange b/c there is a comment from another developer saying he is using this gem with rails 5 and not having a problem.
