### ISSUE TITLE
Bug in find_if_allowed

### ISSUE THREAD

**Issue by darenas1144151** [activescaffold/active_scaffold#466]
hi, I have a strange problem with find_if_allowed method, when try to test the method update_column, i got an error in my model "ActiveRecord::RecordNotFound: Couldn't find Reservation with 'id'=1 [WHERE (1=0)]" the reservation with the id 1 already exist but I Dont Know understand why add "[WHERE (1=0)]" what is this??, this failed in this line 

https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/finder.rb#L331 

Thank for any help.

**Comment by scambra** [comment]
Do you have conditions_for_collection in your controller?
Also, post the request log, with request parameters and sql queries

**Comment by scambra** [comment]
Or do you have beginning_of_chain overrided?

**Comment by darenas1144151** [comment]
only have conditions_for_collection in controller

```
    def conditions_for_collection
       account_id = session[:account]
       return ['account_id = ? and event_id = ?', account_id, session[:checkin_event_id]]
    end
```

but when try make test to method update_column get the error

```
  def test_check_in_reservation
    event = Factory(:event, :venues => @venues)
    reservation = Factory(:reservation, :staff => @staff, :event => event)

    @request.accept = "text/javascript"
    post :update_column, {
      :username => @user.username,
      :password => 'password',
      :column => 'checked_in',
      :original_html => reservation.checked_in,
      :original_value => reservation.checked_in,
      :id => reservation.id,
      :value => 'true'
    }

    assert_response :success
  end
```

**Comment by scambra** [comment]
sorry, conditions for collection shouldn't be used there, only beginning of chain, is it not overrided on your controller?

**Comment by darenas1144151** [comment]
I dont override beginning_of_chain method :(, what else can be?

**Comment by darenas1144151** [comment]
this issue can be close, the issue is no of active_scaffold is of cancan gem that add the condition 1 = 0 to the query
