### ISSUE TITLE
Deleting the association column

### ISSUE THREAD

**Issue by kranthi3896** [activescaffold/active_scaffold#467]
if I had has_one and belongs_to relationship between tables.

when I delete the associated object . the link is gone , but the id was still stored in the associated table.

when I try to get the data from backend i am getting the associated id , where the associated object is no more available.

i think it is better to make the assocaited_id also nil

**Comment by scambra** [comment]
That's unrelated to ActiveScaffold, it's rails question. If you want to unset foreign key, set :dependent => :nullify on your association definition
