### ISSUE TITLE
I am installing Chef 12 server on x86 machine but using a http_proxy server   ... keep getting these errors

### ISSUE THREAD

**Issue by randyab** [activescaffold/active_scaffold#470]
[root@ ~]# rpm -qa | grep chef
chef-server-core-12.3.1-1.el7.x86_64
[root@ ~]#

[root@ ~]# uname -a
Linux zsb3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Aug 25 11:21:22 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@ ~]#

[root@~]# env | grep http
http_proxy=http://10.20.80.216:3128
ftp_proxy=http://10.20.80.216:3128
rsync_proxy=http://10.20.80.216:3128
HTTPS_PROXY=http://10.20.80.216:3128
https_proxy=http://10.20.80.216:3128
HTTP_PROXY=http://10.20.80.216:3128
[root@ ~]# chef-server-ctl install opscode-manage
Starting Chef Client, version 12.5.1
resolving cookbooks for run list: ["private-chef::add_ons_wrapper"]
Synchronizing Cookbooks:
  - enterprise (0.5.1)
  - apt (2.7.0)
  - yum (3.6.1)
  - openssl (4.4.0)
  - runit (1.6.0)
  - chef-sugar (3.1.1)
  - packagecloud (0.0.18)
  - private-chef (0.1.0)
Compiling Cookbooks...
Converging 3 resources
Recipe: private-chef::add_ons_wrapper
  * ruby_block[addon_install_notification_opscode-manage] action nothing (skipped due to ac                                                                                      tion :nothing)
Recipe: private-chef::add_ons_repository
  * yum_repository[chef-stable] action create
    * template[/etc/yum.repos.d/chef-stable.repo] action create (up to date)
    * execute[yum clean chef-stable] action nothing (skipped due to action :nothing)
    * execute[yum-makecache-chef-stable] action nothing (skipped due to action :nothing)
    * ruby_block[yum-cache-reload-chef-stable] action nothing (skipped due to action :nothi                                                                                      ng)
     (up to date)
Recipe: private-chef::add_ons_remote
  * yum_package[opscode-manage] action installKilled
[root@zgpfssb3 ~]#

    ================================================================================
    Error executing action `install` on resource 'yum_package[opscode-manage]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `>' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/add_ons_remot                                                                                      e.rb

     16:   package pkg do
     17:     notifies :create, "ruby_block[addon_install_notification_#{pkg}]", :immediate
     18:     case node['platform_family']
     19:     when 'rhel'
     20:       options "--enablerepo=chef-stable"
     21:     end
     22:   end

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/add_                                                                                      ons_remote.rb:16:in `block in from_file'

    yum_package("opscode-manage") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      options "--enablerepo=chef-stable"
      package_name "opscode-manage"
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name "private-chef"
      recipe_name "add_ons_remote"
    end

Running handlers:
  - #<Class:0x0000000702a150>::AddonInstallHandler
Running handlers complete
Chef Client failed. 0 resources updated in 13 seconds
[2016-01-14T23:38:47-05:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cac                                                                                      he/chef-stacktrace.out
[2016-01-14T23:38:47-05:00] FATAL: NoMethodError: yum_package[opscode-manage] (private-chef                                                                                      ::add_ons_remote line 16) had an error: NoMethodError: undefined method `>' for nil:NilClas                                                                                      s

[root@ ~]#

view /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Generated at 2016-01-14 23:38:47 -0500
NoMethodError: yum_package[opscode-manage] (private-chef::add_ons_remote line 16) had an error: NoMethodError: undefined method `>' for nil:NilClass
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1075:in `yum_command'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1258:in `install_remote_package'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1269:in `install_package'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:91:in `block (2 levels) in action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:217:in `multipackage_api_adapter'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:90:in `block in action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:89:in `action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:589:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:658:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:692:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:271:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:229:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:386:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'

**Comment by scambra** [comment]
what relation with activescaffold?
