### ISSUE TITLE
JSON-based cookie serializer breaks storing search params in session

### ISSUE THREAD

**Issue by courtland** [activescaffold/active_scaffold#472]
Under rails 4.2.x, when using:
```
Rails.application.config.action_dispatch.cookies_serializer = :json # or :hybrid
```
Active scaffold stores field_search parameters in the session. After performing a field_search, the last-used parameters are missing from the UI the next time. If I change the cookies_serializer back to the old :marshal format it works correctly.

Is there a way to make this work with the JSON serializer, or are we stuck with using Marshal? It seems like it should work as is with JSON, since the JSON serializer should support storing the Hash that active_scaffold stores.

In my sessions I show:
```
:"as:merchant_transactions"	{"search"=>{"created_at"=>{"opt"=>"PAST", "number"=>"3", "unit"=>"MONTHS"}}}
```
It appears this is not read-back correctly when the field_search UI is loaded.

**Comment by scambra** [comment]
To work with json, strings must be used on hashes stored on session. I had to change some symbol keys to get them working with rails 4.2, probably some symbols are still used

**Comment by courtland** [comment]
OK. Do you suggest I use marshal serializer, or do you think active_scaffold can be fixed?

**Comment by scambra** [comment]
It should be possible to fix

**Comment by courtland** [comment]
It is fixed now. Thanks a lot. I tried to find where it was breaking down but didn't have any luck.
