### ISSUE TITLE
Nested add_link doc needs change or further explanation

### ISSUE THREAD

**Issue by Grondhammar** [activescaffold/active_scaffold#473]
The [nested add_link documentation](https://github.com/activescaffold/active_scaffold/wiki/API:-Nested#add_link-local) has this as an example:

```rb
# app/models/company.rb
class Company < ActiveRecord::Base
   has_many :contacts
end

# app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company
end

# app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  active_scaffold :contacts do | config |
  end
end

# app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  active_scaffold :companies do |config|
    config.nested.add_link(:contacts)
  end
end
```

The use of the plural symbol forms `:contacts` and `:companies` in the controllers caused the error, "uninitialized constant Companies" when I was trying it out.  I (finally, after hours of wondering what I was doing wrong) changed these forms to their singular and everything worked fine.

The plural forms may somehow work for experts, but it makes us newbies who have only seen singular forms in the getting started docs question our entire approach to AS, and spend hours looking for answers and trying to make it work.

I'd like to suggest these be changed to their singular form to get them in line with other documentation in the wiki.

**Comment by scambra** [comment]
Probably it worked some time ago, and broken later, I never use plurals in active_scaffold call. Changing doc.

**Comment by scambra** [comment]
Thanks
