### ISSUE TITLE
rails5?

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#480]
Hey Sergio.

Just wanted to see what results I would get if I added the rails5 gem into my app that makes use of AS for the admin. It looks like it has problems with the as_routes in the routes file for starters. 

Looking forward to some of the new features of rails 5 and maybe even add some stuff into AS as a result.

Cheers,
Mark

**Comment by scambra** [comment]
some rails5 related changes were done on next branch, you can try it

**Comment by markmcdonald51** [comment]
Thanks Sergio!
