### ISSUE TITLE
ajax/inline forms and turbolinks 

### ISSUE THREAD

**Issue by naaano** [activescaffold/active_scaffold#484]
Active scaffold inline forms won't work with turbo links. 
I've been digging, the problem seems that AS need some JS to be run on every page load. 

So, with turbolinks we can trigger this events:
page:load
page:fetch
page:change

But do you know what AS method should be triggered?

**Comment by scambra** [comment]
What I have test it works if you add [jquery.turbolinks gem](https://github.com/kossnocorp/jquery.turbolinks) and add //= require jquery.turbolinks before jquery_ujs

**Comment by naaano** [comment]
That worked! Thanks
