### ISSUE TITLE
= render :active_scaffold 

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#489]
This seems strange...but I think I have seen this before.

I have an activescaffold page that I have many associations with and I am linking to a modal window to perform some function that I want to call a separate  embeded AS with.

The interesting thing is when I call the scaffold it doesnt return any data. I bound this in the pry debugger and called it and indeed it's not returning data as i would expected.

It just calls it then doesnt return anything. I fished around on the AS google groups as saw that a few others has come across this as well without resolve.

I am attaching a few photos to help in understanding this problem. I think this happened to before but I wasn't able to figure out what the problem was. It is returning the scaffold without the data/tables.

Any help is very welcome! 

Thanks in advance,
Mark
![screenshot from 2016-03-28 12 53 23](https://cloud.githubusercontent.com/assets/39400/14083779/6ff47578-f4e5-11e5-9cef-277ae7039660.png)
![screenshot from 2016-03-28 12 52 39](https://cloud.githubusercontent.com/assets/39400/14083777/6ff3cac4-f4e5-11e5-85a1-2ad8eb113142.png)
![screenshot from 2016-03-28 12 50 51](https://cloud.githubusercontent.com/assets/39400/14083778/6ff44170-f4e5-11e5-81ae-fdcea44d08e7.png)

**Comment by scambra** [comment]
I think it's rendering a div with active-scaffold-component class, with a link to embedded scaffold inside, that's what render :active_scaffold does, unless you are using render_component gem. Render component was removed from rails and recommended to use ajax requests, which activescaffold does when render_component is not available.

I guess when you are rendering inside modal box $(document).ready event is not called, because is not an iframe. It must exist an event for modal box loaded, you must add listener and call ActiveScaffold.load_embedded(modal_box)

**Comment by markmcdonald51** [comment]
Sergio- You ARE the Master! 

Thanks so much for this. I just added that into  new_tab.js.erb 

```
$('ul.nav.nav-tabs').append('<li><a href="#scaffold_<%=@tab_id%>"><%=@udt.name %></a><span>x</span></li>');
$('.tab-content').append("<%= j render('render_active_scaffold_tab', tab_id: @tab_id, udt: @udt) %>");
ActiveScaffold.load_embedded("#scaffold_<%=@tab_id%>");
$('.nav-tabs a[href="#scaffold_<%=@tab_id%>"]').tab('show');
![screenshot from 2016-03-29 06-39-07](https://cloud.githubusercontent.com/assets/39400/14105532/2c1388c2-f57a-11e5-9c1f-d2a9509d1b48.png)

```


and bingo! I decided to use bootstrap tabs for this part as there is going to be many of them and they will be searching between them. 

The last thing (i think) I need to do to get this thing really working well with  the column 'configuration' from gem 'active_scaffold_config_list'. It works for one time then it looses all the columns. I am going to work on that this morning and then on to a bunch of other meta~modeling issues...but thanks so much for the tip and this project.
