### ISSUE TITLE
partial => 'list_record', :locals => {:record => @record}

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#499]
Hi Sergio,

I am trying to do a custom update via a data-remote in AS which for the most part work correctly. The problem is when I call my own partial after the update it get's the action links all gummed up!

My js.erb partial looks like:

 ActiveScaffold.update_row('<%=element_row_id(:action => 'list', :id => @record.id)%>','<%=escape_javascript(render(:partial => 'list_record', :locals => {:record => @record}))%>');
$('#modal_div').modal('hide');

which appears to work but when I try to edit it again the links are tryng to pass what looks to be the entire record in the http link which originally looks like: http://localhost:3000/org/org1/intramural_study_oversight_and_statuses1s/49/edit_udt?eid=e25bb68536b7e249ac86d8a097e96b9e

But after the update and subsequent call to escape_javascript(render(:partial => 'list_record', :locals => {:record => @record}))%>  it create a like with too much text to submit! In fact I get the error:

[2016-04-18 12:21:30] INFO  WEBrick 1.3.1
[2016-04-18 12:21:30] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
[2016-04-18 12:21:30] INFO  WEBrick::HTTPServer#start: pid=9617 port=3000
[2016-04-18 12:21:33] ERROR WEBrick::HTTPStatus::RequestURITooLarge
[2016-04-18 12:21:33] ERROR TypeError: can't convert nil into an exact number
[2016-04-18 12:21:30] INFO  WEBrick 1.3.1
[2016-04-18 12:21:30] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
[2016-04-18 12:21:30] INFO  WEBrick::HTTPServer#start: pid=9617 port=3000
[2016-04-18 12:21:33] ERROR WEBrick::HTTPStatus::RequestURITooLarge
[2016-04-18 12:21:33] ERROR TypeError: can't convert nil into an exact number

So I must be calling this method incorrectly? Below is the pry debugger dump of the result from 'render(:partial => 'list_record', :locals => {:record => @record}.

Any help is super appreciated! Cheers to all!

[6] pry(#<#<Class:0x007fcb5c269880>>)> element_row_id(:action => 'list', :id => @record.id)=> "as_e25bb68536b7e249ac86d8a097e96b9e-list-45-row"
[7] pry(#<#<Class:0x007fcb5c269880>>)> escape_javascript(render(:partial => 'list_record', :locals => {:record => @record})

[7] pry(#<#<Class:0x007fcb5c269880>>)* )  
  Rendered /home/mark/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.35/app/views/active_scaffold_overrides/_list_record.html.erb (5.1ms)
=> "<tr class=\\\"record even-record \\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-list-45-row\\\" data-refresh=\\\"45\\\">\\n\\n    <td class=\\\"pi_name-column  \\\">\\n      Alevizos, Ilias\\n<\\/td>\\n    <td class=\\\"title-column  \\\">\\n      Salivary Evaluation in Healthy Volunteers\\n<\\/td>\\n    <td class=\\\"test_bs-column  \\\">\\n      <a class=\\\"index as_action toggle\\\" data-position=\\\"after\\\" data-action=\\\"index\\\" data-cancel-refresh=\\\"true\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-__org__org1__principal_investigators1s-index-test_bs-45-link\\\" data-remote=\\\"true\\\" href=\\\"/org/org1/principal_investigators1s?association=test_bs&amp;intramural_study_oversight_and_statuses1_id=45&amp;parent_scaffold=org%2Forg1%2Fintramural_study_oversight_and_statuses1s&amp;button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name%5D=Alevizos%2C+Ilias&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93\\\"> <\\/a>\\n<\\/td>\\n    <td class=\\\"test_as-column  empty \\\">\\n      <a class=\\\"index as_action toggle\\\" data-position=\\\"after\\\" data-action=\\\"index\\\" data-cancel-refresh=\\\"true\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-__org__org1__dsmc_processes1s-index-test_as-45-link\\\" data-remote=\\\"true\\\" href=\\\"/org/org1/dsmc_processes1s?association=test_as&amp;intramural_study_oversight_and_statuses1_id=45&amp;parent_scaffold=org%2Forg1%2Fintramural_study_oversight_and_statuses1s&amp;button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name%5D=Alevizos%2C+Ilias&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93\\\">-<\\/a>\\n<\\/td>\\n    <td class=\\\"ce-column  empty \\\">\\n      -\\n<\\/td>\\n    <td class=\\\"te-column  empty \\\">\\n      -\\n<\\/td>\\n    <td class=\\\"irb-column  \\\">\\n      CNS IRB Purple Panel\\n<\\/td>\\n    <td class=\\\"status-column  \\\">\\n      ACTIVE\\n<\\/td>\\n    <td class=\\\"irb_termination_date-column  \\\">\\n      n/a\\n<\\/td>\\n    <td class=\\\"date_last_irb_approval-column  \\\">\\n      4/12/2013\\n<\\/td>\\n    <td class=\\\"next_imv-column  empty \\\">\\n      -\\n<\\/td>\\n    <td class=\\\"comments-column  empty \\\">\\n      &nbsp;\\n<\\/td>    \\n  <td class=\\\"actions\\\"><table>\\n    <tr>\\n      <td class=\\\"indicator-container\\\">\\n        <img style=\\\"visibility:hidden;\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-record-45-loading-indicator\\\" alt=\\\"loading indicator\\\" class=\\\"loading-indicator\\\" src=\\\"/assets/active_scaffold/indicator-07b202d8027099d3add8213095a203cecb4938acdebc80f755ef2251a1a5b880.gif\\\" />\\n      <\\/td>\\n      <td><a class=\\\"edit_udt as_action\\\" data-action=\\\"edit_udt\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-edit_udt-45-link\\\" data-remote=\\\"true\\\" href=\\\"/org/org1/intramural_study_oversight_and_statuses1s/45/edit_udt?button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93&amp;eid=e25bb68536b7e249ac86d8a097e96b9e&amp;record_id=45\\\">Update<\\/a><\\/td><td><a class=\\\"destroy as_action\\\" data-confirm=\\\"Are you sure you want to delete  Salivary Evaluation in Healthy Volunteers?\\\" data-action=\\\"destroy\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-destroy-45-link\\\" data-remote=\\\"true\\\" rel=\\\"nofollow\\\" data-method=\\\"delete\\\" href=\\\"/org/org1/intramural_study_oversight_and_statuses1s/45?destroy_action=true&amp;button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name%5D=Alevizos%2C+Ilias&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93&amp;eid=e25bb68536b7e249ac86d8a097e96b9e&amp;record_id=45\\\">Delete<\\/a><\\/td><td><a class=\\\"show as_action\\\" data-position=\\\"replace\\\" data-action=\\\"show\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-show-45-link\\\" data-remote=\\\"true\\\" href=\\\"/org/org1/intramural_study_oversight_and_statuses1s/45?button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name%5D=Alevizos%2C+Ilias&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93&amp;eid=e25bb68536b7e249ac86d8a097e96b9e&amp;record_id=45\\\">Show<\\/a><\\/td><td><a class=\\\"index as_action toggle\\\" data-position=\\\"after\\\" data-action=\\\"index\\\" data-cancel-refresh=\\\"true\\\" id=\\\"as_e25bb68536b7e249ac86d8a097e96b9e-__paper_trail__versions-index-versions-45-link\\\" data-remote=\\\"true\\\" href=\\\"/paper_trail/versions?association=versions&amp;intramural_study_oversight_and_statuses1_id=45&amp;parent_scaffold=org%2Forg1%2Fintramural_study_oversight_and_statuses1s&amp;button=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bce_te%5D=136%2F250&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcmp_complexity%5D=No+CMP+in+place+after+site+assement+in+2010++++++%2FMin+Complexity+Propose+IMP+Q+2+years&amp;org_org1_intramural_study_oversight_and_statuses1%5Bcomments%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_appr_prot%5D=1%2F11%2F2012&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_dsmc_review%5D=NA&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_irb_approval%5D=4%2F12%2F2013&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_last_monitoring_visit%5D=4%2F3%2F2014&amp;org_org1_intramural_study_oversight_and_statuses1%5Bdate_review_expires%5D=2%2F25%2F2015&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb%5D=CNS+IRB+Purple+Panel&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_sub_type_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date%5D=n%2Fa&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%281i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%282i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Birb_termination_date1%283i%29%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bnext_imv%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bpi_name%5D=Alevizos%2C+Ilias&amp;org_org1_intramural_study_oversight_and_statuses1%5Bprotocol_id%5D=94-D-0018&amp;org_org1_intramural_study_oversight_and_statuses1%5Brecord_id%5D=6&amp;org_org1_intramural_study_oversight_and_statuses1%5Bstatus%5D=ACTIVE&amp;org_org1_intramural_study_oversight_and_statuses1%5Bte%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_a_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=2&amp;org_org1_intramural_study_oversight_and_statuses1%5Btest_b_ids%5D%5B%5D=4&amp;org_org1_intramural_study_oversight_and_statuses1%5Btitle%5D=Salivary+Evaluation+in+Healthy+Volunteers&amp;org_org1_intramural_study_oversight_and_statuses1%5Btype_last_monitoring_visit%5D=&amp;org_org1_intramural_study_oversight_and_statuses1%5Bversion_last_apprv_prot%5D=V_2.0.3&amp;udt_id=1&amp;utf8=%E2%9C%93\\\">Changes<\\/a><\\/td>\\n    <\\/tr>\\n  <\\/table><\\/td>\\n<\\/tr>\\n"

**Comment by scambra** [comment]
What are the params of your form? ActiveScaffold includes all the params except :record and few ones used by ActiveScaffold, such as :adapter, :position, :sort, :sort_direction, :page, :auto_pagination, :commit, :_method, :authenticity_token, :iframe, :associated_id, :dont_close

Your input fields in the form should have a name like record[column_name]

**Comment by markmcdonald51** [comment]
hi sergio. 

right you are! Thanks for that. All i did was delete the param after the create/update and then everything works just fine and dandy! I am using formtastic so I could just  do 

udt_param_name = model_name.param_key.to_sym  

for the entire key.    

     # remove all of the params withing the key 'udt_param_name' 
        # as active scaffold will try to convert them into an anchor...
        params.delete(udt_param_name)


thanks so much sergio!
