### ISSUE TITLE
Cannot read property 'update_flash_messages' of null

### ISSUE THREAD

**Issue by Reedian** [activescaffold/active_scaffold#505]
I have created my own create form for active scaffold with CKEditor. Everything seemed to work on branch which I used to developer new feature, but after merging everything to master without any conflicts I have approached RJS error.

Every time I try to submit my form browser popup with error message appears:
```
RJS error:

TypeError: Cannot read property 'update_flash_messages' of null
```

I have spent several hours on checking class names, gems version and I have no idea what to do. Record is saving to database but this error appears every time.

**Comment by scambra** [comment]
Is it on create or update form? or custom action?

**Comment by Reedian** [comment]
It is on create form

**Comment by scambra** [comment]
This is first lines of create response:

```js
action_link = ActiveScaffold.find_action_link('create_form_selector');
action_link.update_flash_messages('HTML');
```

Your error is saying it didn't find action_link for create form, so closing form won't work either. Did you change id for create form, or did you close it manually before AS response is executed?

**Comment by Reedian** [comment]
I found workaround. I got rid of iframe from form_tag and it seems to work now.
