### ISSUE TITLE
Question: modifying config values

### ISSUE THREAD

**Issue by Grondhammar** [activescaffold/active_scaffold#506]
Hi, this is not an issue, just a question. I have searched SO and the wiki here and can't find any help.

I am trying to do things like change config.label and config.list.per_page based on query string ([params]) values, but init is too soon to get the params hash. And all my attempts to modify config later on are failing. How can I accomplish this?

Thank you, really appreciate all the work that's gone into this gem.

**Comment by scambra** [comment]
Use before_action (before_filter on rails 3):

https://github.com/activescaffold/active_scaffold/wiki/Per-Request-Configuration

That value is stored in class variable, so you need to change to right value on every request, I'm working to do this thread-safe so changing config is not saved between requests, probably for next major version.

**Comment by Grondhammar** [comment]
Excellent, thank you!
