### ISSUE TITLE
validation failure while creating a record with has_many association

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#507]
Hello,

I have 2 tables one with has_many association and the other with belongs to. The models looks as follows:

**map.rb**:

```
class Map < ActiveRecord::Base
  has_many :fields
end
```

**field.rb**

```
class Field < ActiveRecord::Base
  belongs_to :map 
end
```

In the migration of field.rb, I have a field map_id.
But, when I try to create a map record by selecting some fields, 

1 error prohibited this map from being saved
There were problems with the following fields:
- Field is invalid

Can someone please let me know where I am going wrong?

Thank you.

**Comment by scambra** [comment]
Do you have validations on field model? I don't see them but that error should be related to validations.
Also, could you post active_scaffold related code on controllers?

**Comment by peggles2** [comment]
Hi, I am having the same issue. It started to happen after I upgraded to version 3.5. The has many through validations are failing when I run my rspec tests. 
Currently using
ruby 2.3.8p459
Rails 4.2.11.1

```
        routed_query = affiliate.routed_queries.build(url: "http://www.gov.gov/foo.html", description: "testing")
        routed_query.routed_query_keywords.build(keyword: 'foo bar')
        routed_query.save!

```
This fails now after upgrading. The error I get is 
```
     ActiveRecord::RecordInvalid:
       Validation failed: Routed query keywords routed query can't be blank

```
Affiliate model has a has many through association with routed_queries.
`  has_many :routed_query_keywords, -> { order 'keyword' }, through: :routed_queries
`
Also there is a validation that requires that routed query keywords is not blank
```
def keywords_cannot_be_blank
    errors.add(:base, 'Routed query must have 1 or more search terms') if routed_query_keywords.blank? || routed_query_keywords.all?(&:marked_for_destruction?)
  end
```
The tests were passing with active_scaffold version 3.4.43 and after upgrading to active_scaffold version 3.5.0 it is failing.
Is there any documentation on any code changes that we should keep in mind when upgrading to 3.5.0? Any help is appreciated.

**Comment by scambra** [comment]
@peggles2 you're not using activescaffold in your test, you're using only models. Can you test it without ActiveScaffold? I guess plain rails would fail too.

You may want to set inverse_of in your associations, and see if it fixes your test. ActiveScaffold 3.4 was monkey patching association reflections to look for reverse associations, but it caused some issues and it was removed in 3.5, and then column.association was changed to return own ActiveScaffold class instead of ActiveRecord's association reflection.

**Comment by peggles2** [comment]
Thank you!! That worked.
Also noticed after the upgrade options_for_association_conditions requires
2 values to be passed. before it was ok with just passing association.

This below no longer worked unless I passed (association, record) through.

module Admin::AssociationsHelper
  def options_for_association_conditions(association)
    if association.name == :default_affiliate
      ['affiliates.id IN (?)', @record.affiliate_ids]
    else
      super
    end
  end
end



https://github.com/activescaffold/active_scaffold/wiki/Custom-Association-Options

**Comment by peggles2** [comment]
Thank you!! That worked.
Also noticed after the upgrade options_for_association_conditions requires
2 values to be passed. before it was ok with just passing association.

This below no longer worked unless I passed (association, record) through.

module Admin::AssociationsHelper
  def options_for_association_conditions(association)
    if association.name == :default_affiliate
      ['affiliates.id IN (?)', @record.affiliate_ids]
    else
      super
    end
  end
end
https://github.com/activescaffold/active_scaffold/wiki/Custom-Association-Options

**Comment by scambra** [comment]
There was a deprecation warning for a while if method was defined with one argument only, probably you missed that. Now it's mandatory to define with record argument. You shouldn't use @record in the helpers, it will be different to record argument for subforms. I have fixed second example in that wiki page, first example was already right

**Comment by peggles2** [comment]
Thank you!
