### ISSUE TITLE
Change the order in which options appear in the form while creating a new record.

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#508]
Hi,

I have a table called days_of_the_weeks which is has_and_belongs_to_many associated with groups.
While creating a new record the options are appearing in the alphabetical order as shown below instead of the order of ID.

![image](https://cloud.githubusercontent.com/assets/15997451/16678270/22b8b524-44fb-11e6-9aa9-71349b1fba9c.png)

Is there a way to change them to the order of ID?

Thanks,
Mounika

**Comment by mounika36** [comment]
Hi,

```
def group_days_of_the_weeks_form_column(record, options)
  column = active_scaffold_config.columns[:days_of_the_weeks]
  select_options = DaysOfTheWeek.select('*').order("id")
  active_scaffold_checkbox_list(column, select_options, DaysOfTheWeek.select('id'), options)
end
```

This solved my issue, but when I select some options and save a record it is saved correctly.
But when I click on edit all the options of days_of_the_week are unchecked.

Can someone help me with this?

Thanks,
Mounika

**Comment by mounika36** [comment]
Hi,

It's working perfectly this way. :D 

```
  def feed_group_days_of_the_weeks_form_column(record, options)
    column = active_scaffold_config.columns[:days_of_the_weeks]
    select_options = DaysOfTheWeek.select('*').order("id")
    active_scaffold_checkbox_list(column, select_options, record.days_of_the_weeks.collect(&:id), options)
  end
```

-Mounika

**Comment by scambra** [comment]
Another way, using form_ui instead of form override:
```ruby
def sorted_association_options_find(association, conditions = nil, record = nil)
  if association.name == :days_of_the_weeks
    super.sort_by(&:id)
  else
    super
  end
end
