### ISSUE TITLE
Change the theme

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#510]
Hi,

I am using activescaffold 3.4.39.
In config/initializers/active_scaffold.rb, I have the theme as "config.theme = :default"

I think the default one is blue theme.

Is there any way to change the theme?
Is there any documentation available to know what all themes are available and how to use?

Thanks.

**Comment by scambra** [comment]
There is a blue-theme.css file in app/assets/stylesheets but it's not used, default value for config.theme is :default. config.theme only adds a #{theme}-theme class to main active-scaffold div

You should be able to use config.theme = :blue and add blue-theme file to your application.css, below require active_scaffold line.

There is active_scaffold_colors.scss file which define some default SASS variables, you can change some of these variables in your application.css or in required scss file, but you must set value before require active_scaffold line

**Comment by mounika36** [comment]
Hi Scambra,

I understand that we can change the variables of active_scaffold_colors.scss file.

But can you please let me know how to change them in application.css and what value to be set before require active_scaffold line?

My application.css file looks as follows:
```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require active_scaffold
 *= require_tree .
 */
```

Thanks.

**Comment by scambra** [comment]
I was wrong, the way SASS variables work, you have to create a scss file, define variables there and import active_scaffold, so remove require active_scaffold from application.css

application.css:
```css
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require theme
 *= require_tree .
 */
```

theme.scss
```scss
$column_header_bg: #550;
@import 'active_scaffold'
```

**Comment by mounika36** [comment]
Thanks, That's working perfectly! :D

**Comment by mounika36** [comment]
Hi,

Another quick question..
Is it possible to adjust the lengths and alignments in active_scaffold_layout.css?

I tried in the similar way as I did for active_scaffold_colors.scss.
But I don't see it's working.

layout_theme.css

```
.active-scaffold th {
text-align: right;
}

@import 'active_scaffold';
```
application.css

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require layout_theme
 *= require theme
 *= require_tree .
 */

```

Thanks..

**Comment by scambra** [comment]
You can, but two points:

- You shouldn't import active_scaffold twice, you are importing on layout_theme and theme.
- SCSS variables needs to be defined before @import, css rules to change values needs to be defined after.

I see two possibilities:

- Add text-align to theme scss file, after @import
- Move layout_theme below theme, remove @import from layout_theme

**Comment by mounika36** [comment]
Perfect! Moved layout_theme below theme, removed @import from layout_theme.
Thanks.
