### ISSUE TITLE
RecordSelect Under Rails 5

### ISSUE THREAD

**Issue by tripodrob** [activescaffold/active_scaffold#515]
RecordSelect throws the following error under Rails 5:

ActionView::Template::Error (Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.):
    1: <% url_options = params.merge(:controller => controller, :action => :browse, :page => 1, :update => 1) -%>
    2: <%= form_tag url_options, {:method => :get, :remote => true, :id => record_select_search_id}  -%>
    3:   <%= text_field_tag 'search', params[:search], :autocomplete => 'off', :class => 'text-input' %>
    4:   <%= submit_tag 'search', :class => "search_submit" %>
    5: </form>

**Comment by tripodrob** [comment]
Would it be reasonable to whitelist the parameters in the record_select gem partials,  e.g. _search.html.erb:

<% url_options = params.merge(:controller => controller, :action => :browse, :page => 1, :update => 1) -%>
<%= form_tag url_options.permit(:controller, :action, :search, :update), {:method => :get, :remote => true, :id => record_select_search_id}  -%>

**Comment by scambra** [comment]
See https://github.com/scambra/recordselect/issues/14
