### ISSUE TITLE
XSS via the eid param

### ISSUE THREAD

**Issue by marius-bodnariuc** [activescaffold/active_scaffold#517]
Hello,

It looks like the `eid` param can be used to inject JS into AS-generated pages.

I have set up a [basic Rails 3 project](https://github.com/marius-bodnariuc/as-eid-inj) that can be used to reproduce the issue I'm referring to.

The problem seems to be avoided if `params[:eid]` gets `h`'ed every time it appears in the request, such as, for example, via a new hook in `lib/active_scaffold.rb`.

Can you guys please have a look and advise as to what the desired fix or workaround should be?

Thank you,

Marius

**Comment by scambra** [comment]
Rails 3 is not supported on master branch, and I can't reproduce it with rails 4.2.0
Are you able to reproduce it with rails >= 4 and master branch?

**Comment by scambra** [comment]
I was testing on server which responds with X-XSS-Protection:1; mode=block header

**Comment by marius-bodnariuc** [comment]
@scambra thank you, that was really quick!

I had some doubts about putting the `h` in `id_from_controller` because of [this commit of yours](https://github.com/activescaffold/active_scaffold/commit/0c31c2c900cd535fc28dffbb9112a668c945ffa1) from long ago.

**Comment by scambra** [comment]
You're right, although I'm not sure if id helpers are still used in controllers, IdHelpers is included in ControllerHelpers but I cannot see any method used in controllers.
I could replace h with ERB::Util.h, I will leave open and try to find if using h is wrong, or I should remove IdHelpers from ControllerHelpers

**Comment by fnicola** [comment]
this is still happening and in particular in this view: app/views/active_scaffold_overrides/_list_with_header.html.erb
`data-eid` is not escaped properly and results in enabling XSS. 
in example:
http://localhost:3000/entity?eid=1%20onmouseover=alert(1)
@scambra any suggestions here?
