### ISSUE TITLE
Force the page to refresh after a certain action.

### ISSUE THREAD

**Issue by AlexandruCD** [activescaffold/active_scaffold#519]
Let's say i want to allow create just if in the database, certain records are not present.
Initially i am on the page and Create link is present. I use it to create a new record that after goes into the database, should not allow Create to be used again.
I added in my model self.authorized_for_create?, function.
The behaviour is that after i create the record that stops the create link to be present, it is still here after record is created and create form closes. If i manually refresh the page, it goes away. If i click it before i refresh, i get a 401. How can I trigger a refresh, that will go to that model function, detect my conditions for showing create link, and hide it, without forcing me to do a refresh.
thanks.

**Comment by scambra** [comment]
You can disable inline create form, so always is refreshed. Also, you can enable refresh_list on create and refresh_with_header on list (otherwise, header is not refreshed and create link won't be removed):

```ruby
config.create.refresh_list = true
config.list.refresh_with_header = true
```
