### ISSUE TITLE
Rails 5 Field Search not rendering results

### ISSUE THREAD

**Issue by tripodrob** [activescaffold/active_scaffold#526]
The Field Search doesn't render the results after a search.  If you refresh the page the results are refined, but not directly after a search.

**Comment by tripodrob** [comment]
I don't know if this is being looked at, but appears it's likely due to the way ActionController::Parameters are now returned as an Object and not a hash in Rails 5.

In the lib/active_scaffold/actions/field_search.rb the parameter check in the do_search method is checking for a Hash, which is not the type being returned now.

**Comment by scambra** [comment]
Thanks for guiding
