### ISSUE TITLE
Mark all does not work when model contains a column named "Value"

### ISSUE THREAD

**Issue by vtt** [activescaffold/active_scaffold#530]
The mark all toggle checkbox does not work when the model contains a column named "Value".
Marking each row seems to work fine.

**Comment by scambra** [comment]
can you post log for clicking mark all? I would like to see sent parameters and queries

**Comment by vtt** [comment]
Logs for mark all:

> Started POST "/en/translations//mark" for 192.168.0.10 at 2016-12-28 09:16:55 -0700
> Processing by TranslationsController#mark as JS
>   Parameters: {"authenticity_token"=>"/p5p6 dFdd3V9kSK5IUAvjO3xBS7X9SKF7y8pFMqawIjH98Jf1BBvxSJBjtvwE0AT8pq2L2/9Tax068mihaEBw==", "value"=>"1", "locale"=>"en"}

Logs for unmark all

> Started POST "/en/translations//mark" for 192.168.0.10 at 2016-12-28 09:17:26 -0700
> Processing by TranslationsController#mark as JS
>   Parameters: {"authenticity_token"=>"/p5p6 dFdd3V9kSK5IUAvjO3xBS7X9SKF7y8pFMqawIjH98Jf1BBvxSJBjtvwE0AT8pq2L2/9Tax068mihaEBw==", "locale"=>"en"}

Logs for marking single row (this works fine)

> Started POST "/en/translations/2694/mark" for 192.168.0.10 at 2016-12-28 09:20:01 -0700
> Processing by TranslationsController#mark as JS
>   Parameters: {"authenticity_token"=>"/p5p6 dFdd3V9kSK5IUAvjO3xBS7X9SKF7y8pFMqawIjH98Jf1BBvxSJBjtvwE0AT8pq2L2/9Tax068mihaEBw==", "value"=>"1", "locale"=>"en", "id"=>"2694"}
> 
Logs for unmarking single row (this also works fine)

> Started POST "/en/translations/2694/mark" for 192.168.0.10 at 2016-12-28 09:21:51 -0700
> Processing by TranslationsController#mark as JS
>   Parameters: {"authenticity_token"=>"/p5p6 dFdd3V9kSK5IUAvjO3xBS7X9SKF7y8pFMqawIjH98Jf1BBvxSJBjtvwE0AT8pq2L2/9Tax068mihaEBw==", "locale"=>"en", "id"=>"2694"}
