### ISSUE TITLE
Remove , from all integers.

### ISSUE THREAD

**Issue by mounika36** [activescaffold/active_scaffold#533]
Hi,

All integers are by default delimited by `','` .
For ex: 123456 is stored as 1,23,456.
Is there a way to remove `','` from all integers for all tables.

If it is for a single table, we can do in the following way in it's controller.
`config.columns[:<int_field>].options={:i18n_options => {delimiter: ""}}`

Is there a way to do this for all integer fields?

Thanks.

**Comment by scambra** [comment]
column with i18n_number format option uses number_with_delimiter or number_with_precision, you can set options with options[:i18n_options], but default options must be in locale file:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/locale/en.yml#L37

Also, you can override format_number_value in your application helper:

```ruby
def format_number_value(value, options = {})
  if some_condition
     ...
  else
    super
  end
end
```

**Comment by mounika36** [comment]
Perfect! :)

```
def format_number_value(value, delimiter = '')
  if value.is_a? Integer
     ActiveSupport::NumberHelper.number_to_delimited(value, delimiter: '')
  else
    super
  end
end
```

Thanks.
