### ISSUE TITLE
pathing to jquery-ui widgets like sortable seems amiss w/ jquery-datatables-rails 6+

### ISSUE THREAD

**Issue by bretweinraub** [activescaffold/active_scaffold#543]
Leaves me with

    ActionView::Template::Error (couldn't find file 'jquery-ui/sortable' with type 'application/javascript'

```
gem list | egrep \(scaf\|jquery\)
active_scaffold (3.4.41.1)
active_scaffold_export (3.3.2)
jquery-rails (4.2.2)
jquery-ui-rails (6.0.1)
rails-assets-jquery (3.1.1)
```

Patch/merge request forthcoming

**Comment by bretweinraub** [comment]
fixed here
https://github.com/bretweinraub/active_scaffold/commit/4269340087724b1b4deddf77a273ad1a51fcd678

**Comment by scambra** [comment]
That's fixed in master

**Comment by bretweinraub** [comment]
when will it get into the released gem?

**Comment by bretweinraub** [comment]
Per the README

> 3-4-stable supports rails >= 3.2.x and ruby >= 1.9.3 3-3-stable supports rails >= 3.2.x and ruby >= 1.8 rails-3.2 branch on Github supports Rails 3.1 & 3.2, and is the current source of the 3.2.x line of gems.

**Comment by scambra** [comment]
master branch? No ETA, when I finish some features in progress, but it's stable

**Comment by bretweinraub** [comment]
Cool.... for those reading at home, I've worked around this [this is Rails-4.2.2 w/ jquery-ui-rails (6.0.1)] via:

```
# this should be removed once the following pull request is adopted or gem with fix released (https://github.com/activescaffold/active_scaffold/issues/543#issuecomment-279990334):
# https://github.com/activescaffold/active_scaffold/pull/544
gem 'active_scaffold',  :branch => '3-4-stable', :git => 'git@github.com:bretweinraub/active_scaffold.git'

```
So can you maybe leave the issue open until you've released a fix?   Or is there another why we can come to understand that we can drop this from our project?

**Comment by scambra** [comment]
that pull request is merged, you can use :github => 'activescaffold/active_scaffold', :branch => '3-4-stable'

You can change to '~> 3.4.43' when new 3.4.x version is released, or just keep branch '3-4-stable', 3-4-stable will only get fixes
