### ISSUE TITLE
for master branch of AS in rails 5.0.1 have error in field_search

### ISSUE THREAD

**Issue by bencarsal** [activescaffold/active_scaffold#545]
The problem was for in retrieve ActiveRecord column type for rails 5.0.1 change. I resolve with this:
- in .\lib\active_scaffold\data_structures\column.rb line 316 change:
this:
      @text = @column.nil? || [:string, :text, String].include?(@column.type)
for this:
     @text = false
      if Rails.version >= '5'
        @text = @column.nil? || [:string, :text, String].include?(@column.type.type)
      else
        @text = @column.nil? || [:string, :text, String].include?(@column.type)
      end
- in .\lib\active_scaffold\core.rb line 235 insert this:
     elsif Rails.version < '5.1'
        #column.type.cast value
        column.type.cast value
- in .\lib\active_scaffold\finder.rb line 99, change:
    search_ui = column.search_ui || column.column.try(:type)
for this:
        search_ui = nil
        if Rails.version < '5.0'
          search_ui = column.search_ui || column.column.try(:type)
        else
          search_ui = column.search_ui || column.column.type.type
        end
And this is all. I could make it work for me.

**Comment by scambra** [comment]
Are you sure is it for rails 5.0.1? I have tried with 5.0.1 and column.type returns :string, there is no type.type

Anyway, can you make a pull request?

**Comment by bencarsal** [comment]
I´m sure, ok, i'm going to pull request...

**Comment by scambra** [comment]
I have tried with rails 5.0.1 and 5.0.2.rc1 and current code works. Here is a simple test:

> User.columns_hash['name'].type
 => :string 
> User.columns_hash['name'].type.type
NoMethodError: undefined method `type' for :string:Symbol
> User.columns_hash['name'].class
 => ActiveRecord::ConnectionAdapters::Column 
> User.columns_hash['name'].sql_type_metadata
 => #<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x000000062ae008 @sql_type="varchar", @type=:string, @limit=nil, @precision=nil, @scale=nil> 

Can you post output for those commands, changing model and column to your own ones?

**Comment by scambra** [comment]
I saw you use jruby and activerecord-jdbc-adapter, can you send me output of those commands?

```
> Model.columns[1].class
> Model.columns[1].type
> Model.columns[1].sql_type_metadata
```

**Comment by bencarsal** [comment]
> Model.columns[1].class
      => ActiveRecord::ConnectionAdapters::PostgreSQLColumn
      > Model.columns[1].type
      => #<ActiveModel::Type::String:0x53f5082 @precision=nil,
      @limit=3, @scale=nil>
      > Model.columns[1].sql_type_metadata

      =>
      #<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x177cd53f
      @precision=nil, @scale=nil,
      @type=#<ActiveModel::Type::String:0x53f5082 @precision=nil,
      @limit=3, @scale=nil>, @sql_type="character(3)", @limit=nil>
      
      El 01-03-2017 a las 8:35, Sergio Cambra escribió:
    
    
      I saw you use jruby and activerecord-jdbc-adapter, can you send
        me output of those commands?
      > Model.columns[1].class
> Model.columns[1].type
> Model.columns[1].sql_type_metadata

      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/activescaffold/active_scaffold","title":"activescaffold/active_scaffold","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/activescaffold/active_scaffold"}},"updates":{"snippets":[{"icon":"PERSON","message":"@scambra in #545: I saw you use jruby and activerecord-jdbc-adapter, can you send me output of those commands?\r\n\r\n```\r\n\u003e Model.columns[1].class\r\n\u003e Model.columns[1].type\r\n\u003e Model.columns[1].sql_type_metadata\r\n```\r\n"}],"action":{"name":"View Issue","url":"https://github.com/activescaffold/active_scaffold/issues/545#issuecomment-283317674"}}}
