### ISSUE TITLE
column_class not return "#{column.name}-column"

### ISSUE THREAD

**Issue by tiennv91** [activescaffold/active_scaffold#549]
I have a problem with column_class when render html in active_scaffold, that not render class with "#{column.name}-column "
I find this problem in function `column_class`.
```
def column_class(column, column_value, record)
    @_column_classes ||= {}
    @_column_classes[column.name] ||= begin
      classes = "#{column.name}-column "
      classes << 'sorted ' if active_scaffold_config.actions.include?(:list) && active_scaffold_config.list.user.sorting.sorts_on?(column)
      classes << 'numeric ' if column.number?
      classes << column.css_class unless column.css_class.nil? || column.css_class.is_a?(Proc)
    end
    classes = "#{@_column_classes[column.name]} "
    classes << 'empty ' if column_empty? column_value
    classes << 'in_place_editor_field ' if inplace_edit?(record, column) || column.list_ui == :marked
    if column.css_class.is_a?(Proc)
      css_class = column.css_class.call(column_value, record)
      classes << css_class unless css_class.nil?
    end
    classes
  end
```
When the condition `unless column.css_class.nil? || column.css_class.is_a?(Proc)` (line 7) is false so the `classes << column.css_class` will not running. Thus we don't have value "#{column.name}-column " in class when render html.
I think we need to add new line to return `classes` for variabel `@_column_classes[column.name]` in block.
Please confirm that. Thanks for advances.

**Comment by scambra** [comment]
thanks!
