### ISSUE TITLE
Deprecated 'render :text'

### ISSUE THREAD

**Issue by deff7** [activescaffold/active_scaffold#557]
`DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/html`. (called from render at /home/deff/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/active_scaffold-aeea8b705798/lib/active_scaffold/extensions/action_controller_rendering.rb:14)`

**Comment by scambra** [comment]
master branch still supports 4.0, which doesn't have render :html or render :raw
rails 3.4 supports rails >= 3.2, and master branch will support rails >= 4.0, I don't want to drop support for 3.2 and 4.0 with same version, so replacing render :text with render :html will have to wait until 4.0 support is dropped, but I'm setting content_type

**Comment by scambra** [comment]
@fb78a09

**Comment by deff7** [comment]
Sorry, I have studied a problem in details and found deprecated code in my project. Thank you for rapid response!

**Comment by scambra** [comment]
I'm not sure if deprecation is added in rails 5 or rails 5.1. If it has been removed in rails 5.1, I will have to fix to support rails 5.1, or drop 4.0 support when adding support for 5.1
