### ISSUE TITLE
datetime_picker format issue

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#558]
Hello,

I'm trying to view and edit a datetime column.

To view it in a localized format, I use:
`conf.columns[:expiration_datetime].options[:format] = I18n.t :long, scope: [:time, :formats]`

To edit it in a localized format, I use:
`conf.columns[:expiration_datetime].form_ui = :datetime_picker`
and rely on 
`ro.time.formats.picker: "%d.%m.%Y %H:%M:%S"`

Any one of the two configurations works well but when I try both of them at the same time I get:

`I18n::MissingTranslationData: translation missing: ro.time.formats.%H:%M:%S %d.%m.%Y -- on the ActiveScaffold column = :expiration_datetime in Teachers::ContractsController`

Another thing I tried was to use another format for editing and viewing. However, when I tried:
`ro.time.formats.picker: "%d.%m.%Y %H:%M:%S"`
strange things started to happen when I was using the picker, generating datetimes such as:
`HH:06:ss 13.06.2017 20:30:00 dd.30.yy`

**Comment by scambra** [comment]
Use ```conf.columns[:expiration_datetime].options[:format] = :long```, options[:format] is the key of time.formats, and activescaffold will translate it for each request.

```conf.columns[:expiration_datetime].options[:format] = I18n.t :long, scope: [:time, :formats]``` is the same as ```conf.columns[:expiration_datetime].options[:format] = '%d.%m.%Y %H:%M:%S'```, but options[:format] wants a key for translating, not the format string
