### ISSUE TITLE
undefined method `[]' for nil at /lib/active_scaffold/data_structures/nested_info.rb:109: in 'default_sorting'

### ISSUE THREAD

**Issue by osamutake** [activescaffold/active_scaffold#560]
I upgraded from active_scaffold 3.4.39 to the latest and got the following error
with ruby 2.4.0 and Rails 5.1.2 without turbolinks:

```
  NoMethodError (undefined method `[]' for nil:NilClass):
  (path_to)/lib/active_scaffold/data_structures/nested_info.rb:109:in `default_sorting'
```

https://github.com/activescaffold/active_scaffold/blob/d36f2b307c6f5e96840389efe9f470ceb660da1a/lib/active_scaffold/data_structures/nested_info.rb#L109

It seems the current code does not check if ```chain.values``` indeed have a value for ```:order```.
So, the following patch resolved the problem for me but I'm wondering if this is the best way.

Any suggestion?
Thanks in advance.

```ruby
    def default_sorting(chain)
      return @default_sorting if defined? @default_sorting
 -    if association.scope.is_a?(Proc) && chain.respond_to?(:values)
 +    if association.scope.is_a?(Proc) && chain.respond_to?(:values) && chain.values[:order]
        @default_sorting = chain.values[:order]
        @default_sorting = @default_sorting.map(&:to_sql) if @default_sorting[0].is_a? Arel::Nodes::Node
        @default_sorting = @default_sorting.join(', ')
      end
    end
```

**Comment by scambra** [comment]
Can you make a pull request with that change?
