### ISSUE TITLE
error messages missing on subform

### ISSUE THREAD

**Issue by courtland** [activescaffold/active_scaffold#562]
If a scaffold has a has_many relation using a nested subform, the errors in the `association-record-errors` class are not right. The subform fields with errors are highlighted correctly, but the error message is just "model_name is invalid". This is repeated in the parent form errors as well.

in _form_association_record.html.erb, `record.errors` is correct but `active_scaffold_error_messages_for(:record, :object_name => record.class.model_name.human.downcase)` produces output that is not helpful.

I am running latest active_scaffold master branch and ruby 2.2 and rails 4.2.

**Comment by courtland** [comment]
I don't quite understand how active_scaffold_error_messages_for() is supposed to handle the errors for a nested subform record with the params (without being passed the model object), but the following diff seems to fix the problem.

```
diff --git a/app/views/active_scaffold_overrides/_form_association_record.html.erb b/app/views/active_scaffold_overrides/_form_association_record.html.erb
index 9b541cf8d..be8af7baa 100644
--- a/app/views/active_scaffold_overrides/_form_association_record.html.erb
+++ b/app/views/active_scaffold_overrides/_form_association_record.html.erb
@@ -35,7 +35,7 @@
 <%= content_tag record_tag, :class => "sub-form-record" do %>
   <% unless record.errors.empty? -%>
   <%= content_tag error_tag, :class => "association-record-errors", :id => element_messages_id(:action => record.class.name.underscore, :id => "#{parent_record.id}-#{index}") do %>
-    <% errors = active_scaffold_error_messages_for(:record, :object_name => record.class.model_name.human.downcase) %>
+    <% errors = active_scaffold_error_messages_for(:record, :object => record) %>
     <%= error_inner_tag ? content_tag(error_inner_tag, errors, :colspan => (active_scaffold_config_for(record.class).subform.columns.length + 1 if error_inner_tag == :td)) : errors %>
   <% end %>
   <% end %>
```

Perhaps there are other instances of this problem? I replaced `:object_name` with `:object` because active_scaffold_error_messages_for does the same thing to get the name.

**Comment by scambra** [comment]
object_name is used in errors.template.header, although active_scaffold_error_messages_for would use that same code if object_name is not provided.

    options[:object_name] ||= object.class.model_name.human.downcase
