### ISSUE TITLE
Rails 5 + ActiveScaffold

### ISSUE THREAD

**Issue by chavanrajsandhya** [activescaffold/active_scaffold#563]
if i try with this command , 
rails g active_scaffold:install 
i got like this: 

/home/bitlasoft/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'active_scaffold'.
Gem Load Error is: This version of ActiveScaffold requires Rails 3.1 or higher.  Please use an earlier version.
Backtrace for gem load error is

config/application.rb:7

in my application.rb file line no 7 is this,
 Bundler.require(*Rails.groups)

how to solve this plz explain....

**Comment by scambra** [comment]
rails5 is only supported in master branch, no version is released yet, although is pretty stable. You must change your gemfile:
gem 'activescaffold', github: 'activescaffold/active_scaffold'

**Comment by chavanrajsandhya** [comment]
after adding above line to my gem file i got like this:
Could not find gem 'activescaffold' in https://github.com/activescaffold/active_scaffold.git (at master@4c6191c).
Source does not contain any versions of 'activescaffold'

**Comment by scambra** [comment]
Sorry, I forgot underscore
gem 'active_scaffold', github: 'activescaffold/active_scaffold'
