### ISSUE TITLE
Please fix detection of empty for has_and_belongs_to_many on subforms. Booleans not ignored

### ISSUE THREAD

**Issue by josemelchor** [activescaffold/active_scaffold#564]
This issue is similar to https://github.com/activescaffold/active_scaffold/commit/93df2634cd70be8930f46e6d15288373dddcb9e9

Using HABTM relations on subforms fails if the associated object contains booleans. 

attributes_hash_is_empty?(hash, klass) in lib/active_scaffold/attribute_params.rb is supposed to ignore booleans but it doesn't.

using:
ruby-2.4.0
rails-4.2.8
active_scaffold (3.4.41.1)

**Comment by scambra** [comment]
attributes_hash_is_empty? doesn't ignore booleans since 90a1dd41c7c126dd07f19a8336e1a8787017569a
they are ignored if sent value is equal to default value in db

**Comment by josemelchor** [comment]
I see, you're correct. Thanks. Closing this.
