### ISSUE TITLE
Singular resources mapping

### ISSUE THREAD

**Issue by Gorthi** [activescaffold/active_scaffold#566]
resource :controller will generate routes for the default actions (index, show, new, create, edit, update, and destroy). What should I do if I want to generate routes for the remaining actions too?

**Comment by scambra** [comment]
resource :controller, concerns: :active_scaffold

**Comment by Gorthi** [comment]
I tried using that but it throws "RecordNotFound" error saying "Couldn't find Object without an ID", also it doesn't generate ACTIVE_SCAFFOLD_CORE_ROUTING and ACTIVE_SCAFFOLD_ASSOCIATION_ROUTING routes.

**Comment by rkenzhebekov** [comment]
resource :controller do
 as_routes
end

**Comment by tfantina** [comment]
I'm running into this issue upgrading ActiveScaffold.  I use to have all these `row` actions that ActiveScaffold relied on. I assume they were created by the `as_routes` method.  Now that that is deprecated I've reworked my routes to: 
```ruby
concern :active_scaffold_association, ActiveScaffold::Routing::Association.new
concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
...
resources :controller, concerns: :active_scaffold
...

```
but it dosen't seem to create these `row` actions. 
I get this error message: `{:_method=>:get, :action=>"row", :association=>"users", :controller=>"users"`.
I have to manually add: `get 'row' => 'usersr#row'.

**Comment by scambra** [comment]
There is no row action in activescaffold anymore, have you defined row in your controllers? There is a protected method row, which is called from index action when request has param id (and it isn't an array):

```ruby
    def index
      if params[:id] && !params[:id].is_a?(Array) && request.xhr?
        row
      else
        list
      end
    end

    protected

    # get just a single row
    def row
      get_row
      respond_to_action(:row)
    end
```

ActiveScaffold used to use request to row action to update a row when update form was closed, or nested list was closed, but now it calls index action with id, path is /controller?id=..., so route to row action is not needed.
