### ISSUE TITLE
Commit c0d6ac9b4b6bb40750ac902dd5169b81043783b3 breaks IP addresses (and maybe more)

### ISSUE THREAD

**Issue by sokkalf** [activescaffold/active_scaffold#567]
Hi,

In commit c0d6ac9b4b6bb40750ac902dd5169b81043783b3, there is introduced a fix for "yoda notation". This actually changes how the code works, as it seems as if the class in column_value overrides the equals operator, the code will use that equals operator instead of the one in FalseClass.

We ran into this with IP addresses.
Examples:
New behaviour:
`empty ||= column_value != false && column_value.blank?`
`NoMethodError: undefined method `to_i' for false:FalseClass`
`Did you mean?  to_s`
`from /usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/ipaddr.rb:472:in `initialize'`

Old behaviour before this patch:
`empty ||= false != column_value && column_value.blank?`
`=> false`

Can you maybe find another way to handle this, or revert this patch?

**Comment by scambra** [comment]
thanks for catching
