### ISSUE TITLE
draggable_list renders as checkboxes

### ISSUE THREAD

**Issue by Gorthi** [activescaffold/active_scaffold#572]
Controller:

```
class MarketModelTypologiesController < ApplicationController
  active_scaffold :market_model_typology do |config|
    config.columns = [:field_map,:trade_conditions,:bitmask]
    config.columns[:trade_conditions].form_ui = :select
    config.columns[:trade_conditions].options = {:draggable_lists => true}
  end
end
```

Is there something wrong with the code?

Thanks!

**Comment by scambra** [comment]
If anything not working, it will be related to JS, do you have jquery-ui-rails gem to your gemfile?

**Comment by Gorthi** [comment]
yes, jquery-ui-rails (6.0.1)

**Comment by Gorthi** [comment]
I downgraded jquery-ui-rails to 4.2.1 and created app/assets/javascript/active_scaffold.js.erb amd now it works fine.

**Comment by scambra** [comment]
Using jquery-ui-rails 6.0.1 with activescaffold master branch and works.
No need to requre jquery/draggable_lists, or any jquery ui asset, activescaffold requires them.

Maybe you are using an older activescaffold which doesn't support newer jquery-ui-rails gem (paths changed in 6.0 version)

**Comment by Gorthi** [comment]
I'm using active_scaffold 3.4.41.1, If I use jquery-ui-rails 6.0.1 it renders checkboxes.

**Comment by scambra** [comment]
With 3.4.x you can't use jquery-ui-rails 6. You can with master branch, which will be 3.5.x when released
