### ISSUE TITLE
DatePicker Options not working

### ISSUE THREAD

**Issue by sairamreddy3048** [activescaffold/active_scaffold#574]
Hi, 
I am using datepicker for field-search and I want to set the Max and Min dates for selection (i.e, I want to allow user to pick the dates in the next 3 months range)

  ` conf.columns[:date].options =  {options => [[MaxDate, "+3M"]]}`

HTML is generated like below

`<input type="text" name="search[date][from]" id="search_date_from" options="{:maxDate=>&quot;+3M&quot;}" class="date-input text-input date_picker hasDatepicker" autocomplete="off">`

Is there any option available for configuring the datepicker in active_scaffold.

**Comment by scambra** [comment]
You shouldn't use options key, options[:options] is used for select form_ui
Use data-setting, with any setting allowed in jquery ui datepicker:
https://api.jqueryui.com/datepicker/

Value will be eval with JS, so string must be double enclosed:
conf.columns[:date].options = {'data-maxDate' => '"+3M"'}
