### ISSUE TITLE
remove or replace file HTML render as text string

### ISSUE THREAD

**Issue by venisas** [activescaffold/active_scaffold#576]
![remove_or_replace_file](https://user-images.githubusercontent.com/17031436/33747840-15dddc14-db7a-11e7-93f3-006b342bbd03.png)

Hello,

I was updating to Rails 5 and pulling from master for active_scaffold. The "remove or replace file" link render as text string. (see screen capture above.)  It looks like this was from refactoring form_ui. (see link below.) When I pull master with earlier commits, it renders as HTML. Notice in the screen capture, it also overwrite the "title" field with the same value.  Not sure if it's related.

commit where form_ui was refactored: https://github.com/activescaffold/active_scaffold/commit/3239e959e83cb0fdcd89468983a6873f9be9461a

**Controller** 
```
class DocumentsController < ApplicationController
  active_scaffold :document do |conf|
    conf.columns[:file].form_ui = :carrierwave
```

**Gemfile.lock**
```
GIT
  remote: https://github.com/activescaffold/active_scaffold.git
  revision: 6dadcc06bebddbaeb5c2f5cf5296f83173b08974
  branch: master
  specs:
    active_scaffold (3.4.99)
      ice_nine (~> 0.11)
      rails (>= 4.0.5)

GEM
  remote: https://rubygems.org/
  specs:
    carrierwave (0.11.2)
    rails (5.0.2)
```

Let me know if you need additional info. I am relatively new to rails. Thank you!

**Comment by scambra** [comment]
thanks for reporting, let me know if it works, I'm not using carrierwave to test it
