### ISSUE TITLE
Invalid url params on Embedded scaffold

### ISSUE THREAD

**Issue by rkenzhebekov** [activescaffold/active_scaffold#577]
Hello,

I'm getting invalid url params when I render active_scaffold in the view. What I noticed is the following:

- if I do ```render active_scaffold: 'car', constraints: {type: 'Sedan'}``` in the ```users/index.html.erb``` I get list of  cars rendered properly. 

- if I do ```render active_scaffold: 'car', constraints: {type: 'Sedan'}``` in the ```users/12/show.html.erb``` I don't get proper rendered list of cars. The url edit/show/ actions are renders with id = 12. It acts as if it's trying to load cars with id = 12. 

Could someone help me to figure out why I'm getting different render based on the controller action. Thanks.

**Comment by scambra** [comment]
You are getting id in your params when calling render in a request with id in params. It should be fixed in master branch, but you can try to add params: {id: nil}

**Comment by rkenzhebekov** [comment]
Thanks a lot @scambra! Adding ```params: {id: nil}``` did the job.
