### ISSUE TITLE
NoMethodError in ItemsController#show 

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#581]
I am getting "undefined method `each' for nil:NilClass" for records.each below, and could use some advice on how to find the source of the problem.  The model is complex for this resource.  Any debug advice would be much appreciated.

            records = load_slices sliced
            records.each do |record, owner_key|
              owners_map[owner_key].each do |owner|
                records_by_owner[owner] << record
              end
            end

activerecord (4.2.2) lib/active_record/associations/preloader/association.rb:93:in `block in associated_records_by_owner'
activerecord (4.2.2) lib/active_record/associations/preloader/association.rb:92:in `each'
activerecord (4.2.2) lib/active_record/associations/preloader/association.rb:92:in `associated_records_by_owner'
activerecord (4.2.2) lib/active_record/associations/preloader/singular_association.rb:9:in `preload'
activerecord (4.2.2) lib/active_record/associations/preloader/association.rb:20:in `run'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:146:in `block (2 levels) in preloaders_for_one'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:144:in `each'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:144:in `map'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:144:in `block in preloaders_for_one'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:143:in `each'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:143:in `flat_map'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:115:in `preloaders_on'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:103:in `block in preload'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:102:in `each'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:102:in `flat_map'
activerecord (4.2.2) lib/active_record/associations/preloader.rb:102:in `preload'
activerecord (4.2.2) lib/active_record/relation.rb:644:in `block in exec_queries'
activerecord (4.2.2) lib/active_record/relation.rb:643:in `each'
activerecord (4.2.2) lib/active_record/relation.rb:643:in `exec_queries'
activerecord (4.2.2) lib/active_record/relation.rb:514:in `load'
activerecord (4.2.2) lib/active_record/relation.rb:243:in `to_a'
activerecord (4.2.2) lib/active_record/relation/finder_methods.rb:487:in `find_take'
activerecord (4.2.2) lib/active_record/relation/finder_methods.rb:105:in `take'
activerecord (4.2.2) lib/active_record/relation/finder_methods.rb:454:in `find_one'
activerecord (4.2.2) lib/active_record/relation/finder_methods.rb:435:in `find_with_ids'
activerecord (4.2.2) lib/active_record/relation/finder_methods.rb:71:in `find'
active_scaffold (3.4.41.1) lib/active_scaffold/finder.rb:336:in `find_if_allowed'
active_scaffold (3.4.41.1) lib/active_scaffold/actions/show.rb:46:in `do_show'
active_scaffold (3.4.41.1) lib/active_scaffold/actions/show.rb:14:in `show'
actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
rack (1.6.8) lib/rack/etag.rb:24:in `call'
rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.8) lib/rack/head.rb:13:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.8) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.8) lib/rack/lock.rb:17:in `call'
rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/application.rb:164:in `call'
railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
rack (1.6.8) lib/rack/urlmap.rb:66:in `block in call'
rack (1.6.8) lib/rack/urlmap.rb:50:in `each'
rack (1.6.8) lib/rack/urlmap.rb:50:in `call'
rack (1.6.8) lib/rack/lock.rb:17:in `call'
rack (1.6.8) lib/rack/content_length.rb:15:in `call'
rack (1.6.8) lib/rack/handler/webrick.rb:88:in `service'
/Users/dbulgatz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/dbulgatz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/dbulgatz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by scambra** [comment]
You can try upgrading rails to latest 4.2, it must be a rails bug, raised because activescaffold is asking activerecord to preload some associations.
As workaround you could try to remove includes in some association, try one by one until you find out which association is raising this issue.
