### ISSUE TITLE
Empty column appears, On disabling all row actions like edit, delete, show.

### ISSUE THREAD

**Issue by harishmallow** [activescaffold/active_scaffold#582]
![screen shot 2018-02-19 at 5 02 24 pm](https://user-images.githubusercontent.com/32630715/36375787-b253df8e-1596-11e8-908c-ab8a6e3a2e33.png)

Last column for actions is empty. It shows as empty column. how to make it disappear?

**Comment by scambra** [comment]
If you know it will be always empty for that controller you can use CSS:

.controller_name-view .as_content table .actions {
    display: none;
}

You could use JS to get empty .actions cells:

$('.as_content table .actions').filter(function(){
    return $(this).html().trim() == "";
})

If you want to remove from html, you can override _list_column_headings and _list_record partials. Open partials from gem source and copy to your app/views/active_scaffold_overrides

**Comment by harishmallow** [comment]
Hi,
	I have a table with overrided column campaign.. In which name text is based on logic. I need to search records on this fields.. I tried with search overrides.. but it didn’t work.. Any ideas? Thanks in advance..

**Comment by scambra** [comment]
@harishmallow your question is not a bug, please use google group  for questions about activescaffold usage.
https://groups.google.com/forum/#!forum/activescaffold
