### ISSUE TITLE
 How can I override the default notice messages in active_scaffold?. 

### ISSUE THREAD

**Issue by Gomathi-N** [activescaffold/active_scaffold#583]
The default notice message shows as an object like this in active_scaffold.      Updated #&lt;Brochure:0x007f82e6b002f0&gt;

**Comment by scambra** [comment]
Define to_label for your model. You should define it for all models used by activescaffold, unless they have name, label or title column.

https://github.com/activescaffold/active_scaffold/wiki/Describing-Records:-to_label
