### ISSUE TITLE
Active scaffold not updating form_ui : select values,  when values gets changed

### ISSUE THREAD

**Issue by harishmallow** [activescaffold/active_scaffold#584]
Im using active scaffold for two model "Category" and "template"
Associations:  Category has many Templates and Template belongs_to Category
In **template** active scaffold On create and edit view, trying choose category for template using form_ui : select, On first time, it gets all categories and once I add new category, It does not get updated in template create Or edit...

```
    conf.columns[:category_id].form_ui = :select
    conf.columns[:category_id].options = { options: Category.all.map do |category| [category.name, category.id] end, include_blank: true}

```

**Comment by harishmallow** [comment]
Solved it.  Instead of using .map, .collect got the result from associated model.

**Comment by harishmallow** [comment]
Not getting updated categories.

**Comment by scambra** [comment]
Don't set options for columns on active_scaffold config block if you want dynamic options, config block is evaluated only once when server starts.
Also, if column is association, ActiveScaffold would display all categories by default, if you want to filter them use helpers:
https://github.com/activescaffold/active_scaffold/wiki/Custom-Association-Options

So, change it to use :category column in your form:

```ruby
conf.columns[:category].form_ui = :select
```

If you want to use options for non-association column, you can set in column.options hash if they don't change, or define active_scaffold_enum_options helper:
https://github.com/activescaffold/active_scaffold/wiki/Enum-Columns

**Comment by HarishR-amesh** [comment]
You Are Awesome @scambra
