### ISSUE TITLE
Remove Cancel link at create and update action

### ISSUE THREAD

**Issue by Gomathi-N** [activescaffold/active_scaffold#586]
How can I remove the cancel link which comes with create and update action?

**Comment by scambra** [comment]
With CSS, you can hide all, or only for some controllers:

// all controllers
form.as_form .form-footer .as_cancel { display: none; }
// one controller
.controller_name-view .form-footer .as_cancel {display: none;}

Also, you can override _create_form.html.erb and _update_form.html.erb:

<%= render :super, locals: {cancel_link: false} %>
