### ISSUE TITLE
3.5.0+ broken code with "new_model"

### ISSUE THREAD

**Issue by vtt** [activescaffold/active_scaffold#589]
In actions/core.rb line 260-272

relation = beginning_of_chain  # this gives ActiveRecord
config = active_scaffold_config_for(relation.klass) if nested? && nested.plural_association?
column = relation.klass.inheritance_column

relation.klass <<< this throws exception

**Comment by scambra** [comment]
Can you post request log?
Also, have you changed beginning_of_chain in your controller? beginning_of_chain for nested in plural associations should never return ActiveRecord:

```ruby
      if nested? && nested.association
        if nested.association.collection?
          nested_parent_record.send(nested.association.name)

**Comment by vtt** [comment]
> Started GET "/users/new?adapter=_list_inline_adapter" for 192.168.0.10 at 2018-04-03 21:07:24 -0600
> Processing by UsersController#new as JS
>   Parameters: {"adapter"=>"_list_inline_adapter"}
>   User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "96552a64-b574-4451-a6ed-a0decb2538f5"], ["LIMIT", 1]]
> Completed 500 Internal Server Error in 21ms (ActiveRecord: 1.4ms)
> 
> NoMethodError (undefined method `klass' for #<Class:0x000055a3cc578b48>
> Did you mean?  class):


I don't change "beginning_of_chain".  The problem exists in non-nested scaffold.
As you can see on line 230 of the same file:

```
def beginning_of_chain
   active_scaffold_config.model
end

```
relation = beginning_of_chain # will return a model; so calling model.klass gives exception

It may work for nested scaffolds, but it breaks for simple normal non-nested scaffolds.

**Comment by vtt** [comment]
The problem line of code is
`column = relation.klass.inheritance_column`
The gem 3.5.0 works fine because that line does not exist.  That line is only present in master or 3.5.0+

**Comment by scambra** [comment]
That line is in 3.5.0, but inside if condition. I see the problem relation.klass.inheritance_column was called only for nested controllers in 3.5.0
