### ISSUE TITLE
ActiveScaffold on NonModel (Array)

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#593]
While creating a Reports using  Activescaffold I have to first store the result in Report Model table  and then list the result using same model. On every execution of report I need to truncate the old content and insert new content. I know this is very bad practice but I have no solution till date.

Is there any way I can use ActiveScaffold on result array.

**Comment by scambra** [comment]
You can try assigning array to @records and render list, but controller needs a ActiveRecord model to read available columns. I don't know if you talk about array of unsaved models, or array of arrays. If array of arrays you will have to create column override helper for each column to return an element of array
https://github.com/activescaffold/active_scaffold/wiki/Column-Overrides-%28List%29

I never did something like that but it could be doable, maybe you need to setup some more instance variables or override other methods or helpers

**Comment by deep021985** [comment]
There is complected logic behind every report, so is it good idea to write entire code in helper?
 I want to avoid saving report data in model. In other words can I use array as a Model to AS.

I am currently getting result using the following code

def emp_asset_summary(location_ids)		
		ActiveRecord::Base.connection.execute("TRUNCATE reports") #Empty the report table first
		emps = MsetclUser.where("location_id in (?)", location_ids)
		emps.each do |emp|
			total = desktops = laptops = tabs = mobiles = printers = data_cards = 0 #initialize all assets 
			#########here is queries & logic part ##############

			total = desktops + laptops + tabs + mobiles + printers + data_cards		   
				report = Report.new do |r|
					r.text_field1 = emp.emp_name
					r.text_field2 = desktops
					r.text_field3 = laptops
					r.text_field4 = tabs
					r.text_field5 = mobiles
					r.text_field6 = printers
					r.text_field7 = data_cards
					r.text_field8 = total
				end
			report.save		
		end     
end

**Comment by scambra** [comment]
You can try replacing do_list method in controller and use a code like that:

```ruby
def do_list
                # get location_ids from params or whatever logic applied here
		emps = MsetclUser.where("location_id in (?)", location_ids)
		@records = emps.map do |emp|
			total = desktops = laptops = tabs = mobiles = printers = data_cards = 0 #initialize all assets 
			#some queries & logic goes here
			total = desktops + laptops + tabs + mobiles + printers + data_cards		   
				Report.new do |r|
					r.text_field1 = emp.emp_name
					r.text_field2 = desktops
					r.text_field3 = laptops
					r.text_field4 = tabs
					r.text_field5 = mobiles
					r.text_field6 = printers
					r.text_field7 = data_cards
					r.text_field8 = total
				end	
		end
                @page = Paginator.new(@records.size, @records.size) { @records }.page(1)
end
```

**Comment by deep021985** [comment]
Thanks....It works like charm!! 
Only problem is with pagination. Report shows all rows on single page.
I tried
`active_scaffold_config.list.per_page =  20
& 
@page = Paginator.new(@records.size, @records.size) { @records }.per_page(20)
`
but still pagination not working...

**Comment by scambra** [comment]
First argument to Paginator initializer is total count, second is items per page, you can use:

@page = Paginator.new(@records.size, active_scaffold_config.list.per_page) { @records }.page(active_scaffold_config.list.user.page)

It will do pagination, although you are generating all report records for every request, and then displaying requested page

**Comment by deep021985** [comment]
Thanks scambra but paginator still not working...
I also tried passing hard codded value to Paginator second argument but again all rows displayed on same page. 
`@page = Paginator.new(@records.size, 20) { @records }.page(active_scaffold_config.list.user.page)`

Am I missing something?

**Comment by scambra** [comment]
Yes, I copied from an example which didn't use pagination and adapt it, but it wasn't enough:

```ruby
emps = MsetclUser.where("location_id in (?)", location_ids)
		@all_records = emps.map do |emp|
			total = desktops = laptops = tabs = mobiles = printers = data_cards = 0 #initialize all assets 
			#some queries & logic goes here
			total = desktops + laptops + tabs + mobiles + printers + data_cards		   
				Report.new do |r|
					r.text_field1 = emp.emp_name
					r.text_field2 = desktops
					r.text_field3 = laptops
					r.text_field4 = tabs
					r.text_field5 = mobiles
					r.text_field6 = printers
					r.text_field7 = data_cards
					r.text_field8 = total
				end	
		end
@page = Paginator.new(@all_records.size, 20) do |offset, per_page|
  @all_records[offset, per_page]
end.page(active_scaffold_config.list.user.page)
@records = @page.items
```
Block must return page objects, it gets offset as first argument and per_page as second argument. Finally, set @records to @page.items

**Comment by deep021985** [comment]
Its working 👍 ..Thank you so much..
