### ISSUE TITLE
@record in subform partial override is pointing to parent object

### ISSUE THREAD

**Issue by philipkobernik** [activescaffold/active_scaffold#594]
Hello,

I am using a partial to override a subform column to display a custom column.

User has_many licenses

Users controller:
`config.update.columns = [:name, :licenses] `

Licenses controller:
`config.update.columns = [:user, :registration_key_display]`

My partial is named `_registration_key_display_form_column.html.erb` and lives in `views/admin/licenses/` as specified in the docs.

Now my partial invokes `@record.registration_key_display`, trying to call a method on the License model. However, it seems `@record` is pointing to the `User` model, and not the subform `has_many` associated model, `License`.

This problem started happening when I upgraded from 3.4.20 to 3.5.1

Thanks for your attention and investment in this excellent project.

-Philip

**Comment by scambra** [comment]
You must use record local variable instead of @record instance variable. @record is not changed anymore because it was a bad idea, so it's always main form's record, but record local variable has been available for long time.
