### ISSUE TITLE
Saving fields of type :text are failing with Rails 5.2

### ISSUE THREAD

**Issue by dianaq12** [activescaffold/active_scaffold#601]
I just upgraded my app using ActiveScaffold from Rails 4.2 to Rails 5.2 and now all fields of type :text are failing to save.  I'm using ActiveScaffold version 3.5.2.   After some research I found this explanation: https://github.com/rails/rails/pull/26696

After looking through the ActiveScaffold code I replaced the type lookup happening with ActiveModel to ActiveRecord in:
- ../lib/active_scaffold/attribute_params.rb:326
- ../lib/active_scaffold/core.rb:240

Once I did that I was able to save records that included changes to :text type fields.

Here is the backtrace for your reference:
ArgumentError - Unknown type :text:
  activemodel (5.2.0) lib/active_model/type/registry.rb:22:in `lookup'
  activemodel (5.2.0) lib/active_model/type.rb:33:in `lookup'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:319:in `column_default_value'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:296:in `block in attributes_hash_is_empty?'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:283:in `each'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:283:in `all?'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:283:in `attributes_hash_is_empty?'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:239:in `build_record_from_params?'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:223:in `manage_nested_record_from_params'
   () usr/local/rvm/gems/ruby-2.3.1/bundler/gems/active_scaffold-211a273c142a/lib/active_scaffold/attribute_params.rb:216:in `block in column_value_from_param_hash_value'
...

**Comment by scambra** [comment]
Can you send a pull request? You will get credit and it's easier to me to check if some test fails with older rails versions

**Comment by dianaq12** [comment]
OK created pull request.  All tests pass with the changes I made.  This is the first time I've created a pull request so please let me know if there is anything else I should have done.

**Comment by scambra** [comment]
Pull request is good, thanks
Closed with #602

**Comment by scambra** [comment]
I see you are using 3.5.2, 3.5.x version doesn't support rails 5.2, indeed some issue has been fixed in master branch. This was a issue with 5.1 too, because Text ActiveModel::Type was moved to ActiveRecord::Type with 5.1.0
