### ISSUE TITLE
None of the crud templates are shown in browser

### ISSUE THREAD

**Issue by Atastor** [activescaffold/active_scaffold#604]
My settings:
- rails 5.2.1
- ruby 2.5.1
- as current master
- chrome current
- safari current
- project only contains 1 model so far

None of the crud templates are shown inserted inline in the browser. No errors are shown in chrome dev-tools or the safari pendant.

I see that the correct html-content is send to the browser, but it is not inserted inline. If I right-click on the buttons (edit, create, show) and "open in new tab" or "...new window" it DOES show.

Is this a current known as-problem or a rails problem or is it a dumb config error by me (which I usually DO spot after a while)?

**Comment by scambra** [comment]
Can you add breakpoint at this line of active_scaffold.js?
https://github.com/activescaffold/active_scaffold/blob/master/app/assets/javascripts/jquery/active_scaffold.js#L89

That event handler should be triggered when ajax request is done.
What is jquery version? jQuery().jquery in dev tools console

**Comment by Atastor** [comment]
Even if I switch explicitly to jquery3 in assets and get a "3.3.1" as jquery version the behaviour does not change.

**Comment by scambra** [comment]
Can you advance one step and check what value action_link variable has?

**Comment by Atastor** [comment]
Sorry for the delay!

Any attribute you are especially interested? 

![bildschirmfoto 2018-10-23 um 14 06 49](https://user-images.githubusercontent.com/21538/47359401-f19beb80-d6cc-11e8-9ca9-1febdf40611e.png)

**Comment by Atastor** [comment]
Btw: this works (not) even for the startup example given in the introduction, i.e. with a bare new project .

**Comment by scambra** [comment]
I was interested in action_link variable, it will defined when you step over to line 90. I wanted to ensure action_link is not undefined, position property is top and target property is tbody with class before-header. When action_link is defined, and position is top, html from response will be prepended into target property, on insert method called from line 92.

**Comment by Atastor** [comment]
Looks as if it is, or?

![bildschirmfoto 2018-10-23 um 16 39 26](https://user-images.githubusercontent.com/21538/47368663-5746a280-d6e2-11e8-8991-85d7218a9ed0.png)

**Comment by scambra** [comment]
Yes, but everything looks right, I will have to setup rails 5.2 app and debug it

**Comment by eivindm** [comment]
After some more debugging I found another clue: If I removed the require of the rails-ujs javascript, it now works. If the rails-ujs was required before the jquery and jquery-ujs it does not work at all. If I include it after jquery, it does work, with gives an error message and does two XHR call where one fails, but the other works. So there seems to be a conflict of jquery/jquery-ujs and rails-ujs.

**Comment by Atastor** [comment]
Interesting! But wouldn't that mean, that the error is independent of AS? *THINK*

I try to check later.

**Comment by scambra** [comment]
Thanks @eivindm I have tested with rails 5.1, rails-ujs and jquery (only one ujs should be used), and action_link had value, but response (or content in insert funciton) was undefined, same happened with 5.2

I replaced rails-ujs with jquery_ujs and I got value on response, everything worked.

It looks like rails-ujs doesn't provide response variable on events, they are in event.detail:
https://guides.rubyonrails.org/working_with_javascript_in_rails.html#rails-ujs-event-handlers

I should add instructions regarding rails 5.1 and 5.2 require jquery and jquery_ujs, and remove rails-ujs. Although
