### ISSUE TITLE
AS: Mutiple checkboxes on same row

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#606]
How to display multiple checkboxes on same row.
e.g.

> Group Title  column1 chkebox1 column2 checkbox2  column3  checkbox3

> 

currently with 

> config.columns[:column1].form_ui = :checkbox 
config.columns[:column2].form_ui = :checkbox 
config.columns[:column13].form_ui = :checkbox 

> 

each checkbox is displaying on new line.

**Comment by scambra** [comment]
Add some css to change layout for those columns, for example you may use selector li.form-element.checkbox

**Comment by deep021985** [comment]
Please tell me the name of CSS file where I can make the changes..

**Comment by scambra** [comment]
Any CSS on your app, gem files are not supposed to be changed. Check rails asset pipeline doc: https://guides.rubyonrails.org/asset_pipeline.html#controller-specific-assets

You can add new require line into your application.css manifest, below lines requiring activescaffold files, and add your css rules in that new file.
