### ISSUE TITLE
Activestorage ?

### ISSUE THREAD

**Issue by gloufy** [activescaffold/active_scaffold#609]
Happy new year !!!

How is the way to integrate ActiveStorage in Activescaffold ? (In create form) 

Thank you for tips 

Gloufy :)

**Comment by DRSisco** [comment]
(Only a year later) Currently active_scaffold doesn't support ActiveStorage. I think Paperclip was still the standard go-to when you posted this though. :thinking: 

However, I recently decided to get this working, so I am in the process of writing the bridge for it. More info to come!
