### ISSUE TITLE
Full text search and AS

### ISSUE THREAD

**Issue by naaano** [activescaffold/active_scaffold#619]
Have anyone tried using PostgreSQL's full text search with active scaffold?

Thing is, that there are 2 ways of implementing this:
- writing the raw sql "where" fragment, which is in the form of `document @@ to_tsvector('what you are looking for')`, and somehow you have to specify the operator "@@" and a function for searching "to_tsvector". 

- using ruby syntax, like the one with pg_search which implements:
`Product.search("bottle")` but I don't know how I could bind this method to the active_scaffold search mechanism.

any ideas?

**Comment by scambra** [comment]
If you want to replace current search query with Product.search(params[:search]), you may try overriding both do_search and beginning_of_chain, so do_search does nothing.

```ruby
def do_search
end

def beginning_of_chain
  if search_params.is_a?(String) && search_params.present?
    @filtered = true
    super.search(search_params)
  else
    super
  end
end
```
