### ISSUE TITLE
No route matches  action=>"show_search"

### ISSUE THREAD

**Issue by silambarasanmkce** [activescaffold/active_scaffold#621]
Showing /Users/silambarasan/granville-station-web/.bundle/ruby/2.6.0/gems/active_scaffold-3.5.2/app/views/active_scaffold_overrides/_list_header.html.erb

No route matches {:action=>"show_search", :controller=>"admin/users"}

**Comment by scambra** [comment]
I guess it's related to #620 because you don't have AS routes added
