### ISSUE TITLE
scaffold very slow to load (number of columns issue?)

### ISSUE THREAD

**Issue by lucidthoughts** [activescaffold/active_scaffold#636]
Hi Sergio,
Thank you for the excellent gem. I've run into an issue where it's very slow to load the active scaffold. I've tried using 3.4 and 3.5 branches, but the problem remains the same. I've tried to isolate the issue (e.g. disabling layout, reducing the number of columns shown), but there is no change in the behavior. As a test case, I have an environment with three entries in my database, with no luck. I'm using ruby 2.2.2 and rails 4.

Here is the relevant log:

> 
> [I, [2020-06-04T09:15:19.954458 #32713]  INFO -- : Started GET "/admin/review_cases" for 80.22.233.122 at 2020-06-04 09:15:19 +0000
> D, [2020-06-04T09:15:19.957062 #32713] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
> I, [2020-06-04T09:15:19.958746 #32713]  INFO -- : Processing by AdminController#review_cases as HTML
> I, [2020-06-04T09:16:04.628743 #32713]  INFO -- :   Rendered admin/review_cases.html.erb (44668.7ms)
> I, [2020-06-04T09:16:04.629740 #32713]  INFO -- : Completed 200 OK in 44671ms (Views: 44670.1ms | ActiveRecord: 0.0ms)](url)

```
Here is my controller:
class Admin::CasesController < AdminController
  active_scaffold :case do |config|
    config.actions.exclude :create
    config.columns = [:id, :updated_at , :created_at]
    config.label = 'Responses'
  end
end
```
And my view:

```
<h1>Review cases</h1>

<%= render active_scaffold: "admin/survey_responses"%>
```

The key here is likely that my case model has 278 columns. However, as shown above, the problem persists regardless of how many columns I'm actually showing. Is there anything that I'm doing wrong? I haven't had this issue in other systems, so I guess it must be related to the total number of columns for the model? The application behaves completely normally otherwise (i.e. outside of AS).

Thanks for any help and again for your work on this gem!

**Comment by scambra** [comment]
I don't see query to load your model in the log. Can you try loading that model in rails console, same number of records? Is it slow too? Loading many records, with many columns, or big TEXT columns, may be slow in rails, because it has to load lots of data into memory. You can load only the columns you need if you enable auto_select_columns for list action. If you have some helper override for a column, which reads other columns, or an authorize_for_* method which needs other columns, you can setup needed columns:

```ruby
    config.list.auto_select_columns = true
    config.columns[:data].select_columns = [:data, :some_other_column] # these columns will be loaded if data column is in config.list.columns
    config.columns[:id].select_columns = [:id, :other_column] # these coumns are loaded always
```

**Comment by lucidthoughts** [comment]
Hi Sergio,
Thanks for the quick response!

Here is the output in the console:

```
2.2.2 :001 > Case.all.each{|s| puts s.created_at} ; 1
  Case Load (2.6ms)  SELECT "cases".* FROM "cases"
2020-05-22 17:10:39 UTC
2020-05-22 18:05:48 UTC
2020-05-22 18:33:24 UTC
 => 1 
```
So it doesn't seem to be an issue with loading the data from the DB. The same overall delay of about 40 seconds for the scaffold to load happens with 3 cases (as above) or with 250 cases. 
There are a couple of text columns and a couple of string columns, but the vast majority are integers.

Thanks for any additional insight!

**Comment by scambra** [comment]
I guess you get that output quick, although it would be better to see that use something like this:

```ruby
Benchmark.bm { |b| b.report { Case.all.to_a } }
```

I would need a full log for the request, because I don't see case loading, or request for embedded scaffold. I didn't realize before, but review_cases action doesn't load any case model, it isn't list for cases, it's a custom action with an embedded scaffold for different model. Are you using render_component to load embedded scaffold in same request? Or is embedded scaffold loaded by AJAX? I guess if you remove render active_scaffold line from the view, action is fast.

**Comment by lucidthoughts** [comment]
Hi again,
Here is that output:

 Benchmark.bm { |b| b.report { Case.all.to_a } }
       user     system      total        real
   Case Load (2.4ms)  SELECT "cases".* FROM "cases"
  0.000000   0.000000   0.000000 (  0.004786)
 => [#<Benchmark::Tms:0x000000069ed170 @label="", @real=0.004786334931850433, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0>] 

This is in a fresh console without anything cached.

This is the full log:


```
I, [2020-06-04T11:47:51.136059 #2377]  INFO -- : Started GET "/admin/review_cases" for 80.22.233.122 at 2020-06-04 11:47:51 +0000
D, [2020-06-04T11:47:51.138632 #2377] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 3]]
I, [2020-06-04T11:47:51.140175 #2377]  INFO -- : Processing by AdminController#review_cases as HTML
I, [2020-06-04T11:48:28.948783 #2377]  INFO -- :   Rendered admin/review_cases.html.erb within layouts/application (37806.9ms)
I, [2020-06-04T11:48:28.950620 #2377]  INFO -- :   Rendered cases/_consent_text.html.erb (0.1ms)
I, [2020-06-04T11:48:28.951258 #2377]  INFO -- : Completed 200 OK in 37811ms (Views: 37810.4ms | ActiveRecord: 0.0ms)
I, [2020-06-04T11:48:29.463042 #2377]  INFO -- : Started GET "/admin/cases?eid=1781be998f739d216a59be3039298765&embedded%5Bloading%5D=true" for 80.22.233.122 at 2020-06-04 11:48:29 +0000
I, [2020-06-04T11:48:29.467330 #2377]  INFO -- : Processing by Admin::CasesController#index as HTML
I, [2020-06-04T11:48:29.467680 #2377]  INFO -- :   Parameters: {"eid"=>"1781be998f739d216a59be3039298765", "embedded"=>{"loading"=>"true"}}
D, [2020-06-04T11:48:29.470503 #2377] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 3]]
D, [2020-06-04T11:48:29.528411 #2377] DEBUG -- :    (0.3ms)  SELECT COUNT(*) FROM "cases"
I, [2020-06-04T11:48:29.547331 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_header.html.erb (4.0ms)
I, [2020-06-04T11:48:29.734379 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_column_headings.html.erb (181.6ms)
I, [2020-06-04T11:48:29.743071 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_messages.html.erb (0.9ms)
I, [2020-06-04T11:48:29.744367 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_messages.html.erb (6.8ms)
D, [2020-06-04T11:48:29.749234 #2377] DEBUG -- :   Case Load (1.9ms)  SELECT  "cases".* FROM "cases"  ORDER BY "cases"."id" ASC LIMIT 15 OFFSET 0
D, [2020-06-04T11:48:29.762513 #2377] DEBUG -- :   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
D, [2020-06-04T11:48:29.766677 #2377] DEBUG -- :   Site Load (0.2ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."id" = ? LIMIT 1  [["id", 1]]
D, [2020-06-04T11:48:29.899392 #2377] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 2]]
D, [2020-06-04T11:48:29.900480 #2377] DEBUG -- :   CACHE (0.0ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."id" = ? LIMIT 1  [["id", 1]]
D, [2020-06-04T11:48:29.977438 #2377] DEBUG -- :   CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 2]]
D, [2020-06-04T11:48:29.978545 #2377] DEBUG -- :   CACHE (0.0ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."id" = ? LIMIT 1  [["id", 1]]
I, [2020-06-04T11:48:30.035158 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_record.html.erb (282.2ms)
I, [2020-06-04T11:48:30.039530 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_pagination.html.erb (1.6ms)
I, [2020-06-04T11:48:30.039897 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list.html.erb (490.3ms)
I, [2020-06-04T11:48:30.040790 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/_list_with_header.html.erb (500.7ms)
I, [2020-06-04T11:48:30.041065 #2377]  INFO -- :   Rendered /home/survey/.rvm/gems/ruby-2.2.2/bundler/gems/active_scaffold-381cb0fea0f3/app/views/active_scaffold_overrides/list.html.erb (503.4ms)
I, [2020-06-04T11:48:30.041832 #2377]  INFO -- : Completed 200 OK in 574ms (Views: 508.9ms | ActiveRecord: 3.4ms)

```

The current set up is relatively simple in that there is an admin-specific view (i.e. admin/review_cases.html.erb) which has the view code that I put in the first post. 

The admin/cases_controller.rb has the code that I showed in the first post.

Have I missed something obvious or doing something wrong that I overlooked? Thanks again!

**Comment by scambra** [comment]
review_cases is not an ActiveScaffold's action, and the view only has render active_scaffold: "admin/survey_responses", which it should only render some divs, with an h2, a link and an image. It shouldn't take so long. Please, check removing that line action is not slow. Also, you can test adding label option to render call, so helper doesn't call active_scaffold_config_for(model).list.label.

Also, you can define render method in your helper, adding some debug lines to debug why it's slow:

```ruby
  def render(*args, &block)
    if args.first.is_a?(Hash) && args.first[:active_scaffold]
      time = Time.now.to_i
      options = args.first
      require 'digest/md5'

      remote_controller = options[:active_scaffold]
      # It is important that the EID hash remains short as to not contribute
      # to a large session size and thus a possible cookie overflow exception
      # when using rails CookieStore or EncryptedCookieStore. For example,
      # when rendering many embedded scaffolds with constraints or conditions
      # on a single page.
      eid = Digest::MD5.hexdigest(params[:controller] + options.to_s)
      eid_info = {loading: true}
      eid_info[:constraints] = options[:constraints] if options[:constraints]
      eid_info[:conditions] = options[:conditions] if options[:conditions]
      eid_info[:label] = options[:label] if options[:label]
      options[:params] ||= {}
      options[:params].merge! :eid => eid, :embedded => eid_info
      logger.debug "RENDER EMBEDDED: setup options #{Time.now.to_i - time}"

      id = "as_#{eid}-embedded"
      url_options = {controller: remote_controller.to_s, action: 'index', id: nil}.merge(options[:params])

      if controller.respond_to?(:render_component_into_view, true) && !options[:xhr]
        controller.send(:render_component_into_view, url_options)
      else
        url = url_for(url_options)
        logger.debug "RENDER EMBEDDED: setup url #{Time.now.to_i - time}"
        content_tag(:div, :id => id, :class => 'active-scaffold-component', :data => {:refresh => url}) do
          # parse the ActiveRecord model name from the controller path, which
          # might be a namespaced controller (e.g., 'admin/admins')
          model = remote_controller.to_s.sub(%r{.*/}, '').singularize
          logger.debug "RENDER EMBEDDED: got model #{Time.now.to_i - time}"
          content_tag(:div, :class => 'active-scaffold-header') do
            content_tag(:h2) do
              link_label = options[:label] || active_scaffold_config_for(model).list.label
              logger.debug "RENDER EMBEDDED: got label #{Time.now.to_i - time}"
              link_to(link_label, url, remote: true, class: 'load-embedded', data: {error_msg: as_(:error_500)}) <<
                loading_indicator_tag(url_options)
            end
          end
        end.tap do
          logger.debug "RENDER EMBEDDED: rendered #{Time.now.to_i - time}"
        end
      end
    else
      super
    end
  end
```

**Comment by lucidthoughts** [comment]
Hi Sergio,
Thank you so much! It was indeed the label that was causing the issue:

```
D, [2020-06-04T14:51:13.599793 #16149] DEBUG -- : RENDER EMBEDDED: setup options 0
D, [2020-06-04T14:51:13.603153 #16149] DEBUG -- : RENDER EMBEDDED: setup url 0
D, [2020-06-04T14:51:13.604364 #16149] DEBUG -- : RENDER EMBEDDED: got model 0
D, [2020-06-04T14:51:51.198598 #16149] DEBUG -- : RENDER EMBEDDED: got label 38
```

As you suggested, passing the label to the render call solves the issue completely and there is no slowness anymore. So thank you so much for your help!

**Comment by scambra** [comment]
I guess active_scaffold_config_for(model) is taking too long, although I don't know what can cause that.
