### ISSUE TITLE
list sort not working as expected

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#639]
I tried to sort my list using controller methods

active_scaffold do |config|
    list.columns = [:id, :tdn_number, :rev, :is_latest, :title, :clin, :discipline ]
    list.sorting = [{ :tdn_number => :asc}, {:rev => :asc}]
    config.list.sorting = [{ :tdn_number => :asc}, {:rev => :asc}]
end

Neither of the above work.  I can see the order by is not getting injected in the sql.

** However, customer finder options works fine **
  def custom_finder_options
    {:reorder => "tdn_number DESC, rev ASC "}
  end

Questions.  
1.  Is this a bug.  
2. In the config block, is config.list.sorting or list.sorting correct, or do both work?
3.  How can I check (with a puts statement) the controller variables being setup by AS?
4.  Once a sort is set by clicking on the column header, how can it be removed so the default sort returns?  Possible to add a "clear sort" action link at the top of the table?

Thank you!

Thanks

**Comment by scambra** [comment]
1. It may be a bug, tell me used versions, ruby, rails and activescaffold
2. I think both work, but I always use config variable (config.list.columns, config.list.sorting, ...)
3. You can get config with active_scaffold_config, for example active_scaffold_config.list.sorting gives you Sorting data structure, sorting.clause must give you SQL code, sorting.sorts_on? column_name checks if it's sorting by a column.
4. Click on column header set ASC sorting, click again changes to DESC, click again change to default sorting.

Also, you can check if your columns are sortable, for example in rails console:
YourController.active_scaffold_config.columns[:tdn_number].sortable?
YourController.active_scaffold_config.columns[:tdn_number].sort

**Comment by dennisbulgatz** [comment]
Thanks for the feedback above.  I think that some sort info was stored in the session, and once I destroyed (logged out) and logged back in, all worked correctly.  But the debug info provided above is very useful!!
