### ISSUE TITLE
Can DatePicker included with AS be used in standard .erb views?

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#640]
Not an issue, just a question.  Can I use the AS Datepicker in a stardard erb edit form?  Any example you could point me too?  Currently, using:

App was using gem 'bootstrap-datepicker-rails' but this seem bad form to have two Datepicker styles in one app.

	<%= f.date_select :pop_begin, include_blank: true %> 

Thanks for any help with this.

**Comment by scambra** [comment]
Yes, you can, it's jquery datepicker, you only have to render a text_field with date_picker class. ActiveScaffold's helper is in active_scaffold/bridges/date_picker/helper.rb

You can add data- attributes with options for jquery datepicker. ActiveScaffold use some data- attributes with dateFormat and timeFormat options, you can check data- attributes added by ActiveScaffold with web inspector, any options allowed by jquery datepicker should work with data- attribute (https://api.jqueryui.com/datepicker/)
