### ISSUE TITLE
is it possible to use AS datepicker in standard form_for helper

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#641]
Can I use the activescaffold datepicker with the form_for helper in rails?  If so, what are the steps?

f.datepicker :some_date_column, :allow_blank => true  ...  ?

Hate to add an unnecessary gem.

Thank you!

**Comment by scambra** [comment]
I already answered on #640 

There is no AS datepicker, it's a javascript datepicker from jquery UI. Anyway, that datepicker used by AS can be used with form_for rendering a text_field with date_picker class (f.text_field :column, class: 'date_picker'), and you may want to add some other data- attributes
