### ISSUE TITLE
How to do a site Search Across controllers and Columns?

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold#643]
Is there a gem, or suggested approach, to implement a site wide search, across controllers and columns?

I had in mind to use after_save callbacks on each model to concatenate all the columns into a single text string, and then save that string into a separate database table with a schema like:

CREATE TABLE `search_strings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `searchable_text` text DEFAULT NULL,
  `source_table_name` varchar(255) DEFAULT NULL,
  `source_record_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

The search_strings Active Scaffold search would then only have to search the "searchable_text" column to find any record in the db, and would be easy enough to generate at link to the item.

This would not be tough to implement, and the after_save callback would allow full control of what gets concatenated.

Thoughts?

**Comment by scambra** [comment]
I'm not sure how helpful is ActiveScaffold for this, maybe you don't need ActiveScaffold in that controller. Probably the only useful is search action, which tokenize string to search so then it looks for records which have all words.

However, it could be better to use some other full text search engines than using new mysql model, they can have better features, although they may need to run some other process such as solr, elasticsearch or sphinx:
https://github.com/sunspot/sunspot
https://github.com/ankane/searchkick
https://github.com/pat/thinking-sphinx

At least thinking sphinx has application wide searching, I don't know if sunspot or searchkick have it

**Comment by scambra** [comment]
This kind of questions can be better asked in google group, so other people may see your question and answer (alhtough it's not a very active group):
https://groups.google.com/forum/#!forum/activescaffold

**Comment by dennisbulgatz** [comment]
Thank you. I will use the forum!
