### ISSUE TITLE
Issues with in-place editing for decimal numbers when using :i18n_number and :percentage for rendering

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#644]
Hello,

I have a decimal cloumn in my database - `completion_score`.

I'm using the `:ro` I18n locale. Please note that the decimal separator is comma (,) instead of the usual dot (.).

In order to correctly display the column data, I'm using:

`conf.columns[:completion_score].options[:format] = :i18n_number`

I also activated the in-place editing:

`conf.columns[:completion_score].inplace_edit = true`

Displaying the data works correctly, with comma (,) as the decimal separator.
The issue arrizes when I attempt to in-place edit the content: the textfield is empty. If I instead use the :en locale the in-place editing works correctly.

A similar issue arises if I'm formatting the data as a percentage, regardless of locale:

`conf.columns[:completion_score].options[:format] = :percentage`

I suspect a similar behaviour occurs when using `:currency` or `:size` as well but I haven't tested.

Can these issues be fixed? It seems that the browser attempts to parse the displayed string as a decimal number but fails, so it displays an empty textbox instead of the original data.

**Comment by scambra** [comment]
Please, try with inplace_edit :ajax. In some cases inplace edit field must be rendered by ruby, so true won't work and :ajax must be used.

**Comment by spatarel** [comment]
It works like a charm!
Thank you very much! I just want to say that the activescaffold project is making my life a lot easier!
