### ISSUE TITLE
Preloading/includes with ActiveStorage

### ISSUE THREAD

**Issue by DRSisco** [activescaffold/active_scaffold#645]
Looking over my usage of ActiveStorage with ActiveScaffold I realized the columns are using associations different than the name... which is totally my fault, so ActiveScaffold isn't automatically including the association for preloading. Thus n-queries. Two possible solutions off the top of my head:

Continue using the field as the column name but set the includes to the proper association. Does this have other side affects of not linking to directly to the association?
Add:
`          columns[field].includes ||= "#{field}_attachment#{'s' if field_type == :has_many}".to_sym`
in here
 https://github.com/activescaffold/active_scaffold/blob/65a1002a40857f0f72581f3cd26aff2835bb5593/lib/active_scaffold/bridges/active_storage/active_storage_bridge.rb#L23-L29

or change the name of the column itself to `"#{field}_attachment#{'s' if field_type == :has_many}".to_sym`, which would get picked up by the association detection. 

The former solution make it like other file adapters for the developer and the latter takes advantage of the detection in ActiveScaffold. 

Personally I am leaning to the former, but like a second opinion. I can also submit a PR (though I did just note all the changes here), just thought I'd make an issue first.

**Comment by scambra** [comment]
I think first option is the way to go, using field_attachment would break assigning form value to model, so some methods would be needed in the controller to fix it. Probably link to association is not needed, if you haven't seen any issue, but it could be set with this line

```columns[field].instance_variable_set(:@association, Association::ActiveRecord.new(model.reflect_on_association("#{field}_attachment#{'s' if field_type == :has_many}"))```

That line would require to add model as argument to configure_active_storage_field. Anyway, it's probably not needed

**Comment by scambra** [comment]
fixed in 5f425c51
