### ISSUE TITLE
Inplace update does not recompute calculation results correctly

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#648]
How to replicate:

```
conf.list.columns = [:score]
conf.columns[:score].inplace_edit = :ajax
conf.columns[:score].options[:format] = :percentage
conf.columns[:score].calculate = :sum
```

Have at least two rows inserted in the table, with non-zero score values. Try to update one of the rows using the inplace update.

**Expected behaviour:** Recomputing the sum correctly.

**Actual behaviour:** The sum is equal to the newly updated value, ignoring the other row(s) in the table.

Why is this happening?

```
# active_scaffold/lib/active_scaffold/finder.rb
def all_conditions
  [
    id_condition,                                 # for list with id (e.g. /users/:id/index)
    ...

def calculate_query
  conditions = all_conditions
  ...
```

How to fix it?
Option 1: `calculate_query` should call another function like: `all_conditions_except_id` instead of `all_conditions`
Option 2: set `param[:id] = nil` before calling `render_column_calculation` in `active_scaffold/app/views/active_scaffold_overrides/update_column.js.erb`

Option 1 is what I would do. Option 2 is just a quick ugly fix, that doesn't actually solve the underlying problem and could raise other issues in the future. Or perhaps there is a third, better way - I'm not familiar with the codebase so I really don't know how to properly fix this issue.

**Comment by scambra** [comment]
At first view, calculate_query ignoring id could be right, but it's possible to use id with list action, with one value or list of values, I use that for one project, and I understand calculation on those listings must use id condition.

So id condition should be ignored only when called from update_column view. Inplace edit a column on a listing loaded with id param wouldn't work, but that's a really weird case, hard to fix, which probably should be fixed with custom code in app.

Can you try branch issue-648? Also, you can try if index with ?id= or ?id[]=X&id[]=Y still works

**Comment by spatarel** [comment]
From my point of view, now it works properly. Thank you!

However, when viewing a table, if I add `"&id=2"` as parameter by hand, then the inplace update will ignore that parameter and compute wrong results.

In order to fix this, there should be a distinction made between `id` parameter as in filter the results by some specified id and `id` parameter as in updated row id. But this approach would require many changes.

All in all I don't think this is worth the trouble, unless you need to do something like search and filter by id, then compute the sum over a single row (what's the point?), then do an inplace update.

**Comment by scambra** [comment]
Yes, that's what I said, inplace_edit with calculation won't work correctly if list view is loaded with id param, as calculation will be done without id param, but it's not easy to fix, and it's a rare edge case. Indeed, it could be worst and harder if id param in list view is an array.
