### ISSUE TITLE
"Search" form shows a `script` element which has "display: block" style.

### ISSUE THREAD

**Issue by gregschmit** [activescaffold/active_scaffold#653]
On a fairly recent master (`810e1fe4d1b6`), when I click the "Search" box to show the search form, a `script` element inside gets `display: block` style, showing this:

![image](https://user-images.githubusercontent.com/14255284/97371484-4b68ba80-187f-11eb-99af-c32f08868ca5.png)

I did a traceback in Chrome after setting a breakpoint, and `active_scaffold.js` line 923 seems to be in the causal chain (when I comment it out, the script element doesn't get shown).

```
element.effect("highlight", jQuery.extend({}, ActiveScaffold.config.highlight), 3000);
```

**Comment by gregschmit** [comment]
`active_scaffold.js`:1467 also is in the traceback which may be where this can be fixed:

```
ActiveScaffold.highlight(this.adapter.find('td').first().children());
```

**Comment by gregschmit** [comment]
Yeah, by changing that line to:

```
ActiveScaffold.highlight(this.adapter.find('td').first().children().not('script'));
```

That fixes this issue. Do you want me to submit a PR? Or would you prefer this issue be resolved in another way?

**Comment by scambra** [comment]
I don't think anything related has been changed recently. Another way would be add .not('script') to highlight function, line 923, changing to element.not('script').effect, but your fix may be ok, I think it's the only line which may call highlight with a script tag.

**Comment by gregschmit** [comment]
Well, if you run active scaffold and you click the "Search" button, do you see what I see?

**Comment by scambra** [comment]
No, I don't, but I have empty jquery-ui effects in current project, I think I have some old jquery-ui gem
This issue may be there for long time, or start happenning with newer jquery-ui versions, I don't know if they changed something. If I manually change display of script tag to block, I can see what you say, so it must be good to add .not('script')
