### ISSUE TITLE
setting tab index on search forms

### ISSUE THREAD

**Issue by hjw** [activescaffold/active_scaffold#655]
Is there a way to remove the "contains, begins with, etc" drop downs from the tab order on a search form? I am having trouble figuring this out. 99% of the time the user wants the default setting (contains) for the drop down so I'd like <tab> to move to the next record field, skipping over the drop down.

**Comment by scambra** [comment]
There is no way right now. Drop down is rendered in this line:
https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/helpers/search_column_helpers.rb#L214

Select_tag is just called with only id and class options, there is no hash passed to select_tag. You could copy that method to your helper and add tabindex: -1, or you can add some JS to trigger when form is loaded to change tabindex on .as_search_range_option elements

```js
$(document).on('as:action_success', 'a.as_action', function(e, l){
  $('.as_search_range_option', l.adapter).attr('tabindex', -1);
});
```

**Comment by hjw** [comment]
Thanks. I think that I am doing something dumb... probably because I haven't used ruby / rails for ten years: 

- I copied the whole search_column_helpers.rb file from the gem into my **app/helpers/ directory**, 
- made the change (added :tabindex => '-1' in after :class =>  'as_search_range_option') 

and everything worked. But then I asked myself why I was duplicating the whole file from your gem, reread your comment and removed all of the other defs from that file, so it now looks like this:
``` ruby
module ActiveScaffold
    module Helpers
       module SearchColumnHelpers
         def active_scaffold_search_range
           <...>
         end
      end
   end
end
```
Unfortunately, now, things stopped working / the drop downs are back in the tab order.
I must be missing something about how to override the method / where to put that file. I'd prefer to make the mod this way, rather then with javascript... if at all possible. Can you set me straight on where I've gone wrong?

**Comment by scambra** [comment]
Copy method into your ApplicationHelper, don't define ActiveScaffold::Helpers::SearchColumnHelpers in app/helpers, because module from gem won't be loaded

**Comment by hjw** [comment]
hmmn, putting 
```
def active_scaffold_search_range
        <...>
        html = select_tag("#{options[:name]}[opt]", options_for_select(select_options, opt_value),                                                                                                                                
                          :id => "#{options[:id]}_opt", :class => 'as_search_range_option', :tabindex => '-1' )  
       <...>
         end
```
into helpers/application_helper.rb didn't work, I get the standard tab behavior. Does doing that actually work for you? Is the problem that this legacy project that I'm working on is running rails 4.2.10?

**Comment by hjw** [comment]
I found that part of the problem was that the active_scaffold_search_range was being aliased a bunch of times. 
I was able to override the method by adding it to config/initializers/active_scaffold.rb and including the various alias lines.
Sorry for taking up your time and thanks for your help
