### ISSUE TITLE
All fields are showing up after upgrading 

### ISSUE THREAD

**Issue by tfantina** [activescaffold/active_scaffold#667]
I'm in the process of moving a legacy Rails 3 project to Rails 6.
After moving from Rails 3.2 to Rails 4.2 and ActiveScaffold 3.3.3 to ActiveScaffold 3.6.0 one of my search forms is now showing all form fields. Previously we were showing about 10 different fields for search criteria, now it is showing about 30.

What's more the config inside this specific controller no longer seems to work (other controllers are fine).  For example adding or removing `config.columns` does not impact what is showing for the search action.

I'm almost positive this is an issue with my codebase and not ActiveScaffold, but I haven't been able to find any sort of upgrade guide and any thoughts or upgrade gotchas would be much appreciated. 

Thanks for all the work on the gem!

**Comment by scambra** [comment]
Can you post that controller? Is it inheriting from other controller?

**Comment by tfantina** [comment]
Without getting into too many details, apparently he have some custom helper called `visibles_and_hiddens` it was using a method `search_config.columns.each` which needed to be updated to `search_config.conlumns.each_column`. 

Thanks for all the support!
