### ISSUE TITLE
Inplace editing breaks down under special circumstances

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#675]
In short, I believe this line:
```
/app/assets/javascripts/jquery/active_scaffold.js:1027
column_heading = my_parent.closest('.active-scaffold').find('th:eq(' + column_no + ')');
```
should change to
```
column_heading = my_parent.closest('table').find('th:eq(' + column_no + ')');
```

Here's why:
I was implementing a new feature using active_scaffold when I needed to add an action like this:
```
conf.action_links.add :show_new_feature,
  type: :collection, crud_type: :read,
  method: :get, position: true, inline: true
```
The corresponding view would contain several ```<table>```s with some ```<th>```s each, like this:
```
<table class="table">
  <tr>
    <th><p>...</p></th>
    <th><p>...</p></th>
    <th><p>...</p></th>
    ...
  </tr>
  ...
</table>
<table class="table">
  ...
</table>
...
```
As it hapens, I also had an inplace-editable column in my table, like this one:
```
conf.columns[:date].inplace_edit = true
conf.columns[:date].options[:format] = :picker
conf.columns[:date].form_ui = :date_picker
```
Everything seemed fine until I tried using the inplace edit function, **while the new_feature was open**. Then, a JS error occured:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.in_place_editor_field_clicked
    at HTMLTableCellElement.<anonymous>
    at HTMLDocument.dispatch
    at HTMLDocument.elemData.handle
```
It turned out that there is some JS code trying to update something related to the ```<th>``` cell corresponding to the inline edited cell. However, while there are two (or more) tables inside the same ```<div class="active_scaffold">``` the current code finds the wrong ```<th>``` (one of the ```<th>```s from one of my own tables).

The fix I found was easy: look for the k-th ```<th>``` inside the closest ```<table>``` instead. However, I don't know if this might break something else...

Thank you for looking into my issue!

**Comment by scambra** [comment]
I don't think it may break anything else, the right th must be in the closest parent table
