### ISSUE TITLE
Handling for citext columns

### ISSUE THREAD

**Issue by jcrate** [activescaffold/active_scaffold#676]
I noticed this evening that `citext` columns weren't being searched automatically. Digging through the code I find this specification for text fields which will be searched automatically.

column.rb:327
`@text = @column.nil? || [:string, :text, String].include?(column_type)`

This seems to come from ActiveRecord's `type_for_attribute`. 

```
2.6.6 :009 > Campaign.type_for_attribute(:name).type
 => :citext
2.6.6 :010 > Campaign.type_for_attribute(:processor).type
 => :string
```

Seems like we could add `:citext` to the list of textual types but I'm not sure if that will cause any problems elsewhere. I'm not aware of any way in which a citext column needs to be treated different from a string or text column.

**Comment by scambra** [comment]
I think citext columns should be treated as text columns, so that line is not the only required change, I will add some notes to PR
