### ISSUE TITLE
process_action_link_action do end block does not update the collection actions

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#680]
I was adding some collection actions to my table. All was fine.
Then I added some authorization conditions to them. All was fine.
Then I started updating the variables used by the authorization conditions. And things stopped working.

The code below illustrates what I was trying to do:
(a) I'm defining two collection actions `publish_data` and `hide_data`.
(b) Both actions flip some boolean persistent data.
(c) The two actions are authorized by the same boolean persistent data.

In effect, at any given time only one action is authorized. Once one action is clicked it should disable and the other action should become enabled.

What is actually happening is the list of enabled actions is not updated together with the rest of the table.
```
class TableController < ApplicationController
  active_scaffold :table do |conf|
    conf.actions = [:list]

    conf.action_links.add :publish_data
      type: :collection, crud_type: :update,
      method: :put, position: false

    conf.action_links.add :hide_data,
      type: :collection, crud_type: :update,
      method: :put, position: false
  end

  def publish_data
    process_action_link_action do
      some_persistent_data.public!
      self.successful = true
    end
  end

  def hide_data
    process_action_link_action do
      some_persistent_data.hidden!
      self.successful = true
    end
  end

  def publish_table_authorized?
    some_persistent_data.hidden?
  end

  def hide_table_authorized?
    some_persistent_data.public?
  end
end
```

**Comment by scambra** [comment]
Try enabling list.refresh_with_header

```
conf.list.refresh_with_header = true
```

By default list only refreshes the table, but it doesn't refresh list header, where table actions are.

**Comment by spatarel** [comment]
It worked like a charm!
Thank you so much!
