### ISSUE TITLE
Secondary sorting

### ISSUE THREAD

**Issue by technorama** [activescaffold/active_scaffold#681]
Is there a setting for additional sorting when a column is clicked?

**Comment by scambra** [comment]
No, click on column heading change sorting to that column.

You can set multi-column sorting in these ways:

- as default sorting, with config.list.sorting
- in a before_action, with active_scaffold_config.list.user.sorting.set [:col1, :direction], [:col2, :direction]
- with active_scaffold_config_list, which allows to change list columns and sorting, up to 3 columns.

**Comment by scambra** [comment]
I'm open to accept a PR adding this, if code is not too complicated and don't change current way to click to change sorting, but I thinkg UX can be complicated, and [active_scaffold_config_list](https://github.com/activescaffold/active_scaffold_config_list) may be enough

**Comment by technorama** [comment]
There are at least 2 ways to implement secondary sorting:
1) `config[:column_a].sort_sql = "table.column_a, table.column_b"` Similar to secondary searching
2) `config.list.additional_sort_sql = "..."` Appended to `order()`

My use case is favors 2), however 1) seems more generic and flexible.

**Comment by technorama** [comment]
`active_scaffold_config_list` won't work for this use case.  Removing columns is not an option unless I missed a pure sorting configuration.

I have a table with a 4 part natural key [`name, subtype1, subtype2, language`] with default sorting in that order.  Clicking any
of the columns should additionally sort by the remaining columns.  Clicking a 5th column should additionally sort by the 4 named columns.
