### ISSUE TITLE
Can't get this working with rails Rails 6.1.4.7

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#682]
Is there a branch or a tag I need to add to get to the rails6 version?
I ready through the Rails 6 thread but I can't get this working. 
Really want to use this for something I am working on.
Thanks in advance!

lude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x00007fe3ea31f580 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x00007fe3ea3189d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x00007fe3ea31f440 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x00007fe3ea3189d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x00007fe3ea31f328 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x00007fe3ea3189d8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @autoload_paths=[], @eager_load_paths=[]> (NoMethodError)
        from /home/mark/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/active_scaffold-3.6.6/lib/active_scaffold/engine.rb:41:in `block in <class:Engine>'
        from /home/mark/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'

**Comment by scambra** [comment]
You can try with master branch, using github: 'activescaffold/active_scaffold' in Gemfile, but probably has same issue, as 3.6.x is supposed to work with rails 6.1

Line 41 of engine.rb has this code 

```
    initializer 'active_scaffold.assets' do
      config.assets.precompile << 'active_scaffold/indicator.gif'
    end
```

I'm not sure what's the NoMethodError, config doesn't respond to :assets or config.assets doesn't respond to precompile, because first line is not complete. When you report error, please include whole error.

**Comment by gregschmit** [comment]
FYI, I had an issue with new Rails 6.1 error object API, so I added a PR: https://github.com/activescaffold/active_scaffold/pull/692
