### ISSUE TITLE
 undefined method `set_defaults' for ActiveScaffold:Module (NoMethodError)

### ISSUE THREAD

**Issue by CCH4GITHUB** [activescaffold/active_scaffold#683]
C:\PRJ4RAILS\rnd4rails5> rails s
=> Booting Puma
=> Rails 7.0.2.3 application starting in development     
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        50: from bin/rails:4:in `<main>'
        49: from bin/rails:4:in `require'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:134:in `perform'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:134:in `tap'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:36:in `start'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        30: from config.ru:3:in `block in <main>'
        29: from config.ru:3:in `require_relative'
        28: from C:/PRJ4RAILS/rnd4rails5/config/environment.rb:5:in `<top (required)>'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        25: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        24: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        23: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        22: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:347:in `call'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:347:in `each'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        19: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
        18: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:415:in `call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `each'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:619:in `block in <class:Engine>'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:619:in `each'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:666:in `load_config_initializer'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:208:in `instrument'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:667:in `block in load_config_initializer'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:667:in `load'
C:/PRJ4RAILS/rnd4rails5/config/initializers/active_scaffold.rb:3:in `<top (required)>': undefined method `set_defaults' for ActiveScaffold:Module (NoMethodError)

**active_scaffold.rb:3**
ActiveScaffold.set_defaults do |config|
 config.ignore_columns.add [:created_at, :updated_at, :lock_version]

end

**Comment by scambra** [comment]
set_defaults was deprecated in 3.6 and deprecation will be removed in next version, so it's removed in master branch. I guess you are upgrading from 3.5 so you skipped 3.6 and lose deprecations
