### ISSUE TITLE
Want help maintaining?

### ISSUE THREAD

**Issue by gregschmit** [activescaffold/active_scaffold#693]
Hi @scambra , I'm happy to volunteer some of my time to help not just in contributing code (which I would still open PR for review) but also managing issues, getting some things closed, and tagging issues to hopefully make it easier to contribute to this project and prioritize things. I noticed, for example, that https://github.com/activescaffold/active_scaffold/issues/671 can be closed from one of my latest PRs. Would you consider making me a contributor?

**Comment by scambra** [comment]
Thank you so much, any help is needed, it's getting hard to me to maintain the project, not much time after work lately

**Comment by scambra** [comment]
I added you as contributor, let me know if you need more permissions
