### ISSUE TITLE
Error: undefined method `untaint' for "ASC":String after rails upgrade

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#702]
I am getting Error **'undefined method `untaint' for "ASC":String** on config.list and other methods. 
I have upgraded Ruby and Rails to latest version on Windows Server 2016.
Upgraded Version: **ruby 3.2.1 and Rails 7.0.4.2**.
Please tell me how to fix this issue. I don't want to downgrade Rails version now.

**Comment by gregschmit** [comment]
Can you post the full backtrace? Also, you gave us the version of Ruby and Rails, but not the version of Active Scaffold you're using. Please provide that as well.

**Comment by gregschmit** [comment]
You may just need to upgrade Active Scaffold, since I believe this commit removed the `untaint` call: https://github.com/activescaffold/active_scaffold/commit/246c7bbd511210a1ef1e1bdb8f87a5ea53649cbe

**Comment by scambra** [comment]
I guess you are using a gem release, you need to use master branch with ruby 3, until new minor version is released based on master branch, which will support ruby 3

**Comment by deep021985** [comment]
I am using gem release active_scaffold (3.6.17).

**Comment by scambra** [comment]
3.6.x won't work with ruby 3, need to use master branch

**Comment by scambra** [comment]
Use .defaults instead of .set_defaults, set_defaults was deprecated in 3.6.0, and it's removed in master branch

**Comment by deep021985** [comment]
It's working now:). Thank you very much. Now I have active_scaffold with latest version of Ruby & Rails.
