### ISSUE TITLE
Rails 6.1.x Turbo problem

### ISSUE THREAD

**Issue by jcrate** [activescaffold/active_scaffold#709]
I have a Rails 6.1.x app to which I've added Turbo (I never did use turbolinks). ActiveScaffold loads properly on Turbo-initiated requests if the entire request is handled by ActiveScaffold. However, I have a page with a search form that uses:

`<%= render(active_scaffold: 'admin/composites') %>`

When reloading the page, the scaffold is rendered, but if I am coming from another page which causes Turbo to handle the page load, the scaffold is not rendered. 

I see this
```
jQuery(document).on('turbolinks:load', function($) {
  ActiveScaffold.setup(document);
});
```
which I assume is what would handle this scenario for TurboLinks. I'll try duplicating that for `turbo:load` and see if I have any other problems with Turbo. 

They recommend removing rails-ujs when using Turbo, but it seems like they can actually co-exist and I'd rather not have to update everything in this app to switch from rails-ujs to Turbo.

**Comment by jcrate** [comment]
Just adding the Turbo events to the Turbolinks event handlers seems to be working for now. I'll do more testing and create a PR.

**Comment by scambra** [comment]
Thanks, waiting for your PR

**Comment by gregschmit** [comment]
Not sure if this helps, but I ran into this issue in a project and added a feature in turbo to disable drive by default (so you can still opt-in on certain areas of the page with the HTML tag `data-turbo="true"`):

```js
import { Turbo } from "@hotwired/turbo-rails"
Turbo.session.drive = false
```

The PR: https://github.com/hotwired/turbo/pull/196
README: https://github.com/hotwired/turbo-rails#navigate-with-turbo-drive
