### ISSUE TITLE
Rails 7.1 removes ActiveSupport::PerThreadRegistry

### ISSUE THREAD

**Issue by jcrate** [activescaffold/active_scaffold#715]
ActiveSupport::PerThreadRegistry is present in Rails 7.0.x but removed in 7.1.x. It looks like it's been deprecated since Rails 5.0, with suggestions to use thread_mattr_accessor instead. 

https://api.rubyonrails.org/v7.0.4/classes/ActiveSupport/PerThreadRegistry.html
https://api.rubyonrails.org/v7.0.4/classes/Module.html#method-i-thread_mattr_accessor

ActiveSupport::PerThreadRegistry is only used in [lib/active_scaffold/registry.rb](https://github.com/activescaffold/active_scaffold/blob/b962c59edb009b6071427dbbb587abb63af2d0a8/lib/active_scaffold/registry.rb#L3). 

I decided I didn't need ActiveScaffold in that Rails 7.1 project, I don't really view the small amount of data that way, so I don't have a test case or immediate need for now. But I figured keeping this documentation in one place might be helpful for later.

**Comment by scambra** [comment]
Thanks for letting me know, I will look how to replace it

**Comment by dgm** [comment]
It had been marked as deprecated for some time and I tried to put mattr_accessor in, but there were some non-obvious complications in the way it accesses things.

**Comment by jcrate** [comment]
Seems like you'd want `thread_mattr_accessor`, which creates thread-specific class/instance vars, which looks like what `ActiveSupport::PerThreadRegistry` was intended to do.

**Comment by dgm** [comment]
Right, I think that's what I looked at, but the complication is the use of the RequestStore gem too

**Comment by dgm** [comment]
Perhaps last time I looked, I didn't update the RequestStore gem ... but at the moment I have a possible version working ...  or at least not crashing ...  I removed `ActiveSupport::PerThreadRegistry`, changed `attr_accessor` to `thread_mattr_accessor`, and made all of the methods class methods since that's how they are actually called.   However, I'm not sure that the class methods are all thread safe.

**Comment by dgm** [comment]
And I think RequestStore is better to lean on for those?

**Comment by dgm** [comment]
I haven't had much luck trying to prove it in the test cases here, but it seems to work in my own app.   I would love a critical review.
