### ISSUE TITLE
Select mutiple not working

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#717]
I'd like to be able to select multiple options from a dropdown menu. While this functionality works when creating a new record, it doesn't display the current record during updates. Here is the code for reference.

```
	config.columns[:type_of_defect].form_ui = :select
	config.columns[:type_of_defect].options = {
	  :html_options => { :multiple => true },
	  :options => ['Insulator', 'Structure', 'Conductor', 'Earthwire', 'Jumper', 'Spacers', 'Vibration Dampers', 'Temperature', 'Span', 'Other'],
	  :selected => :type_of_defect
	}
```

I attempted to use a helper, but it only displayed a regular dropdown menu. The "multiple" attribute set to "true" didn't seem to work as expected.
```
def type_of_defect_form_column(record, type_of_defect)
  type_of_defect_array = ['Insulator', 'Structure', 'Conductor', 'Earthwire', 'Jumper', 'Spacers', 'Vibration Dampers', 'Temperature', 'Span', 'Other']
select(:record, :type_of_defect, type_of_defect_array,  {:multiple => true, :size =>10})
end
```

**Comment by scambra** [comment]
Are you sure is saving correctly? What field is that can save multiple values?
Have you tried removing :selected from the config.columns[:type_of_defect].options? I don't think it's needed.

Regarding the helper, I think you are passing `{:multiple => true, :size =>10}` in the wrong argument, the method signature is `select(object, method, choices = nil, options = {}, html_options = {}, &block)`, so you are passing multiple and size in options hash instead of html_options hash.

**Comment by deep021985** [comment]
I encountered an 'Undefined method block' error when using the code provided. After removing the block, the component resulted to a simple dropdown. Enabling the 'Multiple' option did not produce the desired results.

``
   def type_of_defect_form_column(record, type_of_defect)
    defects  =  ['Insulator', 'Structure', 'Conductor', 'Earthwire', 'Jumper', 'Spacers', 'Vibration Dampers', 'Temperature', 'Span', 'Other']
	select(:record, :type_of_defect, defects, :options => {:multiple => true, :size =>10}, :html_options => {}, &block)
   end
``

**Comment by scambra** [comment]
I tried using active_scaffold config, like you did:

config.columns[:type_of_defect].form_ui = :select
	config.columns[:type_of_defect].options = {
	  :html_options => { :multiple => true },
	  :options => ['Insulator', 'Structure', 'Conductor', 'Earthwire', 'Jumper', 'Spacers', 'Vibration Dampers', 'Temperature', 'Span', 'Other']
	}

And it worked to render a select tag with multiple options. When saved, it converted the array to string, like `["", "Insulator", "Structure"]`, so editing can't restore it. However, it isn't an ActiveScaffold bug, as the column I was using to test was a string column, which can't hold an array. I should add a getter to the model to convert string to array, or better, using serialize in the model. You haven't explained what you did to save multiple choices in a column.

Your helper is wrong, you have to call select like this:

`select(:record, :type_of_defect, defects, {}, {:multiple => true, :size =>10})`

html_options is the 5th argument, so multiple and size options go there, not in the 4th argument which is options hash
