### ISSUE TITLE
Argument Error in create Action #<ArgumentError: wrong number of arguments (given 1, expected 0)>

### ISSUE THREAD

**Issue by siddharth195** [activescaffold/active_scaffold#720]
Hi, 

I have upgraded rails & ruby version and added new authentication flow to the application. I am getting #<ArgumentError: wrong number of arguments (given 1, expected 0)> in create action and it is failing with 500 error

rror {:controller=>"CachesController", :action=>"create", :request=>#<ActionDispatch::Request POST "https://marco-dev1.factset.io/caches" for 172.18.64.171>, :params=>{"utf8"=>"✓", 
"authenticity_token"=>"Dpkf6L7e0gb4EgZHQoiS8SJe09xVqDJsOCjLPj05XN2PR8KmR8m6TEWPOn09-BCIBnxbxOsDLhcB6l3NgFKEaw", 
"record"=>{"name"=>"sid", "hosts"=>["", "478"], "config"=>"", "cache_size"=>"", "ftok"=>"92"}, "commit"=>"Create", "controller"=>"caches", "action"=>"create"}
, :headers=>#<ActionDispatch::Http::Headers:0x00007f0c341583e8 @req=#<ActionDispatch::Request POST "https://marco-dev1.factset.io/caches" for 172.18.64.171>>, :format=>:js, :method=>"POST", :path=>"/caches", :status=>500, :view_runtime=>nil, :db_runtime=>6.264166831970215, :exception=>["ArgumentError", "wrong number of arguments (given 1, expected 0)"], :exception_object=>#<ArgumentError: wrong number of arguments (given 1, expected 0)>} record 2023-11-23T09:41:39.824308Z app[web.2]: Rendered vendor/bundle/ruby/3.1.0/gems/exception_notification-4.5.0/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (Duration: 5.5ms | Allocations: 5089) 2023-11-23T09:41:39.925146Z app[web.2]: Delivered mail 655f1e53c9621_1b11e44352@d323d5c8-475c-4871-bd3f-ee323f0014c8.mail (100.3ms)

before upgrade post request was like this
Parameters: {"utf8"=>"✓", "record"=>{"name"=>"sid", "hosts"=>["", "1245"], "config"=>"", "cache_size"=>"", "ftok"=>"72"}, "commit"=>"Create"}

after upgrade authenticity token is added in the request 
:params=>{"utf8"=>"✓", "authenticity_token"=>"MG34Vc76APWYEjvzPPH4BEzEUY424vT5FlfCke4UybyfZSlNjDrUI2gu5BPOuCIAc8D6bmSbtQRTl49Smuyhag", "record"=>{"name"=>"sid", "hosts"=>["", "1949"], "config"=>"", "cache_size"=>"", "ftok"=>"72"}, "commit"=>"Create", "controller"=>"caches", "action"=>"create"},

Can anyone please help here ? 
And how to solve this issue ?

**Comment by scambra** [comment]
You need to post the backtrace, otherwise I don't know what method is being called with 1 argument but expects 0.

**Comment by hoenth** [comment]
Hi @scambra Thank you so much for continuing your incredible work on this gem. 

I too am seeing the same error when upgrading to Ruby 3.0.6. Here is the bactrace:
```
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/suppressor.rb:43:in `save'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/active_scaffold-3.6.20/lib/active_scaffold/extensions/unsaved_record.rb:15:in `save'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:373:in `insert_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/has_many_association.rb:58:in `insert_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:358:in `block (2 levels) in _create_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:462:in `replace_on_target'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:283:in `add_to_target'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:357:in `block in _create_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:136:in `block in transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:209:in `transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:135:in `transaction'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_association.rb:355:in `_create_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/has_many_association.rb:137:in `_create_record'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/association.rb:205:in `create'
     # /Users/tom.hoen/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/associations/collection_proxy.rb:348:in `create'
```

I believe the issue is that in save method, for ruby 3, we now need to double splat the arguments, 
```
  # automatically unsets the unsaved flag
  def save(**)
    super.tap { self.unsaved = false }
  end
```

I made this change locally and it does seem to fix the error. 

I think the question is whether there are more areas that will need to change to handle ruby 3

**Comment by hoenth** [comment]
I see now that these changes have been made in the master branch. Do you feel it is safe to deploy the master branch, or should we wait until a new version is issued?
