### ISSUE TITLE
select options with a nil value

### ISSUE THREAD

**Issue by moracca** [activescaffold/active_scaffold#721]
when defining a select column, we can provide 
```
config.columns[:my_col].options = {options:  {'option one' => 1, 'option two' =>2}}
```
and this creates the expected options, and also causes the show/list value to represent the textual value once its been set.

If the hash of options contains a nil value however (`{'default option' => nil, 'option one' => 1, 'option two' =>2}`) then the `active_scaffold_translated_option` method ends up setting the option's value to the string "default option" (due to https://github.com/activescaffold/active_scaffold/blob/f496e8f0ef8f13fece2eeeba455a8d7304c9e8fb/lib/active_scaffold/helpers/form_column_helpers.rb#L457).

We can work around this by not providing the nil option in the list, and instead adding `include_blank: 'default option'` to the options hash, which has the intended effect on the select dropdown (`<option value>default option</option>`).

However, in a show/list column, the displayed value is now empty instead of translating it back to the "default option" string.

What is the best practice for providing an option which has a nil value, that will be translated back to the appropriate string when displayed in the list or show views without having to override helper methods (e.g my_col_column and/or my_col_show_column)?

Ideally I'd like to maintain my list of options in a single place and have it be the source or truth, but right now if one of the options includes nil it ends up submitting the value of the display text.

Thanks!

**Comment by scambra** [comment]
If I remember correctly, using blank string '' instead of nil works for
that use case, but i'm not in a computer to test it right now. It may feels
weird, but I think it's the way it works, it should be documented but AS
docs needs much improvement.
