### ISSUE TITLE
Changing Form Field Issue

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#723]
I would like to update the subdivision dropdown menu based on the selection made in the division dropdown menu. However, when I implement the code according to the documentation, the subdivision dropdown displays all values instead of filtering them based on the division selection. 

Here is my code: 

```rb
class LinesTowersController < ApplicationController
  active_scaffold :lines_tower do |config|   
    config.label = "Lines & Towers"
	 [:delete].each {|a| config.actions.exclude a}
	
    config.columns = [ :division, :subdivision]
    config.list.columns = [:division, :subdivision]
    config.update.columns = [:division, :subdivision]

	config.columns[:division].form_ui = :select
	config.columns[:division].update_columns = :subdivision 
	config.columns[:subdivision].form_ui = :select	
  end
   

end

module LinesTowersHelper
  def options_for_association_conditions(association, record)
    if association.name == :subdivision
      {'subdivisions.division_id' => record.division_id}
    else
      super
    end
  end
end
```

**Trace:**
Started POST "/lines_towers/render_field?column=division" for ::1 at 2024-03-04 17:48:33 +0530
Processing by LinesTowersController#render_field as JS
  Parameters: {"value"=>"8", "source_id"=>"record_division_", "column"=>"division"}
  Division Load (0.3ms)  SELECT `divisions`.* FROM `divisions` WHERE `divisions`.`id` = 8 LIMIT 1
  Rendering C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb
  Subdivision Load (0.2ms)  SELECT `subdivisions`.* FROM `subdivisions`
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 2.5ms | Allocations: 3368)
  Rendered C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb (Duration: 2.9ms | Allocations: 3506)
Completed 200 OK in 7ms (Views: 3.3ms | ActiveRecord: 0.5ms | Allocations: 6146)

**Comment by scambra** [comment]
You could debug it adding a logger.debug line at the beginning of options_for_association_conditions:

logger.debug "#{association.name}: #{record.division_id}"

However, if record.division_id would be nil, which I don't know why it would be nil, you should get SELECT subdivisions.* FROM subdivisions WHERE subdivisions.division_id IS NULL. So I think your helper method is not being called.

Do you have defined options_for_association_conditions in other helper module? If you are not using `clear_helpers` in your ApplicationController, all the helpers are available to every controller, so you may have options_for_association_conditions which is not calling super, or has other code for association :subdivision

**Comment by deep021985** [comment]
Resolved through clear_helpers.. Thank you so much.

**Comment by scambra** [comment]
I think I should recommend using clear_helpers in the README, because there are some methods which are usually overrided for different controllers, with the same name, such as active_scaffold_enum_options, options_for_association_conditions, association_klass_scoped, and having all helpers available to every controller makes hard to debug some issues.

**Comment by deep021985** [comment]
Indeed, this would prove to be quite beneficial.

**Comment by deep021985** [comment]
With the following code, only the last dropdown (towers) functions correctly, while the other dropdowns display all values from the table. Please help

class LinesTowersController < ApplicationController
  clear_helpers
  
  active_scaffold :lines_tower do |config|   
    config.label = "Lines & Towers"
	 [:delete].each {|a| config.actions.exclude a}
	
    config.columns = [:circle, :division, :subdivision, :ehv_line, :tower]
    config.create.columns = [:division,:subdivision, :ehv_line, :tower]
    config.list.columns = [:circle, :division, :subdivision, :ehv_line, :tower]
    config.update.columns = [:subdivision, :ehv_line, :tower]

	
	config.columns[:division].form_ui = :select
	config.columns[:division].update_columns =  :subdivision
	config.columns[:subdivision].form_ui = :select
	config.columns[:subdivision].update_columns =  :ehv_line
	config.columns[:ehv_line].form_ui = :select
	config.columns[:ehv_line].update_columns =  :tower
	 config.columns[:tower].form_ui = :select
	
  end
end

**Helper:**
  def options_for_association_conditions(association, record)
    if association.name == :subdivision
      {'subdivisions.division_id' => record.division_id}
    else
      super
    end
    if association.name == :ehv_line
      {'ehv_lines.subdivision_id' => record.subdivision_id}
    else
      super
    end
	
	if association.name == :tower
      {'towers.ehv_line_id' => record.ehv_line_id}
    else
      super
    end
  end

**Trace:**
  Division Load (0.3ms)  SELECT `divisions`.* FROM `divisions` WHERE `divisions`.`id` = 5 LIMIT 1
  Rendering C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb
  Subdivision Load (0.2ms)  SELECT `subdivisions`.* FROM `subdivisions`
  EhvLine Load (0.2ms)  SELECT `ehv_lines`.* FROM `ehv_lines` WHERE `ehv_lines`.`id` = 0 LIMIT 1
  EhvLine Load (0.8ms)  SELECT `ehv_lines`.* FROM `ehv_lines`
  Tower Load (0.3ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`id` = 0 LIMIT 1
  Tower Load (34.2ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`ehv_line_id` = 0
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 37.1ms | Allocations: 1004)
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 62.0ms | Allocations: 47392)
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 67.3ms | Allocations: 52007)
  Rendered C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb (Duration: 67.7ms | Allocations: 52143)
Completed 200 OK in 71ms (Views: 32.6ms | ActiveRecord: 36.0ms | Allocations: 54616)


Started POST "/lines_towers/render_field?column=subdivision" for ::1 at 2024-03-09 00:27:38 +0530
Processing by LinesTowersController#render_field as JS
  Parameters: {"value"=>"19", "source_id"=>"record_subdivision_", "column"=>"subdivision"}
  Subdivision Load (0.3ms)  SELECT `subdivisions`.* FROM `subdivisions` WHERE `subdivisions`.`id` = 19 LIMIT 1
  Rendering C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb
  EhvLine Load (0.1ms)  SELECT `ehv_lines`.* FROM `ehv_lines` WHERE `ehv_lines`.`id` = 0 LIMIT 1
  EhvLine Load (0.8ms)  SELECT `ehv_lines`.* FROM `ehv_lines`
  Tower Load (0.4ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`id` = 0 LIMIT 1
  Tower Load (34.1ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`ehv_line_id` = 0
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 37.1ms | Allocations: 1004)
  Rendered collection of C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (Duration: 63.2ms | Allocations: 48305)
  Rendered C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb (Duration: 63.6ms | Allocations: 48441)
Completed 200 OK in 67ms (Views: 28.9ms | ActiveRecord: 35.7ms | Allocations: 50916)


Started POST "/lines_towers/render_field?column=ehv_line" for ::1 at 2024-03-09 00:27:49 +0530
Processing by LinesTowersController#render_field as JS
  Parameters: {"value"=>"685", "source_id"=>"record_ehv_line_", "column"=>"ehv_line"}
  EhvLine Load (0.3ms)  SELECT `ehv_lines`.* FROM `ehv_lines` WHERE `ehv_lines`.`id` = 685 LIMIT 1
  Rendering C:/Ruby32-x64/lib/ruby/gems/3.2.0/bundler/gems/active_scaffold-c69adc1be514/app/views/active_scaffold_overrides/render_field.js.erb
  Tower Load (0.1ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`id` = 0 LIMIT 1
  Tower Load (34.0ms)  SELECT `towers`.* FROM `towers` WHERE `towers`.`ehv_line_id` = 685

**Comment by scambra** [comment]
When a column changes only the value of the changed column is submitted. If
multiple fields are refreshed, as your case with multi level chain, you can
enable send_form_on_update_column

**Comment by deep021985** [comment]
I attempted to add the "send_form_on_update_column" to my code, but unfortunately, only the last field, which is the towers, is being updated based on the EHV line. The upper chain still contains all values from the table.  Could you please advise me on what I might be missing in my implementation? 

  active_scaffold :lines_tower do |config|   
    config.label = "Lines & Towers"
	 [:delete].each {|a| config.actions.exclude a}
	
    config.columns = [:circle, :division, :subdivision, :ehv_line, :tower]
    config.create.columns = [:division,:subdivision, :ehv_line, :tower]
    config.list.columns = [:circle, :division, :subdivision, :ehv_line, :tower]
    config.update.columns = [:subdivision, :ehv_line, :tower]

	
	config.columns[:division].form_ui = :select
	config.columns[:division].update_columns =  :subdivision
	config.columns[:subdivision].form_ui = :select
	config.columns[:subdivision].update_columns =  :ehv_line
	config.columns[:subdivision].send_form_on_update_column = true
	config.columns[:ehv_line].form_ui = :select
	config.columns[:ehv_line].send_form_on_update_column = true
	config.columns[:ehv_line].update_columns =  :tower
	config.columns[:tower].form_ui = :select
	
  end

**Helper**

  def options_for_association_conditions(association, record)
    if association.name == :subdivision
      {'subdivisions.division_id' => record.division_id}
    else
      super
    end
    if association.name == :ehv_line
      {'ehv_lines.subdivision_id' => record.subdivision_id}
    else
      super
    end
   if association.name == :tower
      {'towers.ehv_line_id' => record.ehv_line_id}
    else
      super
    end
  end

**Comment by scambra** [comment]
Enabling send_form_on_update_column will submit the whole form, in params[:record], instead of sumitting the value for changed field in params[:value]. But when ehv_line changes, although the whole form is submitted, it will refresh only :tower, as set in `config.columns[:ehv_line].update_columns`. 

However, when subdivision is changed, it will refresh :ehv_line, as set in `config.columns[:subdivision].update_columns`, and will refresh :tower too because :ehv_line has update_columns too. Then, as params[:record] is submitted, it will use the submitted value for ehv_line_id to refresh tower, instead of saved value.

You didn't enable send_form_on_update_column for :division column, so changing division column will refresh subdivision, ehv_line and tower, but only the value for division was submitted.

**Comment by deep021985** [comment]
I attempted to enable the "send_form_on_update_column" for the division, but unfortunately, it did not have the desired effect. The issue persists where only the last towers dropdown is affected, while the others remain populated with all data.
Also as mentioned, while utilizing the helper "_from_column," the "changing_form_fields" functionality does not seem to work as expected. When I remove helper it works. 

   def ehv_line_form_column(record, ehv_line)
	 line_array = EhvLine.where("subdivision_id IN (?)", session[:subdivision_ids]).distinct.collect {|u| [u.to_label, u.id] }

      if controller.action_name == 'new'	    
	    select(:record, :ehv_line, line_array, :include_blank => 'select')
	  elsif controller.action_name == 'edit' 		
		ehv_line = DroneUtilization.find(params[:id]).ehv_line_id		
		select(:record, :ehv_line,line_array, :selected => ehv_line)		
	  else	
		select(:record, :ehv_line, line_array, :include_blank => 'select')
      end
   end

**Comment by scambra** [comment]
If you have a helper ehv_line_form_column which checks action_name, it won't work fine with update_columns, as the helper will be called from action 'render_field', both for create and update forms. It would be better to check if record.id is nil to distinguish between create and update form, so it works with render_field too.

Anyway, I don't know why you need such helper, you are adding a select tag, as form_ui :select would do, and the only difference is setting the selected value. You could use options_for_association_conditions for the select options:

```
def options_for_association_conditions(association, record)
  if association.name == :ehv_line
    {subdivision_id: session[:subdivision_ids]}
  else
    super
  end
end
```

If need to use distinct, then you can use `association_klass_scoped` instead:

```
def association_klass_scoped(association, klass, record)
  if association.name == :ehv_line
    super.where(subdivision_id: session[:subdivision_ids]).distinct
  else
    super
  end
end
```

If needed to change the selected value when opening edit form (not sure why), you can use do_edit in the controller:

```
def do_edit
  super
  @record.ehv_line = DroneUtilization.find(params[:id]).ehv_line_id
end
```
