### ISSUE TITLE
Active scaffold not respecting special character in search

### ISSUE THREAD

**Issue by siddharth195** [activescaffold/active_scaffold#724]
Hi,

Do we have any way so that special characters are respected in search for example below _ o _ is not respected properly in search we are getting results which does not contain exactly _ o _  

![image](https://github.com/activescaffold/active_scaffold/assets/52989183/22f2f7fe-d9b4-421d-8116-22aeeab7f9e1)

Thanks,
Sid

**Comment by scambra** [comment]
Fixed in 3-7-stable branch and master branch
_ has special meaning when used with LIKE operator, it's a wildcard for one character, so text to search must be escaped with sanitize_sql_like rails method.
