### ISSUE TITLE
undefined method `label=' for an instance of ActiveScaffold::Config::Core::UserSettings

### ISSUE THREAD

**Issue by beatjoerg** [activescaffold/active_scaffold#730]
In version 4.0.0rc1 I'm unable to override the label like this:

```
def update_table_config
    active_scaffold_config.label = 'Users'
end
```

it throws an error:
undefined method `label=' for an instance of ActiveScaffold::Config::Core::UserSettings

**Comment by scambra** [comment]
I have fixed it in master. Master should be pretty stable branch until v4.0 is released, so you can use github: 'activescaffold/active_scaffold' in your Gemfile for now

4.0.0 has backward incompatible changes which will require to rewrite some code if you have config changes per request. They were required for threadsafe when changing config per request, and keeping code simple without affecting performance. You may get `can't modify frozen` errors when changing a column setting, or action's columns (like adding or removing).

To change a column per request you have to use this now:

```
active_scaffold_config.columns.override(:column_name).form_ui = ...
```

Or using block for multiple changes:

```
active_scaffold_config.columns.override(:column_name) do |column|
  column.form_ui = ...
  column.options = ...
end
```

After calling `override(:column_name)` once, next calls may use `columns.override(:column_name)` or `columns[:column_name]`, but the first time override is needed to avoid the frozen object error.

For the action's columns, like `active_scaffold_config.create.columns`, you have to use `override_columns` the first time, like `active_scaffold_config.create.override_columns.exclude :column_name` to exclude a column, or `active_scaffold_config.create.override_columns << :column_name` to add a column. Again, only needed the first call, next calls to `active_scaffold_config.create.columns` won't return frozen object.
