### ISSUE TITLE
Demo site mostly broken

### ISSUE THREAD

**Issue by epitron** [activescaffold/active_scaffold#85]
There are 3 models on the demo site: `users`, `permissions`, and `roles`.

Only roles is still working ( http://demo.activescaffold.com/roles ) -- the rest give redirect loops if you go to their pages (eg: http://demo.activescaffold.com/users ), and 404s if you try to view the associations (on the `roles` page).

**Comment by ain** [comment]
Still on error page the demo. +1 for the fix.

**Comment by alexbottoni** [comment]
Do you have any intention to resurrect the project website (and its demo) with the original domain name (activescaffold.com) or a new one (activescaffold.info or something like that)?

Do you think the dead link on github page and readme file can be removed (at least until a new website is available)?

**Comment by scambra** [comment]
I would like to do that, but I'm alone here and lots of another tasks to do (more testing, rdoc, threadsafe, some samples or demo) I can't reuse original domain because it's registered by a previous developer and I don't get answer from him. I'm open to collaboration.
